using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using PoliSim.Data;
using PoliSim.Simulation;
using UnityEngine;

namespace PoliSim.EditorTools
{
    /// <summary>
    /// P5-B1 (2026-09-05) - THE BUDGET PREMISE, MEASURED. Before Track B builds nominal lines that persist and
    /// index, this dump states what the lines ARE today and proves it by running the model, then audits every
    /// slider at magnitude. Three parts, all generated:
    ///
    /// <para>§1 the lines' rules - for every spending line the probed country holds: what the dial sets (a
    /// PERCENTAGE of the line's current nominal amount, clamped to the dial's range and then to a band around the
    /// seed), what the fiscal-year boundary does to it (nothing - the amount persists; the DIAL is a per-turn
    /// delta and reads zero the next year, which is the "normalises after a year" a player sees), and what moves
    /// the line between player changes (potential growth on every line; the pension and health pressures; the
    /// enforcement and sector costs). Each claim is a probe: the line's amount over five untouched turns against
    /// the growth factor, the inflation compound and the GDP path; a +full-range step on one line followed by
    /// five untouched turns against the baseline.</para>
    ///
    /// <para>§2 the tax lines - revenue = GDP × rate × the base's share of GDP (TaxBaseTable, D-16), so the base
    /// moves with NOMINAL GDP and with nothing else; the elasticity of revenue to nominal GDP at a held rate is
    /// measured on the run, and its elasticity to employment and to the distribution is zero by construction.</para>
    ///
    /// <para>§3 the liveness audit at magnitude (C-C10's leave-one-out idea, at the dial's full range): every
    /// slider stepped by its full range on the first turn, the model's response at one and five years read on
    /// the headline quantities, and the slider classed LIVE, LIVE-BUT-NEGLIGIBLE (the largest headline move
    /// below <see cref="NegligibleRelative"/> of the quantity, or below <see cref="NegligibleAbsolute"/> where the quantity
    /// is a rate near zero) or DEAD (no public EconomyState float of the probed country moved at five years).</para>
    ///
    /// Run: `Unity.exe -batchmode -nographics -projectPath &lt;path&gt; -executeMethod
    /// PoliSim.EditorTools.BudgetPremiseDump.Run -logFile &lt;path&gt; [-premiseout=&lt;file&gt;]`
    /// </summary>
    public static class BudgetPremiseDump
    {
        private const int Horizon = 5;
        private const float NegligibleRelative = 0.0005f;   // [AUTHORED-DRAFT] threshold: half a tenth of a percent of the quantity after five years
        private const float NegligibleAbsolute = 0.01f;     // [AUTHORED-DRAFT] for rate-like quantities under 1: a hundredth of a point
        private static readonly string[] Headline = { "GDP", "Unemployment", "Inflation", "Budget", "GovernmentDebt", "ApprovalRating", "PovertyRate", "Gini", "Investment", "Consumption" };

        public static void Run()
        {
            CheckExit.ArmLogFold();
            string outPath = LeverProbes.Arg("-premiseout=", Path.Combine(Application.dataPath, "..", "BUDGET_PREMISE.md"));
            var sb = new StringBuilder(1 << 17);
            sb.Append("# THE BUDGET PREMISE, MEASURED - what a spending line and a tax line are today, and whether every slider moves the model\n\n");
            sb.Append($"GENERATED by `BudgetPremiseDump` ({DateTime.Now:yyyy-MM-dd}), not transcribed. Probed country {LeverProbes.Probed}, seed {LeverProbes.Seed}, {Horizon} turns (one turn is one year). Do not edit by hand; re-run the dump.\n\n");

            // ---- §1 the lines' rules, proved on the run --------------------------------------------------
            var baseLines = new Dictionary<SpendingCategory, List<float>>();
            var baseGdp = new List<float>();
            var baseInflation = new List<float>();
            var seedDriver = new Dictionary<SpendingCategory, float>();
            var endDriver = new Dictionary<SpendingCategory, float>();
            var baseRevenue = new Dictionary<TaxType, List<float>>();
            var baseRates = new Dictionary<TaxType, float>();
            float potentialGrowth = 0f;
            LeverProbes.RunWorld(null, Horizon, (sim, world, country, turn) =>
            {
                potentialGrowth = country.PotentialGrowthRate;
                foreach (SpendingLine l in country.SpendingLines) { endDriver[l.Category] = SpendingDrivers.Level(SpendingDrivers.Of(l.Category), country); }
                foreach (SpendingLine l in country.SpendingLines)
                {
                    if (!baseLines.TryGetValue(l.Category, out List<float> list)) { baseLines[l.Category] = list = new List<float>(); }
                    list.Add(l.Amount);
                }
                baseGdp.Add(country.State.GDP);
                baseInflation.Add(country.State.Inflation);
                foreach (TaxLine t in country.TaxLines)
                {
                    if (!t.IsImplemented || t.Type == TaxType.Tariffs) { continue; }
                    if (!baseRevenue.TryGetValue(t.Type, out List<float> list)) { baseRevenue[t.Type] = list = new List<float>(); baseRates[t.Type] = t.Rate; }
                    list.Add(country.State.GDP * (t.Rate / 100f) * TaxBaseTable.BaseShareOfGdp(country.Id, t.Type));
                }
            }, out _);
            float seedGdp = 0f;
            var seedLines = new Dictionary<SpendingCategory, (float Amount, bool Mandatory)>();
            {
                SimulationRandom.Seed(LeverProbes.Seed);
                World w = WorldFactory.CreateDefault();
                Country c = w.GetCountry(LeverProbes.Probed);
                seedGdp = c.State.GDP;
                foreach (SpendingLine l in c.SpendingLines) { seedLines[l.Category] = (l.Amount, l.IsMandatory); }
                foreach (SpendingLine l in c.SpendingLines) { seedDriver[l.Category] = SpendingDrivers.Level(SpendingDrivers.Of(l.Category), c); }
            }

            sb.Append("## 1. The spending lines - what the dial sets, what the year boundary does, what moves the line between changes\n\n");
            sb.Append("**What the dial sets (from the code, `ApplySpendingLineChanges`):** a PERCENTAGE change of the line's CURRENT nominal amount, applied once on the turn the decision carries it - clamped to ±30 % for a Discretionary line and ±15 % for a Mandatory one, and then the amount is clamped to [0.2×, 3×] of the line's seed anchor (`ClampToSeedRange`); since P5-B2 a line can also be SET to a nominal amount (`PolicyDecision.SpendingNominalTargets`) and PINNED (`PolicyDecision.SpendingPinChanges`). The amount is nominal (the same $B-scale unit as GDP) and PERSISTS - nothing resets it at the fiscal-year boundary (`IsFiscalYearStart` only opens the budget process). **The \"normalises after a year\" a player sees is the DIAL, not the line:** `PolicyDecision.SpendingLineChanges` is a per-turn delta, consumed on application, so next year's dial reads 0 % while the amount it set stays. Proved below.\n\n");
            sb.Append("**What moves a line between player changes (from the code, P5-B2's `IndexSpendingLines`):** a line with a DRIVER (`SpendingDrivers`: pensions to the 65+ cohort, unemployment benefits to the unemployment rate, education to the 0–19 cohort, health to the age-cost index, …) indexes to its level as the ratio now/then - there is NO price term, the book being in constant prices (`SimulationManager.IndexSpendingLines` says why, with the measurement); a line with no driver holds its figure; a pinned line takes none of it; a country the player does not govern also grows its lines at its real potential rate (the AI's budget rule). The Justice (else PublicServices) and HomelandSecurity (else PublicServices) lines take the crime dials' enforcement cost; the Commerce (else PublicServices) line the sector dials' support cost (P4-B3). Before P5-B2 every line grew at the seed's potential rate and nothing else (§312). Proved below - the run below has NO player, so every country is under the AI rule.\n\n");

            sb.Append($"| line | driver | mandatory | seed ($B) | dial range | amount after {Horizon} turns | ratio | price index | driver ratio | real growth (AI) | residual |\n|---|---|---|---|---|---|---|---|---|---|---|\n");
            float growthCompound = Mathf.Pow(1f + potentialGrowth / 100f, Horizon);
            float gdpRatio = baseGdp[Horizon - 1] / seedGdp;
            foreach (KeyValuePair<SpendingCategory, List<float>> kv in baseLines.OrderBy(k => k.Key.ToString(), StringComparer.Ordinal))
            {
                (float seed, bool mandatory) = seedLines[kv.Key];
                float ratio = kv.Value[Horizon - 1] / seed;
                float driverRatio = seedDriver.TryGetValue(kv.Key, out float d0) && d0 > 0f && endDriver.TryGetValue(kv.Key, out float d5) ? d5 / d0 : 1f;
                float residual = ratio / (driverRatio * growthCompound);
                sb.Append($"| {kv.Key} | {SpendingDrivers.Name(SpendingDrivers.Of(kv.Key))} | {(mandatory ? "yes" : "no")} | {Inv(seed)} | ±{(mandatory ? 15 : 30)} % | {Inv(kv.Value[Horizon - 1])} | {Inv(ratio)} | {Inv(driverRatio)} | {Inv(growthCompound)} | {Inv(residual)} |\n");
            }
            sb.Append($"\nNominal GDP over the same {Horizon} turns grew by {Inv(gdpRatio)}×. A residual of 1.000 means the line is exactly its seed times its driver (times real growth under the AI rule) - the enforcement and support costs move a line only when their dials do, and nothing here moved them.\n\n");

            // the persistence probe: +full range on the first Discretionary line, then untouched
            SpendingCategory probeCat = baseLines.Keys.FirstOrDefault(k => !seedLines[k].Mandatory);
            if (baseLines.Count > 0)
            {
                var stepped = new List<float>();
                LeverProbes.Lever step = new LeverProbes.Lever { Family = "Budget line", Name = "step", Arm = (sim, c, d) => d.SpendingLineChanges[probeCat] = 30f };
                LeverProbes.RunWorld(step, Horizon, (sim, world, country, turn) =>
                {
                    stepped.Add(country.SpendingLines.Find(l => l.Category == probeCat).Amount);
                }, out _);
                sb.Append($"**The persistence probe** ({probeCat}, a Discretionary line, stepped +30 % - the dial's full range - on turn 1, then untouched): ");
                var parts = new List<string>();
                for (int t = 0; t < Horizon; t++) { parts.Add($"year {t + 1} {Inv(stepped[t] / baseLines[probeCat][t])}×"); }
                sb.Append("the line against the untouched baseline reads " + string.Join(", ", parts) + $". The step PERSISTS at its full ratio through every later year (the index applies to both); nothing normalises the amount. The dial reads 0 % from year 2: the decision's delta was consumed.\n\n");
            }

            // ---- §2 the tax lines ------------------------------------------------------------------------
            sb.Append("## 2. The tax lines - revenue = GDP × rate × the base's share of GDP\n\n");
            sb.Append("From the code (`GetTotalTaxRevenue`, `TaxBaseTable.BaseShareOfGdp`, D-16): a tax line's revenue is nominal GDP times the rate times a FIXED per-country share of GDP for that base. The base therefore moves one-for-one with nominal GDP and with nothing else - not employment, not the wage bill, not the distribution (F4's income dimension does not enter). At a held rate the revenue's elasticity to nominal GDP is exactly 1 by construction; the run below measures it.\n\n");
            sb.Append($"| tax line | rate held (%) | revenue year 1 ($B) | revenue year {Horizon} ($B) | ratio | GDP ratio | elasticity to nominal GDP |\n|---|---|---|---|---|---|---|\n");
            foreach (KeyValuePair<TaxType, List<float>> kv in baseRevenue.OrderBy(k => k.Key.ToString(), StringComparer.Ordinal))
            {
                float r1 = kv.Value[0], r5 = kv.Value[Horizon - 1];
                float gdp1 = baseGdp[0], gdp5 = baseGdp[Horizon - 1];
                float elasticity = Mathf.Abs(Mathf.Log(gdp5 / gdp1)) > 1e-6f ? Mathf.Log(r5 / r1) / Mathf.Log(gdp5 / gdp1) : float.NaN;
                sb.Append($"| {kv.Key} | {Inv(baseRates[kv.Key])} | {Inv(r1)} | {Inv(r5)} | {Inv(r5 / r1)} | {Inv(gdp5 / gdp1)} | {Inv(elasticity)} |\n");
            }
            sb.Append("\nA rate held constant yields rising revenue in a growing economy and falling revenue in a recession - through nominal GDP alone. What is NOT there: an employment channel (a recession that cuts employment more than GDP does not cut payroll revenue more), and a distribution channel (a rising Gini does not move income-tax revenue). Track B3's family.\n\n");

            // ---- §3 the liveness audit at magnitude ----------------------------------------------------
            sb.Append("## 3. The liveness audit at magnitude - every slider stepped by its full range, read at one and five years\n\n");
            sb.Append($"A slider is **LIVE** when its step moves a headline quantity ({string.Join(", ", Headline)}) of the probed country by at least {NegligibleRelative:P2} of itself (or {NegligibleAbsolute} of a point where the quantity sits under 1) at one year or at five; **LIVE-BUT-NEGLIGIBLE** when something moves but no headline quantity by that much at five years; **DEAD** when no public EconomyState float of the probed country moves at all at five years. **NOT ARMABLE** when the lever is not the probed country's to pull, and the row says why (P5-B4): a tax it has not implemented (the row is drawn disabled), the policy rate where a governor sits, the base tariff of a customs-union member, a partner it does not trade with, a fund or programme it does not have. The thresholds are stated, not derived: half a tenth of a percent after five years is the size of a rounding difference on the sheet.\n\n");
            List<LeverProbes.Quantity> quantities = LeverProbes.BuildQuantities();
            var headlineIndex = new List<int>();
            for (int i = 0; i < quantities.Count; i++)
            {
                foreach (string h in Headline) { if (quantities[i].Name == "EconomyState." + h) { headlineIndex.Add(i); } }
            }
            float[] base1 = LeverProbes.RunOne(null, quantities, 1, out _);
            float[] base5 = LeverProbes.RunOne(null, quantities, Horizon, out _);
            List<LeverProbes.Lever> levers = LeverProbes.BuildLevers(includeLaws: false, budgetLinePercent: null);
            sb.Append("| slider | family | largest headline move at 1 yr | at 5 yr | anything moved at 5 yr | class |\n|---|---|---|---|---|---|\n");
            int live = 0, negligible = 0, dead = 0, notArmed = 0;
            foreach (LeverProbes.Lever lever in levers)
            {
                float[] p1 = LeverProbes.RunOne(lever, quantities, 1, out bool armed);
                if (!armed) { sb.Append($"| {lever.Name} | {lever.Family} | - | - | - | NOT ARMABLE for {LeverProbes.Probed}: {lever.NotArmable} |\n"); notArmed++; continue; }
                float[] p5 = LeverProbes.RunOne(lever, quantities, Horizon, out _);
                (string name1, float rel1, bool big1) = Largest(quantities, headlineIndex, base1, p1);
                (string name5, float rel5, bool big5) = Largest(quantities, headlineIndex, base5, p5);
                bool anything = false;
                for (int i = 0; i < quantities.Count && !anything; i++)
                {
                    if (quantities[i].Group != "EconomyState") { continue; }
                    if (Mathf.Abs(p5[i] - base5[i]) > 1e-6f * Mathf.Max(1f, Mathf.Abs(base5[i]))) { anything = true; }
                }
                string cls = !anything ? "**DEAD**" : (big1 || big5) ? "LIVE" : "LIVE-BUT-NEGLIGIBLE";
                if (!anything) { dead++; } else if (big1 || big5) { live++; } else { negligible++; }
                sb.Append($"| {lever.Name} | {lever.Family} | {Describe(name1, rel1)} | {Describe(name5, rel5)} | {(anything ? "yes" : "no")} | {cls} |\n");
            }
            sb.Append($"\n**{live} LIVE · {negligible} LIVE-BUT-NEGLIGIBLE · {dead} DEAD · {notArmed} not armable for {LeverProbes.Probed}, each with its reason.** P5-B4 (2026-09-05) worked the list down: a dead slider either gained a sourced transmission or was retired by name; a lever that is not the country's to pull is NOT ARMABLE, not dead.\n");

            File.WriteAllText(outPath, sb.ToString());
            Debug.Log($"PREMISE: wrote {Path.GetFullPath(outPath)} - {baseLines.Count} spending lines, {baseRevenue.Count} tax lines, {levers.Count} sliders: {live} live, {negligible} negligible, {dead} dead, {notArmed} not armable.");
            CheckExit.Finish(0);
        }

        private static (string Name, float Rel, bool Big) Largest(List<LeverProbes.Quantity> quantities, List<int> headline, float[] baseline, float[] probed)
        {
            string best = "-"; float bestRel = 0f; bool big = false;
            foreach (int i in headline)
            {
                float b = baseline[i], p = probed[i];
                float rel = Mathf.Abs(b) >= 1f ? Mathf.Abs(p - b) / Mathf.Abs(b) : Mathf.Abs(p - b);
                bool over = Mathf.Abs(b) >= 1f ? rel >= NegligibleRelative : rel >= NegligibleAbsolute;
                if (rel > bestRel) { bestRel = rel; best = quantities[i].Name.Replace("EconomyState.", ""); }
                if (over) { big = true; }
            }
            return (best, bestRel, big);
        }

        private static string Describe(string name, float rel) => rel <= 0f ? "none" : $"{name} {rel:P3}";
        private static string Inv(float v) => v.ToString("0.###", CultureInfo.InvariantCulture);
    }
}
