using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using PoliSim.Data;
using PoliSim.Simulation;
using PoliSim.UI;
using UnityEngine;
using Debug = UnityEngine.Debug;

namespace PoliSim.EditorTools
{
    /// <summary>
    /// **D18's inventory: the asset request's spine, emitted from the coverage checks' own print.**
    ///
    /// <para><b>Why this exists.</b> Every asset request before D18 was written by reading the checks
    /// and typing what they said into a document. That is a transcription, and this project has the
    /// receipts on what transcriptions do: `CheckSuite`'s own doc comment read "TWENTY-ONE" while its
    /// array held twenty-five, and section 0 of the request document still said "52 undrawn marks" and
    /// "two StatNodeId icons when those rows are promoted" - **both false today** (43 and none). Neither
    /// was a lie when written. Both went stale the moment the repo moved, and no check could see it,
    /// because nothing compares a sentence in a markdown file against the thing it describes.</para>
    ///
    /// <para><b>What it does instead.</b> <see cref="Emit"/> RUNS the coverage checks in-process,
    /// captures what they log, and writes their own lines into a markdown body under the generated-block
    /// convention this repo already proves (`ElectionsDataCatalogGenerator` / `GeneratedCatalogCheck`):
    /// a DO-NOT-EDIT stamp, a digest, and drift caught by comparing the digest rather than by parsing
    /// the document. <see cref="Run"/> is that guard: it rebuilds the body and fails the bar when the
    /// request document's block and the repo disagree. **The figures in D18 are therefore not claims
    /// about the checks - they ARE the checks, one splice removed.**</para>
    ///
    /// <para>⚠ <b>It re-runs the checks rather than re-deriving their facts.</b> A second enumeration of
    /// the same subject is a second thing to keep true, and the first disagreement between them would be
    /// settled by whichever was edited last. The one place this file enumerates anything itself is the
    /// per-country grouping the ask needs (which parties, in which chamber, at what seat count) - and
    /// that grouping is CROSS-CHECKED against the counts the check printed, so the two cannot drift
    /// apart silently: they disagree, and the run says so and fails.</para>
    ///
    /// <para><b>The naming rule is verified, not asserted.</b> The stem a mark will be loaded by is
    /// `mark_party_&lt;iso2&gt;_&lt;abbrev&gt;`. That rule is not this file's invention: it is re-derived
    /// against every delivered mark on every run, and if one disagrees, the rule is wrong and the run
    /// fails rather than printing a proposed filename nobody can load.</para>
    ///
    /// <para>Run: `Tools/d18_inventory.sh` (Unity batch, then the splice), or
    /// `-executeMethod PoliSim.EditorTools.D18Inventory.Emit` for the body alone.</para>
    /// </summary>
    public static class D18Inventory
    {
        /// <summary>The document whose block this guards. Relative to the project root, which is the
        /// working directory under `-batchmode`.</summary>
        public const string Document = "CLAUDE_DESIGN_ASSET_REQUEST.md";

        /// <summary>Where <see cref="Emit"/> leaves the body for the splice tool. Under `Logs/`, which is
        /// gitignored: the body's home is the request document, and a second tracked copy would be a
        /// second thing to keep true.</summary>
        public const string BodyFile = "Logs/d18_inventory.md";

        private const string BeginPrefix = "<!-- GENERATED by D18Inventory.Emit (Tools/d18_inventory.sh). DO NOT EDIT BY HAND. source-digest: ";
        private const string BeginSuffix = " -->";
        private const string EndMarker = "<!-- END GENERATED -->";

        /// <summary>ISO 3166-1 alpha-2, the code the delivered mark stems already use (`mark_party_se_s`,
        /// `mark_party_us_rep`). Declared here so the rule can be CHECKED against those files rather than
        /// trusted - see <see cref="Build"/>.</summary>
        private static string Iso2(CountryId id)
        {
            switch (id)
            {
                case CountryId.USA:     return "us";
                case CountryId.Sweden:  return "se";
                case CountryId.Germany: return "de";
                case CountryId.France:  return "fr";
                case CountryId.Italy:   return "it";
                case CountryId.Poland:  return "pl";
                default: return null;
            }
        }

        // ------------------------------------------------------------------------------------------
        // Entry points
        // ------------------------------------------------------------------------------------------

        /// <summary>Writes the body to <see cref="BodyFile"/> and prints its digest. Exits non-zero when
        /// the inventory could not be built - an inventory nobody can trust must not be spliced into an
        /// ask that goes to another party.</summary>
        public static void Emit()
        {
            string body = Build(out string fault);

            string path = Path.Combine(Directory.GetCurrentDirectory(), BodyFile.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, body, new UTF8Encoding(false));

            Debug.Log($"D18GEN: wrote {BodyFile} - {body.Length} chars, {CountLines(body)} line(s), digest {Digest(body)}");

            if (fault != null)
            {
                Debug.LogError("D18GEN: " + fault);
                CheckExit.Finish(1);
                return;
            }

            CheckExit.Finish(0);
        }

        /// <summary>The drift guard, in the cheap bar: rebuild the body and require the request
        /// document's generated block to be it. ⚠ A missing block FAILS - the ask is sent to another
        /// party, and an inventory that is simply absent is the same accident as one that is stale.</summary>
        public static void Run()
        {
            string body = Build(out string fault);
            if (fault != null)
            {
                Debug.LogError("D18INV: the inventory could not be built - " + fault + ". VERIFIED NOTHING about the document.");
                CheckExit.Finish(1);
                return;
            }

            string path = Path.Combine(Directory.GetCurrentDirectory(), Document);
            if (!File.Exists(path))
            {
                Debug.LogError($"D18INV: {Document} is not on disk; the generated inventory has nothing to be compared against. VERIFIED NOTHING.");
                CheckExit.Finish(1);
                return;
            }

            string doc = File.ReadAllText(path).Replace("\r\n", "\n");
            int begin = doc.IndexOf(BeginPrefix, StringComparison.Ordinal);
            int end = doc.IndexOf(EndMarker, StringComparison.Ordinal);
            if (begin < 0 || end < 0 || end < begin)
            {
                Debug.LogError($"D18INV: {Document} carries no generated inventory block. Run Tools/d18_inventory.sh.");
                CheckExit.Finish(1);
                return;
            }

            int stampEnd = doc.IndexOf(BeginSuffix, begin, StringComparison.Ordinal);
            string stamped = stampEnd < 0
                ? "(unreadable)"
                : doc.Substring(begin + BeginPrefix.Length, stampEnd - begin - BeginPrefix.Length).Trim();
            string now = Digest(body);

            int bodyStart = doc.IndexOf('\n', begin) + 1;
            string inDocument = doc.Substring(bodyStart, end - bodyStart);

            bool digestAgrees = string.Equals(stamped, now, StringComparison.Ordinal);
            bool textAgrees = string.Equals(Normalize(inDocument), Normalize(body), StringComparison.Ordinal);

            var sb = new StringBuilder();
            sb.Append("=== D18's inventory against the repo ===\n");
            sb.Append($"    document : {Document}\n");
            sb.Append($"    stamped  : {stamped}\n");
            sb.Append($"    rebuilt  : {now}\n");
            sb.Append($"    body     : {CountLines(body)} line(s) rebuilt, {CountLines(inDocument)} in the document\n");

            if (digestAgrees && textAgrees)
            {
                sb.Append("    the block in the ask IS what the checks print now.\n");
                Debug.Log(sb.ToString());
                Debug.Log("=== D18InventoryCheck: ALL ASSERTIONS PASS ===");
                CheckExit.Finish(0);
                return;
            }

            sb.Append("    ⚠ THE ASK IS STALE. The repo moved and the document did not - regenerate with Tools/d18_inventory.sh.\n");
            sb.Append(FirstDifference(Normalize(inDocument), Normalize(body)));
            Debug.LogError(sb.ToString());
            CheckExit.Finish(1);
        }

        // ------------------------------------------------------------------------------------------
        // The body
        // ------------------------------------------------------------------------------------------

        /// <summary>Builds the markdown body. <paramref name="fault"/> is non-null when something makes
        /// the inventory untrustworthy rather than merely empty - an enumeration that found nothing, a
        /// naming rule the delivered files refute, or two counts of one fact that disagree.</summary>
        public static string Build(out string fault)
        {
            fault = null;
            var faults = new List<string>();
            var sb = new StringBuilder();

            List<string> marks = Capture(PartyMarkCoverageCheck.Run, out int marksCode);
            List<string> portraits = Capture(PortraitCoverageCheck.Run, out int portraitsCode);
            List<string> statIcons = Capture(StatIconCoverageCheck.Run, out int statCode);
            List<string> areaIcons = Capture(AreaIconCoverageCheck.Run, out int areaCode);
            List<string> audio = Capture(AudioCueCoverageCheck.Run, out int audioCode);

            var families = new List<(string Name, List<string> Lines)>
            {
                ("PartyMarkCoverageCheck", marks), ("PortraitCoverageCheck", portraits),
                ("StatIconCoverageCheck", statIcons), ("AreaIconCoverageCheck", areaIcons),
                ("AudioCueCoverageCheck", audio),
            };

            foreach ((string name, List<string> lines) in families)
            {
                if (lines.Count == 0)
                {
                    faults.Add(name + " printed nothing - it was not captured, so this inventory verified "
                               + "nothing about its family");
                }
            }

            sb.Append("*Every figure in this section is EMITTED, never typed: `D18Inventory.Emit` runs the coverage\n");
            sb.Append("checks in-process and writes their own lines here. Regenerate with `Tools/d18_inventory.sh`.\n");
            sb.Append("`D18InventoryCheck` runs in the cheap bar and fails it when this block and the repo disagree,\n");
            sb.Append("so a figure here cannot go stale without the build going red.*\n\n");

            // ---- 1. party marks -------------------------------------------------------------------
            sb.Append("#### 1 · Party identity marks — `PartyMarkCoverageCheck`\n\n");
            sb.Append(Fenced(Interesting(marks)));

            int printedGaps = marks.Count(l => l.StartsWith("  no mark", StringComparison.Ordinal));
            int printedOk = marks.Count(l => l.StartsWith("  ok        PartySystems/", StringComparison.Ordinal));

            var byCountry = new List<(CountryId Id, int Seeded, int Resolving)>();
            var toCut = new List<(CountryId Id, string Abbrev, string Name, int Seats, string Stem)>();
            int seededTotal = 0, resolvingTotal = 0, ruleChecked = 0;
            var stems = new HashSet<string>(StringComparer.Ordinal);

            foreach (CountryId id in Enum.GetValues(typeof(CountryId)))
            {
                IReadOnlyList<PoliticalParty> parties = PartySystems.For(id);
                int resolving = 0;
                foreach (PoliticalParty party in parties)
                {
                    string stem = "mark_party_" + Iso2(id) + "_" + Slug(party.Abbrev);
                    if (!stems.Add(stem))
                    {
                        faults.Add($"two parties in {id} slug to one stem ({stem}) - the naming rule cannot name them both");
                    }

                    if (!string.IsNullOrEmpty(party.MarkName))
                    {
                        // ⚠ The rule is DERIVED here, not declared: every delivered mark must be the name
                        // the rule produces, or the rule is wrong and the stems below are unloadable.
                        ruleChecked++;
                        if (!string.Equals(party.MarkName, stem, StringComparison.Ordinal))
                        {
                            faults.Add($"the naming rule fails on a DELIVERED mark: {id} {party.Abbrev} is seeded as "
                                       + $"'{party.MarkName}' and the rule produces '{stem}'");
                        }

                        if (IconLibrary.GetPartyMark(party.MarkName) != null) { resolving++; }
                    }
                    else
                    {
                        toCut.Add((id, party.Abbrev, party.Name, party.SeedSeats, stem));
                    }
                }

                byCountry.Add((id, parties.Count, resolving));
                seededTotal += parties.Count;
                resolvingTotal += resolving;
            }

            if (toCut.Count != printedGaps)
            {
                faults.Add($"the per-country grouping counts {toCut.Count} parties without a mark and "
                           + $"PartyMarkCoverageCheck printed {printedGaps} - two enumerations of one fact disagree");
            }

            if (resolvingTotal != printedOk)
            {
                faults.Add($"the per-country grouping counts {resolvingTotal} resolving marks and the check printed {printedOk}");
            }

            if (ruleChecked == 0)
            {
                faults.Add("no delivered mark was available to check the naming rule against - the stems below are unverified");
            }

            sb.Append("\n**By chamber** (seeded parties, the marks that resolve, and what is left to cut; the rule\n");
            sb.Append($"`mark_party_<iso2>_<abbrev>` re-derived against all {ruleChecked} delivered marks on this run):\n\n");
            sb.Append("| country | chamber seats | parties seeded | marks resolving | to cut |\n|---|--:|--:|--:|--:|\n");
            foreach ((CountryId id, int seeded, int resolving) in byCountry)
            {
                sb.Append($"| {id} | {PartySystems.ChamberSeats(id)} | {seeded} | {resolving} | {seeded - resolving} |\n");
            }

            sb.Append($"| **total** | | **{seededTotal}** | **{resolvingTotal}** | **{seededTotal - resolvingTotal}** |\n");

            sb.Append("\n**The batch, party by party** — seats are the seed's own, so the largest are the ones a\n");
            sb.Append("chamber shows most; the stem is the file the game will load once the seed names it:\n\n");
            sb.Append("| country | abbrev | party | seats at seed | stem |\n|---|---|---|--:|---|\n");
            foreach ((CountryId id, string abbrev, string name, int seats, string stem) in
                     toCut.OrderBy(p => p.Id).ThenByDescending(p => p.Seats))
            {
                sb.Append($"| {id} | {abbrev} | {name} | {seats} | `{stem}` |\n");
            }

            // ---- 2. portraits ---------------------------------------------------------------------
            sb.Append("\n#### 2 · Portraits — `PortraitCoverageCheck`\n\n");
            sb.Append(Fenced(Interesting(portraits)));

            // ---- 3. stat icons --------------------------------------------------------------------
            sb.Append("\n#### 3 · Stat icons — `StatIconCoverageCheck`\n\n");
            sb.Append(Fenced(Interesting(statIcons)));

            // ---- 4. area icons --------------------------------------------------------------------
            sb.Append("\n#### 4 · Area icons — `AreaIconCoverageCheck`\n\n");
            sb.Append(Fenced(Interesting(areaIcons)));

            // ---- 5. audio -------------------------------------------------------------------------
            sb.Append("\n#### 5 · Audio cues — `AudioCueCoverageCheck`\n\n");
            sb.Append(Fenced(audio.Where(l => l.Length > 0 && !l.StartsWith("SELFTEST", StringComparison.Ordinal)).ToList()));

            // ---- 6. delivered and held ------------------------------------------------------------
            List<(string Stem, string Folder)> held = Held(out int delivered, out string censusFault);
            if (censusFault != null) { faults.Add(censusFault); }

            sb.Append("\n#### 6 · Delivered and held — nothing in `Assets/Scripts/` can load these\n\n");
            sb.Append($"*{delivered} sprite(s) under `Assets/Resources/Art/UI/`. A file counts as REACHED when an\n");
            sb.Append("accessor the game calls actually loads it on this run (the texture's own name is taken as the\n");
            sb.Append("key, so no naming rule is duplicated here), or when a source file names its stem as a whole\n");
            sb.Append("token. The rest are below: delivered work with no way in. **They are ours to wire, not\n");
            sb.Append("Design's to cut again.***\n\n");
            sb.Append("| stem | folder |\n|---|---|\n");
            foreach ((string stem, string folder) in held)
            {
                sb.Append($"| `{stem}` | {folder} |\n");
            }

            sb.Append($"\n{held.Count} held, {delivered - held.Count} reached.\n");

            // ---- the checks' own exit codes -------------------------------------------------------
            sb.Append("\n**The runs behind this block**: ");
            sb.Append(string.Join(" · ", new[]
            {
                $"PartyMark {marksCode}", $"Portrait {portraitsCode}", $"StatIcon {statCode}",
                $"AreaIcon {areaCode}", $"AudioCue {audioCode}",
            }));
            sb.Append(" — 0 is a clean check; a non-zero code means that family's own bar is red and this\n");
            sb.Append("inventory is describing a broken build.\n");

            if (faults.Count > 0) { fault = string.Join("; ", faults.ToArray()); }

            return sb.ToString();
        }

        // ------------------------------------------------------------------------------------------
        // Capture, census and helpers
        // ------------------------------------------------------------------------------------------

        /// <summary>Runs one check and returns every line it logged. ⚠ <see cref="CheckExit.Collect"/> is
        /// what keeps a check's `Finish` from ending the Editor, and it is nesting-safe precisely so this
        /// can call it from inside a check that is itself being collected.</summary>
        private static List<string> Capture(Action check, out int code)
        {
            var lines = new List<string>();
            Application.LogCallback handler = (condition, stack, type) =>
            {
                foreach (string part in condition.Replace("\r\n", "\n").Split('\n')) { lines.Add(part.TrimEnd()); }
            };

            Application.logMessageReceived += handler;
            try
            {
                code = CheckExit.Collect(check);
            }
            finally
            {
                Application.logMessageReceived -= handler;
            }

            return lines;
        }

        /// <summary>The lines worth putting in front of Design: every summary, and every row reporting
        /// something absent, shared, odd or exempt. The `ok` rows are the other nine tenths and say only
        /// that the delivered set is intact, which the summary line already says.</summary>
        private static List<string> Interesting(List<string> lines)
        {
            var keep = new List<string>();
            foreach (string line in lines)
            {
                if (line.Length == 0) { continue; }
                if (line.StartsWith("===", StringComparison.Ordinal)
                    || line.Contains("GAP") || line.Contains("MISSING") || line.Contains("no mark")
                    || line.Contains("sitting") || line.Contains("permanent") || line.Contains("awaiting")
                    || line.Contains("ODD SIZE") || line.Contains("SHARED") || line.Contains("DAMAGED")
                    || line.Contains("UNCONSUMED"))
                {
                    keep.Add(line);
                }
            }

            return keep;
        }

        /// <summary>Every delivered sprite nothing can reach. REACHED is proved by loading, not by a rule:
        /// each accessor the game calls is asked for every key the game can produce, and the texture that
        /// comes back names itself. What that cannot cover - a stem a draw call passes as a literal - is
        /// covered by a whole-token scan of the sources.</summary>
        private static List<(string Stem, string Folder)> Held(out int delivered, out string fault)
        {
            fault = null;
            delivered = 0;

            string root = Path.Combine(Directory.GetCurrentDirectory(),
                "Assets/Resources/Art/UI".Replace('/', Path.DirectorySeparatorChar));
            if (!Directory.Exists(root))
            {
                fault = "Assets/Resources/Art/UI is not on disk - the held census verified nothing";
                return new List<(string, string)>();
            }

            var reached = new HashSet<string>(StringComparer.Ordinal);
            void Take(Texture2D t)
            {
                if (t != null) { reached.Add(t.name); }
            }

            foreach (StatNodeId stat in Enum.GetValues(typeof(StatNodeId)))
            {
                Take(IconLibrary.GetStat(PolicyScreenStatsRenderer.GetIconName(stat)));
            }

            foreach (UiPalette.SystemArea area in Enum.GetValues(typeof(UiPalette.SystemArea)))
            {
                Take(IconLibrary.GetAreaIcon(area));
            }

            foreach (CountryId id in Enum.GetValues(typeof(CountryId)))
            {
                Take(IconLibrary.GetFlag(id));
                foreach (PoliticalParty party in PartySystems.For(id)) { Take(IconLibrary.GetPartyMark(party.MarkName)); }
            }

            var ministers = PortraitCoverageCheck.ReadPool<Dictionary<CabinetPortfolio, List<CabinetMinister>>>(
                typeof(CabinetSystem), "CandidatePool");
            var chairs = PortraitCoverageCheck.ReadPool<List<FedChair>>(typeof(FederalReserveSystem), "CandidatePool");
            if (ministers == null || chairs == null)
            {
                fault = "the cabinet or chair pool could not be read, so every portrait would read as held";
                return new List<(string, string)>();
            }

            foreach (KeyValuePair<CabinetPortfolio, List<CabinetMinister>> entry in ministers)
            {
                foreach (CabinetMinister minister in entry.Value)
                {
                    Take(IconLibrary.GetCabinetPortrait(minister.Portfolio, minister.Name));
                }
            }

            foreach (FedChair chair in chairs) { Take(IconLibrary.GetFedChairPortrait(chair.Name)); }

            string sources = ReadSources();
            var held = new List<(string, string)>();
            foreach (string file in Directory.GetFiles(root, "*.png", SearchOption.AllDirectories)
                         .OrderBy(p => p, StringComparer.Ordinal))
            {
                delivered++;
                string stem = Path.GetFileNameWithoutExtension(file);
                if (reached.Contains(stem) || NamesToken(sources, stem)) { continue; }

                held.Add((stem, Path.GetFileName(Path.GetDirectoryName(file))));
            }

            return held;
        }

        private static string ReadSources()
        {
            string scripts = Path.Combine(Directory.GetCurrentDirectory(), "Assets/Scripts".Replace('/', Path.DirectorySeparatorChar));
            if (!Directory.Exists(scripts)) { return string.Empty; }

            var sb = new StringBuilder();
            foreach (string file in Directory.GetFiles(scripts, "*.cs", SearchOption.AllDirectories))
            {
                // ⚠ COMMENTS STRIPPED, through the shared stripper `CommentImmunityCheck` enrols this file
                // for: a stem named only in a comment is NOT a call site, and counting one would report a
                // delivered sprite as reached on the strength of a sentence about it.
                sb.Append(SourceText.WithoutComments(File.ReadAllText(file))).Append('\n');
            }

            return sb.ToString();
        }

        /// <summary>⚠ Whole-token, because `ui_btn_paper_canvas` is a PREFIX of `ui_btn_paper_canvas_hover`:
        /// a plain Contains would report the shorter name as reached on the strength of the longer one's
        /// literal, which is the one direction of error a census like this must not make.</summary>
        private static bool NamesToken(string sources, string stem)
        {
            int at = 0;
            while ((at = sources.IndexOf(stem, at, StringComparison.Ordinal)) >= 0)
            {
                int after = at + stem.Length;
                bool trailing = after < sources.Length && (char.IsLetterOrDigit(sources[after]) || sources[after] == '_');
                if (!trailing) { return true; }

                at = after;
            }

            return false;
        }

        private static string Slug(string abbrev)
        {
            var sb = new StringBuilder();
            foreach (char c in abbrev ?? string.Empty)
            {
                if (char.IsLetterOrDigit(c)) { sb.Append(char.ToLowerInvariant(c)); }
            }

            return sb.ToString();
        }

        private static string Fenced(List<string> lines)
        {
            var sb = new StringBuilder("```\n");
            foreach (string line in lines) { sb.Append(line).Append('\n'); }

            return sb.Append("```\n").ToString();
        }

        private static int CountLines(string s) => string.IsNullOrEmpty(s) ? 0 : s.Split('\n').Length;

        private static string Normalize(string s) => s.Replace("\r\n", "\n").Trim('\n', ' ', '\t');

        private static string FirstDifference(string a, string b)
        {
            string[] left = a.Split('\n');
            string[] right = b.Split('\n');
            for (int i = 0; i < Math.Max(left.Length, right.Length); i++)
            {
                string l = i < left.Length ? left[i] : "(the document ends here)";
                string r = i < right.Length ? right[i] : "(the rebuild ends here)";
                if (!string.Equals(l, r, StringComparison.Ordinal))
                {
                    return $"    first difference at line {i + 1} of the block:\n      document: {l}\n      repo now: {r}\n";
                }
            }

            return "    the two agree line for line and the digests do not, which means the stamp was edited by hand.\n";
        }

        public static string Digest(string s)
        {
            using (SHA256 sha = SHA256.Create())
            {
                byte[] hash = sha.ComputeHash(new UTF8Encoding(false).GetBytes(s.Replace("\r\n", "\n")));
                var sb = new StringBuilder(hash.Length * 2);
                foreach (byte b in hash) { sb.Append(b.ToString("x2", CultureInfo.InvariantCulture)); }

                return sb.ToString();
            }
        }
    }
}
