using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using PoliSim.Data;
using PoliSim.Simulation;
using PoliSim.UI;
using UnityEngine;

namespace PoliSim.EditorTools
{
    /// <summary>
    /// **D24 item 4: the icon inventory at CATEGORY level, emitted from the catalogues and the icon loader** (UI v3.3; Design's
    /// `#d24-note`, 2026-09-26: "the icon inventory at category level ... a law's icon is a pair, an emblem and a verb side by side; a
    /// law that none of the four verbs describes gets no verb; a fifth verb, if the inventory shows one is needed, is a costed ask").
    ///
    /// <para>D18's lesson kept (`D18Inventory`): nothing here is typed from a reading of the code. Every row is the catalogue's own
    /// enumeration and every "held" is <see cref="IconLibrary"/> answering for the name the screens would load - so the send is the
    /// code, one step removed, and a stale sentence cannot enter it.</para>
    ///
    /// <para><b>The verb census is a PROPOSAL from signs, never a ruling.</b> A law is a preset over the dial space; where every dial
    /// it moves moves one way, the sign proposes RAISE or LOWER; where its dials move both ways, or it moves only structural
    /// parameters, the census says so and the verb is the owner's reading (BAN, ALLOW or none - the four verbs are Elias's).</para>
    ///
    /// <para>Run: `-executeMethod PoliSim.EditorTools.D24Inventory.Emit` - writes <see cref="BodyFile"/> and prints its digest.</para>
    /// </summary>
    public static class D24Inventory
    {
        /// <summary>Under `Logs/` (gitignored): the body travels in the Design package; the generator, not a copy, is the repo's.</summary>
        public const string BodyFile = "Logs/d24_inventory.md";

        public static void Emit()
        {
            string body = Build(out string fault);
            string path = Path.Combine(Directory.GetCurrentDirectory(), BodyFile.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, body, new UTF8Encoding(false));
            Debug.Log($"D24GEN: wrote {BodyFile} - {body.Length} chars, digest {Digest(body)}");
            if (fault != null)
            {
                Debug.LogError("D24GEN: " + fault);
                CheckExit.Finish(1);
                return;
            }
            CheckExit.Finish(0);
        }

        public static string Build(out string fault)
        {
            fault = null;
            var sb = new StringBuilder();
            sb.AppendLine("# D24 item 4 - the icon inventory at category level");
            sb.AppendLine();
            sb.AppendLine("GENERATED by `PoliSim.EditorTools.D24Inventory.Emit` from the catalogues and the icon loader; a row's HELD is the loader");
            sb.AppendLine("answering for the name the screens load. Nothing below is typed. NONE means no file is held under the name - a gap to");
            sb.AppendLine("cost, not an ask: per #d24-note, per-item icons only where the category cannot carry the item.");
            sb.AppendLine();

            // 1. The law categories: the emblem each category draws today (its area's icon), and the verb census.
            MethodInfo areaOf = typeof(GameController).GetMethod("LawCategoryArea", BindingFlags.Static | BindingFlags.NonPublic);
            if (areaOf == null) { fault = "GameController.LawCategoryArea is not reachable - the category's emblem cannot be named"; }
            sb.AppendLine("## 1. Law categories - the emblem half of the law's pair, and the verb census");
            sb.AppendLine();
            sb.AppendLine("| category | laws | emblem drawn today (its area) | held | all moves up | all moves down | both ways | of which structural | nothing moved |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|---|");
            int totalLaws = 0, up = 0, down = 0, mixed = 0, structural = 0, none = 0;
            foreach (LawCategory category in (LawCategory[])Enum.GetValues(typeof(LawCategory)))
            {
                int n = 0, u = 0, d = 0, m = 0, s = 0, z = 0;
                foreach (LawDefinition law in LawCatalog.All)
                {
                    if (law.Category != category) { continue; }
                    n++;
                    bool anyUp = false, anyDown = false;
                    foreach (float delta in law.DialDeltas) { if (delta > 0f) { anyUp = true; } else if (delta < 0f) { anyDown = true; } }
                    bool anyStructural = law.Structural != null && law.Structural.Length > 0;
                    if (anyStructural) { foreach (StructuralDelta sd in law.Structural) { if (sd.Delta > 0f) { anyUp = true; } else if (sd.Delta < 0f) { anyDown = true; } } s++; }
                    if (anyUp && anyDown) { m++; }
                    else if (anyUp) { u++; }
                    else if (anyDown) { d++; }
                    else { z++; }
                }
                UiPalette.SystemArea area = areaOf != null ? (UiPalette.SystemArea)areaOf.Invoke(null, new object[] { category }) : UiPalette.SystemArea.Neutral;
                string emblem = area == UiPalette.SystemArea.Neutral ? "(none - Neutral)" : "icon_area_" + area.ToString().ToLowerInvariant();
                bool held = area != UiPalette.SystemArea.Neutral && IconLibrary.GetAreaIcon(area) != null;
                sb.AppendLine($"| {category} | {n} | `{emblem}` | {(held ? "HELD" : "NONE")} | {u} | {d} | {m} | {s} | {z} |");
                totalLaws += n; up += u; down += d; mixed += m; structural += s; none += z;
            }
            sb.AppendLine($"| **all** | **{totalLaws}** | | | **{up}** | **{down}** | **{mixed}** | **{structural}** | **{none}** |");
            sb.AppendLine();
            sb.AppendLine("The census reads the signs of each law's dial deltas (`LawDefinition.DialDeltas`) and structural deltas (`LawDefinition.Structural`).");
            sb.AppendLine("ALL UP proposes RAISE and ALL DOWN proposes LOWER - proposals from signs; a structural parameter's sign is on its own scale, so a");
            sb.AppendLine("structural law's proposal is read against what its parameter means. BOTH WAYS is the owner's reading: BAN, ALLOW or no verb.");
            sb.AppendLine("A category shares an area's emblem where two categories draw one area; whether a category needs its own emblem is Design's call.");
            sb.AppendLine();

            // 2. The areas: every SystemArea's emblem.
            sb.AppendLine("## 2. Areas - the emblems the rail and the sub-tab rows draw");
            sb.AppendLine();
            sb.AppendLine("| area | file | held |");
            sb.AppendLine("|---|---|---|");
            foreach (UiPalette.SystemArea area in (UiPalette.SystemArea[])Enum.GetValues(typeof(UiPalette.SystemArea)))
            {
                if (area == UiPalette.SystemArea.Neutral) { continue; }
                sb.AppendLine($"| {area} | `icon_area_{area.ToString().ToLowerInvariant()}` | {(IconLibrary.GetAreaIcon(area) != null ? "HELD" : "NONE")} |");
            }
            sb.AppendLine();

            // 3. The stat nodes: the icon each one would load.
            sb.AppendLine("## 3. Stat nodes - the icon each stat row loads");
            sb.AppendLine();
            sb.AppendLine("| stat | file | held |");
            sb.AppendLine("|---|---|---|");
            int statsHeld = 0, statsAll = 0;
            foreach (StatNodeId stat in (StatNodeId[])Enum.GetValues(typeof(StatNodeId)))
            {
                string icon = PolicyScreenStatsRenderer.GetIconName(stat);
                bool held = !string.IsNullOrEmpty(icon) && IconLibrary.GetStat(icon) != null;
                statsAll++; if (held) { statsHeld++; }
                sb.AppendLine($"| {stat} | {(string.IsNullOrEmpty(icon) ? "(no name mapped)" : "`" + icon + "`")} | {(held ? "HELD" : "NONE")} |");
            }
            sb.AppendLine($"| **{statsAll} nodes** | | **{statsHeld} held** |");
            sb.AppendLine();

            // 4. The cabinet's portfolios: a category the Politics page and the formation sheet name by word today.
            sb.AppendLine("## 4. Cabinet portfolios - named by word today");
            sb.AppendLine();
            sb.AppendLine("| portfolio | short word the screens print | icon held |");
            sb.AppendLine("|---|---|---|");
            foreach (CabinetPortfolio portfolio in (CabinetPortfolio[])Enum.GetValues(typeof(CabinetPortfolio)))
            {
                string stem = "icon_portfolio_" + portfolio.ToString().ToLowerInvariant();
                sb.AppendLine($"| {portfolio} | {Effectiveness.ShortName(portfolio)} | {(IconLibrary.Get(stem) != null ? "HELD (`" + stem + "`)" : "NONE")} |");
            }
            sb.AppendLine();

            // 5. §662, Design's first ask of Code: the both-ways laws by name, one line each - read by LawVerbs, the one definition the rows draw by.
            string[] dials = new string[12];
            string[] cj = Enum.GetNames(typeof(CrimeJusticeDial)), lab = Enum.GetNames(typeof(LaborDial));
            Array.Copy(cj, 0, dials, 0, 6); Array.Copy(lab, 0, dials, 6, 6);   // LawDefinition.DialDeltas' contract: the six C&J dials, then the six labour dials
            sb.AppendLine("## 5. The laws that move dials both ways - one line each");
            sb.AppendLine();
            sb.AppendLine("category · id · the name the desk shows (the formal name) · what goes up · what goes down. Your rule applies to each: BAN if its net move is");
            sb.AppendLine("a prohibition, ALLOW if it permits what was not, no verb if it does both or neither. Until you read them, each shows no verb.");
            sb.AppendLine();
            int both = 0;
            foreach (LawDefinition law in LawCatalog.All)
            {
                if (!LawVerbs.IsBothWays(law)) { continue; }
                both++;
                var upList = new List<string>(); var downList = new List<string>();
                float[] deltas = law.DialDeltas;
                for (int i = 0; i < deltas.Length && i < dials.Length; i++) { if (deltas[i] > 0f) { upList.Add(dials[i]); } else if (deltas[i] < 0f) { downList.Add(dials[i]); } }
                if (law.Structural != null) { foreach (StructuralDelta s in law.Structural) { if (s.Delta > 0f) { upList.Add(s.Parameter.ToString()); } else if (s.Delta < 0f) { downList.Add(s.Parameter.ToString()); } } }
                sb.AppendLine($"{both}. {law.Category} · `{law.Id}` · {law.PlainName ?? law.Name} ({law.Name}) · up: {string.Join(", ", upList)} · down: {string.Join(", ", downList)}");
            }
            sb.AppendLine();
            sb.AppendLine($"**{both} laws.**");
            sb.AppendLine();

            return sb.ToString();
        }

        private static string Digest(string body)
        {
            using (var sha = SHA256.Create())
            {
                byte[] hash = sha.ComputeHash(new UTF8Encoding(false).GetBytes(body));
                return BitConverter.ToString(hash).Replace("-", string.Empty).ToLowerInvariant().Substring(0, 16);
            }
        }
    }
}
