using System;
using System.Globalization;
using System.IO;
using System.Text;
using PoliSim.Data;
using PoliSim.Data.Generated;
using UnityEditor;
using UnityEngine;
using Debug = UnityEngine.Debug;

namespace PoliSim.EditorTools
{
    /// <summary>
    /// Stage 2's only presentation (POLISIM_ENERGY_SPECLET.md S14): the physical layer, probed and written as `ENERGY_LAYER_PREMISE.md` -
    /// the `BudgetPremiseDump` pattern. Six fleets with the office of record's figure and Ember's side by side and the definition named,
    /// the capacity factors, the derived mix against the family's seed, the ten load folds, Sweden's zones with their apportioned fleet,
    /// the links with the flows the balances require in each block, and the single-book decomposition of the power figure per country.
    /// Generated, never typed; re-run the dump.
    ///
    /// Run: `Unity.exe -batchmode -nographics -projectPath &lt;path&gt; -executeMethod PoliSim.EditorTools.EnergyLayerDump.Run -logFile &lt;path&gt; [-energyout=&lt;file&gt;]`
    /// </summary>
    public static class EnergyLayerDump
    {
        [MenuItem("PoliSim/Dump Energy Layer Premise")]
        public static void Run()
        {
            CheckExit.ArmLogFold();
            string outPath = LeverProbes.Arg("-energyout=", Path.Combine(Application.dataPath, "..", "ENERGY_LAYER_PREMISE.md"));
            World world = WorldFactory.CreateDefault();
            var sb = new StringBuilder(1 << 16);
            sb.Append("# THE ENERGY LAYER'S PREMISE - the physical layer at its 2023 seed, probed\n\n");
            sb.Append($"GENERATED by `EnergyLayerDump` ({DateTime.Now:yyyy-MM-dd}), not transcribed. Every figure is read off `EnergyLayerData` (generated from `EnergyData/`, generated from the sources `ENERGY_LAYER_SPINE.md` lists by digest). Do not edit by hand; re-run the dump. **Stage 2 is readouts: the fleet and the load are static, the family's power figure keeps its own writer until stage 3's dispatch, and nothing here reaches the simulation.**\n\n");

            sb.Append("## 1. The fleet - the office of record's figure, Ember's beside it, the definition named\n\n");
            sb.Append("The record: Eurostat `nrg_inf_epc` net maximum capacity by main fuel group for five (coal = coal and manufactured gases; hydro includes pumped storage; solar AC; multi-fuel plants sit in other); EIA Table 4.3 net summer for the USA (hydro = conventional + pumped; solar includes small-scale). Ember's nameplate stands beside it. **Where they disagree the record carries the fleet and the row says DIVERGENT - a definition is chosen and named, never three figures averaged.**\n\n");
            foreach (Country c in world.Countries)
            {
                if (!EnergyLayer.Has(c.Id)) { continue; }
                if (c.Environment == null || !c.Environment.Seeded) { EnvironmentFamily.Seed(c); }
                sb.Append($"### {c.Id}\n\n| label | capacity MW (record) | capacity MW (Ember) | | generation GWh (record) | generation GWh (Ember) | capacity factor | derived share % | seed share % |\n|---|---|---|---|---|---|---|---|---|\n");
                float[] derived = EnergyLayer.DerivedMix(c.Id); float[] seed = c.Environment.MixShares;
                for (int l = 0; l < EnergyLayerData.Labels.Length; l++)
                {
                    double r = EnergyLayer.CapacityMw(c.Id, l), e = EnergyLayer.CapacityEmberMw(c.Id, l);
                    bool agree = Math.Abs(r - e) <= Math.Max(1000.0, 0.10 * Math.Max(r, e));
                    string closed = EnergyLayerCheck.ClosedByLawReason(c.Id, EnergyLayerData.Labels[l]);
                    string verdict = agree ? "agree" : (closed != null ? "**CLOSED BY LAW** - " + closed : "**DIVERGENT**");
                    sb.Append(F("| {0} | {1:N0} | {2:N0} | {3} | {4:N0} | {5:N0} | {6:0.00} | {7:0.0} | {8} |\n", EnergyLayerData.Labels[l], r, e, verdict, EnergyLayer.GenerationGwh(c.Id, l), EnergyLayer.GenerationEmberGwh(c.Id, l), EnergyLayer.Utilisation(c.Id, l), derived[l], seed == null ? "-" : seed[l].ToString("0.0", CultureInfo.InvariantCulture)));
                }
                sb.Append(F("\nTotal generation {0:N0} GWh; the derived mix departs from the family's static seed by at most **{1:0.0} points**.\n\n", EnergyLayer.TotalGenerationGwh(c.Id), seed == null ? 0f : EnergyLayer.MaxShareGap(derived, seed)));
            }

            sb.Append("## 2. The load, folded - the spec-let's three blocks and the peak (S3, the P90 cut)\n\n| zone | hours | energy GWh | base block (min MW × hours) | mid block h · MW | peak block h · MW | max MW | balance factor |\n|---|---|---|---|---|---|---|---|\n");
            for (int i = 0; i < EnergyLayer.ZoneCount; i++)
            {
                EnergyLayer.Blocks b = EnergyLayer.BlocksAt(i);
                sb.Append(F("| {0} | {1:N0} | {2:N1} | {3:N0} MW · {4:N1} GWh | {5:N0} · {6:N0} (+{7:N1} GWh) | {8:N0} · {9:N0} (+{10:N1} GWh) | {11:N0} | {12} |\n", b.Zone, b.Hours, b.EnergyGwh, b.MinMw, b.BaseGwh, b.MidHours, b.MidMeanMw, b.MidAboveBaseGwh, b.PeakHours, b.PeakMeanMw, b.PeakAboveBaseGwh, b.MaxMw, b.Scale < 1 ? F("{0:0.0000} (inland demand {1:N0} GWh)", b.Scale, b.InlandDemandGwh) : "1"));
            }
            sb.Append("\nThe three blocks sum to the series in every row (gate 2). Poland's series exceeds Eurostat's inland demand and carries the balance factor; the USA has no Eurostat balance and carries none; Sweden's four zones are settlement consumption and sum below the national load by the network's losses.\n\n");

            sb.Append("## 3. Sweden's zones - the apportioned fleet, the supply, the load, the links\n\n");
            sb.Append("The national fleet is apportioned to SE1..SE4 by each zone's 2023 share of eSett's production of the label's type (thermal carries coal, gas and other) - **an apportionment, stated: per-zone capacity is billed (ENTSO-E 14.1.A per bidding zone)**. Supply is the apportioned capacity at the national capacity factor, an annual average.\n\n| zone | consumption GWh | production GWh (eSett) | apportioned capacity MW: " + string.Join(" · ", EnergyLayerData.Labels) + " | average supply MW | peak level MW | base level MW |\n|---|---|---|---|---|---|---|\n");
            foreach (string z in EnergyLayer.SwedenZones)
            {
                var caps = new string[EnergyLayerData.Labels.Length];
                for (int l = 0; l < caps.Length; l++) { caps[l] = EnergyLayer.ZoneCapacityMw(z, l).ToString("N0", CultureInfo.InvariantCulture); }
                EnergyLayer.Blocks b = EnergyLayer.BlocksOf(z);
                sb.Append(F("| {0} | {1:N1} | {2:N1} | {3} | {4:N0} | {5:N0} | {6:N0} |\n", z, EnergyLayer.ZoneConsumptionGwh(z), EnergyLayer.ZoneProductionGwh(z), string.Join(" · ", caps), EnergyLayer.ZoneAverageSupplyMw(z), b.PeakMeanMw, b.MinMw));
            }
            sb.Append("\n| link | NTC 2021-2023 MW (the seed) | the map's maximum MW (the ceiling) |\n|---|---|---|\n");
            for (int i = 0; i < EnergyLayerData.LinkFrom.Length; i++) { sb.Append(F("| {0} → {1} | {2:N0} | {3:N0} |\n", EnergyLayerData.LinkFrom[i], EnergyLayerData.LinkTo[i], EnergyLayerData.LinkNtcMw[i], EnergyLayerData.LinkMapMaxMw[i])); }
            sb.Append("\n**The flows the zonal balances require, by block (MW, positive southward), against the NTC in the flow's direction:**\n\n| block | merged balance | SE1→SE2 | SE2→SE3 | SE3→SE4 |\n|---|---|---|---|---|\n");
            foreach (EnergyLayer.Block block in new[] { EnergyLayer.Block.Peak, EnergyLayer.Block.Mid, EnergyLayer.Block.Base })
            {
                EnergyLayer.LinkFlow[] flows = EnergyLayer.Flows(block, false);
                sb.Append(F("| {0} | {1:N0} |", block, EnergyLayer.MergedSurplusMw(block)));
                foreach (EnergyLayer.LinkFlow f in flows) { sb.Append(F(" {0:N0} / {1:N0} ({2:0}%){3} |", f.FlowMw, f.CapacityMw, 100 * f.Utilisation, f.Binding ? " **BINDS**" : "")); }
                sb.Append('\n');
            }
            sb.Append("\nWith the links infinite the four zones clear as one (the merged balance is the chain's end, asserted by `EnergyLayerCheck`). ⚠ These are balances on annual-average supply along a chain with ONE exit, SE4 - the interconnectors out of SE1, SE2 and SE3 to Norway, Finland and Denmark (spine §4) are outside it, so the base block's national surplus reads here as a flow through snitt 4 that in fact leaves north and west. Not a clearing: the north's hydro dispatched up in the peak, the south's imports from the continent, and SE4's price above SE1's are stage 3's.\n\n");

            sb.Append("## 4. The single book - the family's power figure decomposed, per country by method\n\n");
            sb.Append("The family's `PowerCo2PerCapita` is EDGAR's Power Industry per head (IPCC 1A1). Its DERIVED part is what the fleet itself burned for electricity - main-activity electricity-only plants plus the electricity share of main-activity CHP, at the IPCC 2006 default factors. The RESIDUAL is the seed minus that, by definition, so the identity holds at the seed; its known part is main-activity heat (heat-only plants and CHP's heat share) and the remainder is refineries, other energy industries and the gap between EDGAR's country factors and the defaults - **printed with its sign, never hidden.** Autoproducers' combustion is shown and is industry's book.\n\n| country | seed t/head | population M | seed kt | derived kt | derived % | residual kt | of which known heat | remainder | autoproducers kt | derived by label: coal · gas · other |\n|---|---|---|---|---|---|---|---|---|---|---|\n");
            foreach (Country c in world.Countries)
            {
                if (!EnergyLayer.Has(c.Id)) { continue; }
                EnergyLayer.Co2 d = EnergyLayer.Decomposition(c.Id, c.Environment.PowerCo2PerCapita);
                sb.Append(F("| {0} | {1:0.00} | {2:0.00} | {3:N0} | {4:N0} | {5:0.0} | {6:N0} | {7:N0} | {8:N0} | {9:N0} | {10:N0} · {11:N0} · {12:N0} |\n", c.Id, c.Environment.PowerCo2PerCapita, EnergyLayer.PopulationM(c.Id), d.SeedTotalKt, d.DerivedKt, 100 * d.DerivedShare, d.ResidualKt, d.MainHeatKt, d.RemainderKt, d.AutoproducerKt,
                    EnergyLayer.DerivedKtByLabel(c.Id, 0), EnergyLayer.DerivedKtByLabel(c.Id, 1), EnergyLayer.DerivedKtByLabel(c.Id, 2)));
            }
            sb.Append("\n## 5. What this layer does not do yet\n\nNo dispatch (stage 3), so no price, no scarcity, no import bill; the fleet does not invest or retire; the load does not grow; the carbon tax reaches the power figure through the family's own elasticity, as before, until the merit order exists to replace it. The Environment plate's foot prints the derived share so the single book is visible where the figure is; the energy screen is stage 6's.\n");

            File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(false));
            Debug.Log($"ENERGY: wrote {Path.GetFullPath(outPath)}.");
            CheckExit.Finish(0);
        }

        private static string F(string format, params object[] args) => string.Format(CultureInfo.InvariantCulture, format, args);
    }
}
