using System;
using System.Globalization;
using System.IO;
using System.Text;
using PoliSim.Data;
using PoliSim.Data.Generated;
using UnityEditor;
using UnityEngine;
using Debug = UnityEngine.Debug;

namespace PoliSim.EditorTools
{
    /// <summary>
    /// Stage 2's only presentation (POLISIM_ENERGY_SPECLET.md S14): the physical layer, probed and written as `ENERGY_LAYER_PREMISE.md` -
    /// the `BudgetPremiseDump` pattern. Six fleets with the office of record's figure and Ember's side by side and the definition named,
    /// the capacity factors, the derived mix against the family's seed, the ten load folds, Sweden's zones with their apportioned fleet,
    /// the links with the flows the balances require in each block, and the single-book decomposition of the power figure per country.
    /// Generated, never typed; re-run the dump.
    ///
    /// Run: `Unity.exe -batchmode -nographics -projectPath &lt;path&gt; -executeMethod PoliSim.EditorTools.EnergyLayerDump.Run -logFile &lt;path&gt; [-energyout=&lt;file&gt;]`
    /// </summary>
    public static class EnergyLayerDump
    {
        [MenuItem("PoliSim/Dump Energy Layer Premise")]
        public static void Run()
        {
            CheckExit.ArmLogFold();
            string outPath = LeverProbes.Arg("-energyout=", Path.Combine(Application.dataPath, "..", "ENERGY_LAYER_PREMISE.md"));
            World world = WorldFactory.CreateDefault();
            var sb = new StringBuilder(1 << 16);
            sb.Append("# THE ENERGY LAYER'S PREMISE - the physical layer at its 2023 seed, probed\n\n");
            sb.Append($"GENERATED by `EnergyLayerDump` ({DateTime.Now:yyyy-MM-dd}), not transcribed. Every figure is read off `EnergyLayerData` (generated from `EnergyData/`, generated from the sources `ENERGY_LAYER_SPINE.md` lists by digest). Do not edit by hand; re-run the dump. **Stage 2 is readouts: the fleet and the load are static, the family's power figure keeps its own writer until stage 3's dispatch, and nothing here reaches the simulation.**\n\n");

            sb.Append("## 1. The fleet - the office of record's figure, Ember's beside it, the definition named\n\n");
            sb.Append("The record: Eurostat `nrg_inf_epc` net maximum capacity by main fuel group for five (coal = coal and manufactured gases; hydro includes pumped storage; solar AC; multi-fuel plants sit in other); EIA Table 4.3 net summer for the USA (hydro = conventional + pumped; solar includes small-scale). Ember's nameplate stands beside it. **Where they disagree the record carries the fleet and the row says DIVERGENT - a definition is chosen and named, never three figures averaged.**\n\n");
            foreach (Country c in world.Countries)
            {
                if (!EnergyLayer.Has(c.Id)) { continue; }
                if (c.Environment == null || !c.Environment.Seeded) { EnvironmentFamily.Seed(c); }
                sb.Append($"### {c.Id}\n\n| label | capacity MW (record) | capacity MW (Ember) | | generation GWh (record) | generation GWh (Ember) | capacity factor | derived share % | seed share % |\n|---|---|---|---|---|---|---|---|---|\n");
                float[] derived = EnergyLayer.DerivedMix(c.Id); float[] seed = c.Environment.MixShares;
                for (int l = 0; l < EnergyLayerData.Labels.Length; l++)
                {
                    double r = EnergyLayer.CapacityMw(c.Id, l), e = EnergyLayer.CapacityEmberMw(c.Id, l);
                    bool agree = Math.Abs(r - e) <= Math.Max(1000.0, 0.10 * Math.Max(r, e));
                    string closed = EnergyLayerCheck.ClosedByLawReason(c.Id, EnergyLayerData.Labels[l]);
                    string verdict = agree ? "agree" : (closed != null ? "**CLOSED BY LAW** - " + closed : "**DIVERGENT**");
                    sb.Append(F("| {0} | {1:N0} | {2:N0} | {3} | {4:N0} | {5:N0} | {6:0.00} | {7:0.0} | {8} |\n", EnergyLayerData.Labels[l], r, e, verdict, EnergyLayer.GenerationGwh(c.Id, l), EnergyLayer.GenerationEmberGwh(c.Id, l), EnergyLayer.Utilisation(c.Id, l), derived[l], seed == null ? "-" : seed[l].ToString("0.0", CultureInfo.InvariantCulture)));
                }
                sb.Append(F("\nTotal generation {0:N0} GWh; the derived mix departs from the family's static seed by at most **{1:0.0} points**.\n\n", EnergyLayer.TotalGenerationGwh(c.Id), seed == null ? 0f : EnergyLayer.MaxShareGap(derived, seed)));
            }

            sb.Append("## 2. The load, folded - the spec-let's three blocks and the peak (S3, the P90 cut)\n\n| zone | hours | energy GWh | base block (min MW × hours) | mid block h · MW | peak block h · MW | max MW | balance factor |\n|---|---|---|---|---|---|---|---|\n");
            for (int i = 0; i < EnergyLayer.ZoneCount; i++)
            {
                EnergyLayer.Blocks b = EnergyLayer.BlocksAt(i);
                sb.Append(F("| {0} | {1:N0} | {2:N1} | {3:N0} MW · {4:N1} GWh | {5:N0} · {6:N0} (+{7:N1} GWh) | {8:N0} · {9:N0} (+{10:N1} GWh) | {11:N0} | {12} |\n", b.Zone, b.Hours, b.EnergyGwh, b.MinMw, b.BaseGwh, b.MidHours, b.MidMeanMw, b.MidAboveBaseGwh, b.PeakHours, b.PeakMeanMw, b.PeakAboveBaseGwh, b.MaxMw, b.Scale < 1 ? F("{0:0.0000} (inland demand {1:N0} GWh)", b.Scale, b.InlandDemandGwh) : "1"));
            }
            sb.Append("\nThe three blocks sum to the series in every row (gate 2). Poland's series exceeds Eurostat's inland demand and carries the balance factor; the USA has no Eurostat balance and carries none; Sweden's four zones are settlement consumption and sum below the national load by the network's losses.\n\n");

            sb.Append("## 3. Sweden's zones - the apportioned fleet, the supply, the load, the links\n\n");
            sb.Append("The national fleet is apportioned to SE1..SE4 by each zone's 2023 share of eSett's production of the label's type (thermal carries coal, gas and other) - **an apportionment, stated: per-zone capacity is billed (ENTSO-E 14.1.A per bidding zone)**. Supply is the apportioned capacity at the national capacity factor, an annual average.\n\n| zone | consumption GWh | production GWh (eSett) | apportioned capacity MW: " + string.Join(" · ", EnergyLayerData.Labels) + " | average supply MW | peak level MW | base level MW |\n|---|---|---|---|---|---|---|\n");
            foreach (string z in EnergyLayer.SwedenZones)
            {
                var caps = new string[EnergyLayerData.Labels.Length];
                for (int l = 0; l < caps.Length; l++) { caps[l] = EnergyLayer.ZoneCapacityMw(z, l).ToString("N0", CultureInfo.InvariantCulture); }
                EnergyLayer.Blocks b = EnergyLayer.BlocksOf(z);
                sb.Append(F("| {0} | {1:N1} | {2:N1} | {3} | {4:N0} | {5:N0} | {6:N0} |\n", z, EnergyLayer.ZoneConsumptionGwh(z), EnergyLayer.ZoneProductionGwh(z), string.Join(" · ", caps), EnergyLayer.ZoneAverageSupplyMw(z), b.PeakMeanMw, b.MinMw));
            }
            sb.Append("\n| link | NTC 2021-2023 MW (the seed) | the map's maximum MW (the ceiling) |\n|---|---|---|\n");
            for (int i = 0; i < EnergyLayerData.LinkFrom.Length; i++) { sb.Append(F("| {0} → {1} | {2:N0} | {3:N0} |\n", EnergyLayerData.LinkFrom[i], EnergyLayerData.LinkTo[i], EnergyLayerData.LinkNtcMw[i], EnergyLayerData.LinkMapMaxMw[i])); }
            sb.Append("\n**The flows the zonal balances require, by block (MW, positive southward), against the NTC in the flow's direction:**\n\n| block | merged balance | SE1→SE2 | SE2→SE3 | SE3→SE4 |\n|---|---|---|---|---|\n");
            foreach (EnergyLayer.Block block in new[] { EnergyLayer.Block.Peak, EnergyLayer.Block.Mid, EnergyLayer.Block.Base })
            {
                EnergyLayer.LinkFlow[] flows = EnergyLayer.Flows(block, false);
                sb.Append(F("| {0} | {1:N0} |", block, EnergyLayer.MergedSurplusMw(block)));
                foreach (EnergyLayer.LinkFlow f in flows) { sb.Append(F(" {0:N0} / {1:N0} ({2:0}%){3} |", f.FlowMw, f.CapacityMw, 100 * f.Utilisation, f.Binding ? " **BINDS**" : "")); }
                sb.Append('\n');
            }
            sb.Append("\nWith the links infinite the four zones clear as one (the merged balance is the chain's end, asserted by `EnergyLayerCheck`). ⚠ These are balances on annual-average supply along a chain with ONE exit, SE4 - the interconnectors out of SE1, SE2 and SE3 to Norway, Finland and Denmark (spine §4) are outside it, so the base block's national surplus reads here as a flow through snitt 4 that in fact leaves north and west. Not a clearing: the north's hydro dispatched up in the peak, the south's imports from the continent, and SE4's price above SE1's are stage 3's.\n\n");

            sb.Append("## 4. The single book - the family's power figure decomposed, per country by method\n\n");
            sb.Append("The family's `PowerCo2PerCapita` is EDGAR's Power Industry per head (IPCC 1A1). Its DERIVED part is what the fleet itself burned for electricity - main-activity electricity-only plants plus the electricity share of main-activity CHP, at the IPCC 2006 default factors. The RESIDUAL is the seed minus that, by definition, so the identity holds at the seed; its known part is main-activity heat (heat-only plants and CHP's heat share) and the remainder is refineries, other energy industries and the gap between EDGAR's country factors and the defaults - **printed with its sign, never hidden.** Autoproducers' combustion is shown and is industry's book.\n\n| country | seed t/head | population M | seed kt | derived kt | derived % | residual kt | of which known heat | remainder | autoproducers kt | derived by label: coal · gas · other |\n|---|---|---|---|---|---|---|---|---|---|---|\n");
            foreach (Country c in world.Countries)
            {
                if (!EnergyLayer.Has(c.Id)) { continue; }
                EnergyLayer.Co2 d = EnergyLayer.Decomposition(c.Id, c.Environment.PowerCo2PerCapita);
                sb.Append(F("| {0} | {1:0.00} | {2:0.00} | {3:N0} | {4:N0} | {5:0.0} | {6:N0} | {7:N0} | {8:N0} | {9:N0} | {10:N0} · {11:N0} · {12:N0} |\n", c.Id, c.Environment.PowerCo2PerCapita, EnergyLayer.PopulationM(c.Id), d.SeedTotalKt, d.DerivedKt, 100 * d.DerivedShare, d.ResidualKt, d.MainHeatKt, d.RemainderKt, d.AutoproducerKt,
                    EnergyLayer.DerivedKtByLabel(c.Id, 0), EnergyLayer.DerivedKtByLabel(c.Id, 1), EnergyLayer.DerivedKtByLabel(c.Id, 2)));
            }
            // ---- EN-3 (2026-09-11): the market layer at the seed
            sb.Append("\n## 5. The market at the seed (EN-3) - one clearing per block per zone\n\n");
            sb.Append("The clearing's blocks are hours: the trough decile (base), the middle eight (mid), the top decile (peak) of the load. The merit order runs over fuel ÷ efficiency + O&M, carried by the price level, plus the ETS price × the emission factor (the national carbon tax does not reach the fleet - EN-4d, §467: ETS-covered plant is exempt of it by statute, applied here at sector level for want of an installation register), plus the seed's CALIBRATION ADDER - solved once so the seed dispatch reproduces 2023's coal / gas / oil shares of the fossil total (the shadow of what three blocks do not see: must-run contracts, heat-led CHP, ramping, location) and printed here. Germany's reactors dispatch at zero (CLOSED BY LAW). The price is the marginal unit's cost, lifted by the scarcity term above " + PoliSim.Simulation.EnergyMarket.ScarcityOnset.ToString("0.00", CultureInfo.InvariantCulture) + " of the dependable capacity toward the ceiling of " + PoliSim.Simulation.EnergyMarket.MaxClearingPrice.ToString("N0", CultureInfo.InvariantCulture) + " (ACER's harmonised maximum); nothing is clamped, and the lowest offer on every curve is " + PoliSim.Simulation.EnergyMarket.CurtailmentOffer.ToString("0", CultureInfo.InvariantCulture) + " until a support scheme bids below it.\n\n");
            sb.Append("| country | block | hours | demand MW | must-run MW | residual MW | coal · gas · oil MW | marginal cost coal · gas · oil | price | scarcity | curtailed | unserved |\n|---|---|---|---|---|---|---|---|---|---|---|---|\n");
            PoliSim.Simulation.EnergyMarket.ResetCalibration();
            PoliSim.Simulation.EnergyMarket.BeginTurn(world);
            foreach (Country c in world.Countries)
            {
                if (!EnergyLayer.Has(c.Id) || c.Id == CountryId.Sweden) { continue; }
                PoliSim.Simulation.EnergyMarket.Result r = PoliSim.Simulation.EnergyMarket.Clear(c);
                int zone = EnergyLayer.ZoneIndex(EnergyLayer.Code(c.Id));
                for (int b = 0; b < 3; b++)
                {
                    PoliSim.Simulation.EnergyMarket.BlockResult br = r.Zones[0][b];
                    sb.Append(F("| {0} | {1} | {2:N0} | {3:N0} | {4:N0} | {5:N0} | {6:N0} · {7:N0} · {8:N0} | {9:F1} · {10:F1} · {11} | **{12:F1}** | {13:F1} | {14:N0} | {15:N0} |\n", c.Id, EnergyLayerData.DispatchBlocks[b], EnergyLayerData.DispatchHours[zone][b], br.DemandMw, br.MustRunMw, br.ResidualMw, br.FossilMw[0], br.FossilMw[1], br.FossilMw[2], br.MarginalCost[0], br.MarginalCost[1], double.IsInfinity(br.MarginalCost[2]) ? "-" : br.MarginalCost[2].ToString("F1", CultureInfo.InvariantCulture), br.Price, br.Scarcity, br.CurtailedMw, br.UnservedMw));
                }
                double fossil = r.AnnualGwh[0] + r.AnnualGwh[1] + r.AnnualGwh[2]; double[] target = PoliSim.Simulation.EnergyMarket.SeedTargets(c.Id);
                sb.Append(F("| | **{0} year** | | | | | fossil shares {1:F3} · {2:F3} · {3:F3} (2023: {4:F3} · {5:F3} · {6:F3}) | adders {7:F1} · {8:F1} · {9:F1} | | | derived CO₂ {10:F1} Mt + residual {11:F1} = {12:F3} t/head | |\n", c.Id, fossil > 0 ? r.AnnualGwh[0] / fossil : 0, fossil > 0 ? r.AnnualGwh[1] / fossil : 0, fossil > 0 ? r.AnnualGwh[2] / fossil : 0, target[0], target[1], target[2], r.Adders[0], r.Adders[1], r.Adders[2], r.DerivedCo2Mt, c.Environment.PowerResidualMt, (r.DerivedCo2Mt + c.Environment.PowerResidualMt) / Math.Max(0.0001f, c.State.Population)));
            }
            Country sweden = world.GetCountry(CountryId.Sweden);
            PoliSim.Simulation.EnergyMarket.Result rse = PoliSim.Simulation.EnergyMarket.Clear(sweden);
            sb.Append("\n**Sweden's four zones, on coincident hours, against the dated NTCs** - each zone's balance is its settlement consumption plus its exogenous external export (energy-charts' exchange by neighbour, apportioned by the interconnectors) less its own supply; the water value is Germany's and Poland's block price weighted by SE4's capacity to each; a link that cannot carry the required flow BINDS and splits the price.\n\n| block | water value | SE1 balance MW | SE2 | SE3 | SE4 | snitt 1 flow / NTC | snitt 2 | snitt 4 | prices SE1 · SE2 · SE3 · SE4 |\n|---|---|---|---|---|---|---|---|---|---|\n");
            for (int b = 0; b < 3; b++)
            {
                sb.Append(F("| {0} | {1:F1} | {2:N0} | {3:N0} | {4:N0} | {5:N0} |", EnergyLayerData.DispatchBlocks[b], rse.WaterValue[b], rse.Zones[0][b].MustRunMw - rse.Zones[0][b].DemandMw, rse.Zones[1][b].MustRunMw - rse.Zones[1][b].DemandMw, rse.Zones[2][b].MustRunMw - rse.Zones[2][b].DemandMw, rse.Zones[3][b].MustRunMw - rse.Zones[3][b].DemandMw));
                foreach (PoliSim.Simulation.EnergyMarket.LinkResult l in rse.Links) { sb.Append(F(" {0:N0} / {1:N0} ({2:F0} %){3} |", l.FlowMw[b], l.CapacityMw[b], 100 * Math.Abs(l.FlowMw[b]) / l.CapacityMw[b], l.Binding[b] ? " **BINDS**" : "")); }
                sb.Append(F(" {0:F1} · {1:F1} · {2:F1} · {3:F1} |\n", rse.Zones[0][b].Price, rse.Zones[1][b].Price, rse.Zones[2][b].Price, rse.Zones[3][b].Price));
            }
            int se4z = EnergyLayer.ZoneIndex("SE4");
            sb.Append("\n**Snitt 4's answer.** ");
            for (int b = 0; b < 3; b++) { sb.Append(F("{0}: {1:N0} MW of {2:N0} = SE4's own deficit {3:N0} + transit to the continent {4:N0} (the chain's unbalance {5:N0} MW, losses and rounding, never priced) - {6}. ", EnergyLayerData.DispatchBlocks[b], rse.Links[2].FlowMw[b], rse.Links[2].CapacityMw[b], EnergyLayerData.ZoneConsumptionBlockMw[se4z][b] - rse.Zones[3][b].MustRunMw, EnergyLayerData.ZoneExternalExportMw[se4z][b], rse.ChainUnbalanceMw[b], rse.Links[2].Binding[b] ? "CONGESTION on the block average" : "EXPORT, not congestion, on the block average")); }
            sb.Append("The §457 proxy read 10 785 MW through snitt 4 in the base block because its chain had one exit; the exchange with Norway, Finland and Denmark out of SE1–SE3 is in the balances now, and what crosses snitt 4 is SE4's own deficit plus the transit to Denmark, Germany, Poland and Lithuania. Hourly congestion is not claimed by a block average.\n");
            // ---- EN-3b (2026-09-11): the reservoir dispatch
            sb.Append("\n**The reservoir dispatch (EN-3b).** Each zone's uncongested price is its own 2023 day-ahead price on the exchange, folded onto the model's blocks (energy-charts.info's republication of Nord Pool's series; the seed carries three block means per zone), carried by the price level and coupled to the continental proxy above by the zone's measured share of its moves; the proxy itself - what EN-3 cleared every zone at - stands in the table's water-value column as the measure of what it cost.\n\n| zone | seed price base · mid · peak €/MWh | load-weighted | coupling to the continent (β, DERIVED) | reservoir capacity GWh (Energiföretagen) |\n|---|---|---|---|---|\n");
            foreach (string z in EnergyLayer.SwedenZones) { int hz = EnergyLayer.HydroZoneIndex(z); sb.Append(F("| {0} | {1:F1} · {2:F1} · {3:F1} | {4:F1} | {5:F2} | {6:N0} |\n", z, EnergyLayerData.HydroPriceBlock[hz][0], EnergyLayerData.HydroPriceBlock[hz][1], EnergyLayerData.HydroPriceBlock[hz][2], EnergyLayerData.HydroPriceLoadWeighted[hz], EnergyLayerData.HydroBetaToProxy[hz], EnergyLayerData.ReservoirCapacityGwh[hz])); }
            { int de = EnergyLayer.HydroZoneIndex("DE"), pl = EnergyLayer.HydroZoneIndex("PL"); sb.Append(F("\nThe exchange's own 2023 blocks for the two markets the proxy is made of - Germany {0:F1} · {1:F1} · {2:F1} (load-weighted {3:F1}), Poland {4:F1} · {5:F1} · {6:F1} ({7:F1}) - against the market's seed prices above: the adders calibrate the fossil shares, not the prices, and the peak blocks run low (EN-3c, evidence). Sweden's reservoirs together {8:N0} GWh; the balance against the seed's cycle is carried on the state and a deficit raises the water value at the slope `EnergyMarket.ReservoirDeficitSlope` (authored; the piece a fill-and-price record replaces). The shiftable hydro of the fossil countries (Italy {9:F3}, Germany {10:F3} of the year's hydro; France, Poland and the USA BILLED) moves between the base and the peak block when a policy moves the peak–base spread off the seed's, and not before.\n", EnergyLayerData.HydroPriceBlock[de][0], EnergyLayerData.HydroPriceBlock[de][1], EnergyLayerData.HydroPriceBlock[de][2], EnergyLayerData.HydroPriceLoadWeighted[de], EnergyLayerData.HydroPriceBlock[pl][0], EnergyLayerData.HydroPriceBlock[pl][1], EnergyLayerData.HydroPriceBlock[pl][2], EnergyLayerData.HydroPriceLoadWeighted[pl], EnergyLayer.SwedenReservoirCapacityGwh(), EnergyLayer.HydroShiftableShare(CountryId.Italy), EnergyLayer.HydroShiftableShare(CountryId.Germany))); }

            // ---- EN-4 (2026-09-11): the fiscal layer at the seed
            sb.Append("\n## 6. The fiscal layer at the seed - the retail stack per class and the two ledgers (EN-4)\n\nThe stack per kWh in THE BOOK'S DOLLARS (the game keeps every country's book in US dollars; Eurostat's euro rows reach it at the ECB 2023 rate 1.0813 USD/EUR, and the stated total is printed beside in the source's own currency): the wholesale is the seed dispatch load-weighted over the blocks (Sweden: over the zones at the seed's water value); the SUPPLY MARGIN is FITTED - Eurostat's energy-and-supply component less that wholesale - and is printed with its sign; network, levies and environmental tax are Eurostat's 2023 components (`nrg_pc_204`/`nrg_pc_205`, bands DC/IC; the USA EIA's averages, components BILLED); VAT is the rate the components imply. Non-households bear the pre-VAT price. The budget-financed support is the book's energy spending line; the bill-financed support is the levy; Germany's book carries no energy line (the KTF is outside the Bundeshaushalt).\n\n");
            foreach (Country c in world.Countries)
            {
                if (!EnergyLayer.Has(c.Id)) { continue; }
                int ci = EnergyLayer.Index(c.Id);
                PoliSim.Simulation.EnergyMarket.Result r0 = PoliSim.Simulation.EnergyMarket.ClearAtSeed(c.Id);
                PoliSim.Simulation.EnergyLedger.Book book = PoliSim.Simulation.EnergyLedger.Compute(c, r0, 1.0, 0.0);
                string sourceCurrency = c.Id == CountryId.USA ? "USD" : "EUR";
                sb.Append(F("### {0} ({1} per kWh, the book's dollars; bills in billions of dollars; the country's own currency is {2})\n\n| class | consumption GWh | wholesale | supply margin (FITTED) | network | policy levies | environmental tax | VAT (implied rate) | total (the components' sum) | Eurostat's stated total ({3}) | bill |\n|---|---|---|---|---|---|---|---|---|---|---|\n", c.Id, PoliSim.Simulation.EnergyLedger.BookCurrency, PoliSim.Simulation.EnergyLedger.NationalCurrencyCode(c.Id), sourceCurrency));
                for (int k = 0; k < PoliSim.Simulation.EnergyLedger.ClassCount; k++)
                {
                    PoliSim.Simulation.EnergyLedger.ClassStack st = book.Classes[k];
                    sb.Append(F("| {0} | {1:N0} | {2:F4} | {3:+0.0000;-0.0000} | {4:F4} | {5:F4} | {6:F4} | {7:F4} ({8:F1} %) | **{9:F4}** | {10:F4} | {11:F2}{12} |\n", st.Class, st.ConsumptionGwh, st.Wholesale, st.Margin, st.Network, st.Policy, st.TaxEnv, st.Vat, 100 * c.Environment.RetailVatRate[k], st.Total, EnergyLayerData.RetailTotal[ci][k], st.Bill, k == PoliSim.Simulation.EnergyLedger.NonHouseholds ? " (pre-VAT)" : ""));
                }
                sb.Append(F("\n**System cost, as far as the model states it (bn):** fossil variable cost {0:F2} = fuel and O&M {1:F2} + ETS {2:F2} (the fleet's one carbon price - the national carbon tax does not reach ETS-covered plant, EN-4d) + fitted adders {3:F2}; wholesale outlay {4:F2}, of which {5:F2} above the fossil variable cost pays the fleet's fixed costs and the non-fossil fleet (not modelled); network revenue {6:F2}; support {7:F2} = levy {8:F2} + budget line {9:F2}.\n\n",
                    book.FossilVariableCost, book.FuelVomCost, book.EtsCost, book.AdderCost, book.WholesaleOutlay, book.InframarginalRent, book.NetworkRevenue, book.SupportCost, book.LevyRevenue, book.BudgetSupport));
                sb.Append(F("**Incidence (bn):** paid - households {0:F2}, non-households {1:F2}, taxpayers {2:F2} = {3:F2}; received - generators {4:F2}, suppliers {5:F2}, networks {6:F2}, the support scheme {7:F2}, the state's electricity taxes {8:F2} = {9:F2}; gap {10:E1}. The state's net {11:F2}. Congestion rent {12:F3}.\n\n",
                    book.PaidHouseholds, book.PaidNonHouseholds, book.PaidTaxpayers, book.PaidTotal, book.ToGenerators, book.ToSuppliers, book.ToNetworks, book.ToSupport, book.ToStateTaxes, book.ReceivedTotal, book.Gap, book.StateNet, book.CongestionRent));
            }

            // ---- EN-5 (2026-09-11): the pass-through's weight
            sb.Append("\n**The pass-through to inflation (EN-5).** Electricity's weight in the consumer price index, per mille of the all-items basket, 2023 (Eurostat `prc_hicp_inw` CP0451 for the five; the BLS CPI-U relative importance, December 2023, for the USA): ");
            foreach (Country c in world.Countries) { if (EnergyLayer.Has(c.Id)) { sb.Append(F("{0} {1:F2} · ", c.Id, PoliSim.Simulation.EnergyPassThrough.WeightFraction(c.Id) * PoliSim.Simulation.EnergyPassThrough.PerMille)); } }
            sb.Append("the household price's change relative to the general price level, times this weight, is the year's pass-through in inflation points - a price-level term the expectations step looks through (`EnergyPassThrough`). Sweden's weight is two and a half times Germany's, and part of that is 2022: the 2023 weights rest on the spike year's expenditure.\n");

            sb.Append("\n## 7. What this layer does not do yet\n\nThe fleet does not invest or retire; the load does not grow (so the bills' share of a growing GDP drifts down - the missing load growth, stated); the reservoirs' seed fill and the water value's answer to a deficit have no source yet (the slope is authored and armed by probe; a dry year is stage 8's event); the neighbours outside the six are an exogenous exchange; the energy screen is a later stage's. The carbon tax reaches transport's tonnes and nothing in this layer (EN-4d, §467: ETS-covered plant is exempt of the national carbon tax by statute so the two prices do not stack, applied here at sector level for want of an installation register - the deviation, stated in EnergyMarket's class doc); since EN-4c its rate has one meaning - the country's currency per tonne of CO₂, the statutory figure at the seed. The fleet's carbon price is the ETS, exogenous - the 2023 mean carried by the price level, stepped only by a probe - until a stage gives it a path. Sweden's statutory indexation of its rate (2 kap. 1 b §) is not carried - a known divergence, its own row (EN-4e).\n");

            File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(false));
            Debug.Log($"ENERGY: wrote {Path.GetFullPath(outPath)}.");
            CheckExit.Finish(0);
        }

        private static string F(string format, params object[] args) => string.Format(CultureInfo.InvariantCulture, format, args);
    }
}
