using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using Debug = UnityEngine.Debug;

namespace PoliSim.EditorTools
{
    /// <summary>
    /// Stage 2 of the energy track (POLISIM_ENERGY_SPECLET.md, ruled §454; the data in ENERGY_LAYER_SPINE.md §455): the physical
    /// layer's six data files under `EnergyData/` - themselves generated by `Tools/energy_prep.pl` from the sources on disk - emitted
    /// into the runtime assembly as `EnergyLayerData`, the `ElectionsDataCatalogGenerator` idiom: each file's SHA-256 is written into
    /// the catalog and `GeneratedCatalogCheck` re-derives it every run, so a CSV cannot move while the C# stays.
    ///
    /// <para>What is asserted on the way in: the six files' headers; 6 countries × 7 labels of fleet rows in the catalog's order; ten
    /// load-block rows (six countries and SE1..SE4); four Swedish zones whose production types sum to their total; six directed links;
    /// 6 × 3 × 6 combustion rows in class order; six country rows. A file that fails any of those is not the file this catalog was
    /// designed for, and no catalog is written.</para>
    /// </summary>
    public static class EnergyCatalogGenerator
    {
        internal const string FleetSource = "EnergyData/fleet_2023.csv";
        internal const string BlocksSource = "EnergyData/load_blocks_2023.csv";
        internal const string ZonesSource = "EnergyData/zones_2023.csv";
        internal const string LinksSource = "EnergyData/links.csv";
        internal const string CombustionSource = "EnergyData/combustion_2023.csv";
        internal const string CountrySource = "EnergyData/country_2023.csv";
        private const string OutputRelative = "Assets/Scripts/Data/Generated/EnergyLayerData.cs";

        internal static readonly string[] Countries = { "DE", "FR", "IT", "PL", "SE", "US" };
        internal static readonly string[] Labels = { "coal", "gas", "nuclear", "hydro", "wind", "solar", "other" };
        internal static readonly string[] CombustionLabels = { "coal", "gas", "other" };
        internal static readonly string[] Classes = { "MAPE", "MAPCHP", "MAPH", "APE", "APCHP", "APH" };
        internal static readonly string[] ZoneProductionTypes = { "hydro", "nuclear", "wind", "solar", "thermal", "other" };
        internal static readonly string[] SwedishZones = { "SE1", "SE2", "SE3", "SE4" };

        [MenuItem("PoliSim/Generate Energy Catalog")]
        public static void Run()
        {
            CheckExit.ArmLogFold();
            string root = Directory.GetCurrentDirectory();
            try
            {
                (List<string[]> fleet, string dFleet) = Read(Path.Combine(root, FleetSource), "country;label;capacity_record_mw;capacity_ember_mw;generation_record_gwh;generation_ember_gwh");
                (List<string[]> blocks, string dBlocks) = Read(Path.Combine(root, BlocksSource), "zone;country;periods;step_h;hours;energy_gwh;min_mw;mean_mw;max_mw;p90_mw;peak_h;peak_mean_mw;mid_h;mid_mean_mw;inland_demand_gwh;scale");
                (List<string[]> zones, string dZones) = Read(Path.Combine(root, ZonesSource), "zone;country;consumption_gwh;hydro_gwh;nuclear_gwh;wind_gwh;solar_gwh;thermal_gwh;other_gwh;total_gwh");
                (List<string[]> links, string dLinks) = Read(Path.Combine(root, LinksSource), "from;to;ntc_mw;map_max_mw");
                (List<string[]> combustion, string dComb) = Read(Path.Combine(root, CombustionSource), "country;label;class;fuel_tj;co2_kt");
                (List<string[]> country, string dCountry) = Read(Path.Combine(root, CountrySource), "country;population_m;chp_share_main;chp_share_auto;inland_demand_gwh");

                // the fleet: 42 rows in the catalog's order
                if (fleet.Count != Countries.Length * Labels.Length) { throw new InvalidDataException($"fleet: {fleet.Count} rows, expected {Countries.Length * Labels.Length}"); }
                var capR = New2(Countries.Length, Labels.Length); var capE = New2(Countries.Length, Labels.Length); var genR = New2(Countries.Length, Labels.Length); var genE = New2(Countries.Length, Labels.Length);
                for (int i = 0; i < fleet.Count; i++)
                {
                    int c = i / Labels.Length, l = i % Labels.Length; string[] r = fleet[i];
                    if (r[0] != Countries[c] || r[1] != Labels[l]) { throw new InvalidDataException($"fleet row {i}: {r[0]}/{r[1]}, expected {Countries[c]}/{Labels[l]}"); }
                    capR[c][l] = P(r[2]); capE[c][l] = P(r[3]); genR[c][l] = P(r[4]); genE[c][l] = P(r[5]);
                    if (capR[c][l] < 0 || genR[c][l] < -1) { throw new InvalidDataException($"fleet row {i}: a negative figure"); }
                }
                // the load blocks: ten rows, the six countries then SE1..SE4
                if (blocks.Count != Countries.Length + SwedishZones.Length) { throw new InvalidDataException($"blocks: {blocks.Count} rows, expected {Countries.Length + SwedishZones.Length}"); }
                for (int i = 0; i < blocks.Count; i++)
                {
                    string expected = i < Countries.Length ? Countries[i] : SwedishZones[i - Countries.Length];
                    if (blocks[i][0] != expected) { throw new InvalidDataException($"blocks row {i}: zone {blocks[i][0]}, expected {expected}"); }
                    if (P(blocks[i][15]) <= 0 || P(blocks[i][15]) > 1.0000001) { throw new InvalidDataException($"blocks row {i}: scale {blocks[i][15]} outside (0, 1]"); }
                }
                // the zones: four, each production type summing to its total within a GWh
                if (zones.Count != SwedishZones.Length) { throw new InvalidDataException($"zones: {zones.Count} rows, expected {SwedishZones.Length}"); }
                for (int i = 0; i < zones.Count; i++)
                {
                    if (zones[i][0] != SwedishZones[i]) { throw new InvalidDataException($"zones row {i}: {zones[i][0]}, expected {SwedishZones[i]}"); }
                    double sum = 0; for (int t = 0; t < ZoneProductionTypes.Length; t++) { sum += P(zones[i][3 + t]); }
                    if (Math.Abs(sum - P(zones[i][9])) > 1.0) { throw new InvalidDataException($"zones row {i}: production types sum to {sum}, total {zones[i][9]}"); }
                }
                if (links.Count != 6) { throw new InvalidDataException($"links: {links.Count} rows, expected 6"); }
                // combustion: 6 × 3 × 6 in order
                if (combustion.Count != Countries.Length * CombustionLabels.Length * Classes.Length) { throw new InvalidDataException($"combustion: {combustion.Count} rows, expected {Countries.Length * CombustionLabels.Length * Classes.Length}"); }
                var fuel = New3(Countries.Length, CombustionLabels.Length, Classes.Length); var co2 = New3(Countries.Length, CombustionLabels.Length, Classes.Length);
                for (int i = 0; i < combustion.Count; i++)
                {
                    int c = i / (CombustionLabels.Length * Classes.Length), l = (i / Classes.Length) % CombustionLabels.Length, k = i % Classes.Length; string[] r = combustion[i];
                    if (r[0] != Countries[c] || r[1] != CombustionLabels[l] || r[2] != Classes[k]) { throw new InvalidDataException($"combustion row {i}: {r[0]}/{r[1]}/{r[2]}, expected {Countries[c]}/{CombustionLabels[l]}/{Classes[k]}"); }
                    fuel[c][l][k] = P(r[3]); co2[c][l][k] = P(r[4]);
                    if (fuel[c][l][k] < 0 || co2[c][l][k] < 0) { throw new InvalidDataException($"combustion row {i}: a negative figure"); }
                }
                if (country.Count != Countries.Length) { throw new InvalidDataException($"country: {country.Count} rows, expected {Countries.Length}"); }
                for (int i = 0; i < country.Count; i++) { if (country[i][0] != Countries[i]) { throw new InvalidDataException($"country row {i}: {country[i][0]}, expected {Countries[i]}"); } }

                string text = Emit(capR, capE, genR, genE, blocks, zones, links, fuel, co2, country, dFleet, dBlocks, dZones, dLinks, dComb, dCountry);
                File.WriteAllText(Path.Combine(root, OutputRelative), text, new UTF8Encoding(false));
                Debug.Log($"ENERGY: catalog written to {OutputRelative} from six files under EnergyData/ ({dFleet.Substring(0, 12)}…, {dBlocks.Substring(0, 12)}…, {dZones.Substring(0, 12)}…, {dLinks.Substring(0, 12)}…, {dComb.Substring(0, 12)}…, {dCountry.Substring(0, 12)}…).");
                CheckExit.Finish(0);
            }
            catch (Exception e)
            {
                Debug.LogError("ENERGY: catalog NOT written - " + e.Message);
                CheckExit.Finish(1);
            }
        }

        internal static (List<string[]> Rows, string Digest) Read(string path, string header)
        {
            if (!File.Exists(path)) { throw new FileNotFoundException(path); }
            byte[] bytes = File.ReadAllBytes(path);
            string digest = ElectionsDataCatalogGenerator.Sha256Of(bytes);
            var rows = new List<string[]>(); bool seenHeader = false;
            foreach (string raw in File.ReadAllLines(path))
            {
                string line = raw.Trim();
                if (line.Length == 0 || line.StartsWith("#", StringComparison.Ordinal)) { continue; }
                if (!seenHeader) { seenHeader = true; if (line != header) { throw new InvalidDataException($"{Path.GetFileName(path)}: unexpected header: {line}"); } continue; }
                string[] cells = line.Split(';');
                int expected = header.Split(';').Length;
                if (cells.Length != expected) { throw new InvalidDataException($"{Path.GetFileName(path)}: expected {expected} cells: {line}"); }
                rows.Add(cells);
            }
            return (rows, digest);
        }

        /// <summary>The data rows of a file, as GeneratedCatalogCheck counts them - the header and the comments skipped.</summary>
        internal static int DataRows(string path)
        {
            int rows = -1;
            foreach (string raw in File.ReadAllLines(path)) { string line = raw.Trim(); if (line.Length == 0 || line.StartsWith("#", StringComparison.Ordinal)) { continue; } rows++; }
            return Math.Max(0, rows);
        }

        private static double P(string s) => s.Trim().Length == 0 ? -1.0 : double.Parse(s.Trim(), NumberStyles.Float, CultureInfo.InvariantCulture);
        private static double[][] New2(int a, int b) { var m = new double[a][]; for (int i = 0; i < a; i++) { m[i] = new double[b]; } return m; }
        private static double[][][] New3(int a, int b, int c) { var m = new double[a][][]; for (int i = 0; i < a; i++) { m[i] = New2(b, c); } return m; }

        private static string Emit(double[][] capR, double[][] capE, double[][] genR, double[][] genE, List<string[]> blocks, List<string[]> zones, List<string[]> links, double[][][] fuel, double[][][] co2, List<string[]> country,
            string dFleet, string dBlocks, string dZones, string dLinks, string dComb, string dCountry)
        {
            var sb = new StringBuilder();
            sb.Append("// GENERATED by PoliSim.EditorTools.EnergyCatalogGenerator. DO NOT EDIT BY HAND.\n//\n");
            sb.Append("// Sources (each itself generated by Tools/energy_prep.pl from the files ENERGY_LAYER_SPINE.md lists by digest):\n");
            sb.Append("//   ").Append(FleetSource).Append(" (SHA-256 ").Append(dFleet).Append(")\n");
            sb.Append("//   ").Append(BlocksSource).Append(" (SHA-256 ").Append(dBlocks).Append(")\n");
            sb.Append("//   ").Append(ZonesSource).Append(" (SHA-256 ").Append(dZones).Append(")\n");
            sb.Append("//   ").Append(LinksSource).Append(" (SHA-256 ").Append(dLinks).Append(")\n");
            sb.Append("//   ").Append(CombustionSource).Append(" (SHA-256 ").Append(dComb).Append(")\n");
            sb.Append("//   ").Append(CountrySource).Append(" (SHA-256 ").Append(dCountry).Append(")\n//\n");
            sb.Append("// The digests above are what GeneratedCatalogCheck re-derives from the files every run. The files' own headers carry the\n");
            sb.Append("// provenance: the office of record per country, the fold into the seven labels, the P90 rule of the blocks, the two Svenska\n");
            sb.Append("// kraftnat documents behind the links, the IPCC factors and the operator split behind the combustion figures.\n\n");
            sb.Append("namespace PoliSim.Data.Generated\n{\n");
            sb.Append("    /// <summary>The energy layer's 2023 seed data for six countries and Sweden's four bidding zones - the fleet by the environment\n");
            sb.Append("    /// family's seven labels, the load folded into three blocks, the zones' consumption and production, the links between them, the\n");
            sb.Append("    /// combustion CO2 by plant class, and the per-country keys. Generated, never hand-edited; the units are in the member names.</summary>\n");
            sb.Append("    public static class EnergyLayerData\n    {\n");
            sb.Append("        public const string FleetDigest = \"").Append(dFleet).Append("\";\n");
            sb.Append("        public const string LoadBlocksDigest = \"").Append(dBlocks).Append("\";\n");
            sb.Append("        public const string ZonesDigest = \"").Append(dZones).Append("\";\n");
            sb.Append("        public const string LinksDigest = \"").Append(dLinks).Append("\";\n");
            sb.Append("        public const string CombustionDigest = \"").Append(dComb).Append("\";\n");
            sb.Append("        public const string CountryDigest = \"").Append(dCountry).Append("\";\n\n");
            sb.Append("        /// <summary>The six countries, in the catalog's order: ISO codes, the USA as US.</summary>\n");
            sb.Append("        public static readonly string[] Countries = { ").Append(Quote(Countries)).Append(" };\n");
            sb.Append("        /// <summary>The environment family's seven labels, in its order.</summary>\n");
            sb.Append("        public static readonly string[] Labels = { ").Append(Quote(Labels)).Append(" };\n\n");
            Matrix(sb, "CapacityRecordMw", "Net capacity 2023 by [country][label], MW - the office of record (Eurostat CAP_NET_ELC; the USA EIA net summer). Definitions in the file's header.", capR);
            Matrix(sb, "CapacityEmberMw", "Ember's capacity 2023 by [country][label], MW (nameplate) - the cross-check, never averaged in.", capE);
            Matrix(sb, "GenerationRecordGwh", "Gross generation 2023 by [country][label], GWh - the office of record (Eurostat GEP; the USA EIA net).", genR);
            Matrix(sb, "GenerationEmberGwh", "Ember's generation 2023 by [country][label], GWh.", genE);

            var zoneNames = new List<string>(); var zoneCc = new List<string>();
            var periods = new List<double>(); var step = new List<double>(); var hours = new List<double>(); var energy = new List<double>(); var min = new List<double>(); var mean = new List<double>(); var max = new List<double>(); var p90 = new List<double>();
            var peakH = new List<double>(); var peakMean = new List<double>(); var midH = new List<double>(); var midMean = new List<double>(); var inland = new List<double>(); var scale = new List<double>();
            foreach (string[] r in blocks)
            {
                zoneNames.Add(r[0]); zoneCc.Add(r[1]); periods.Add(P(r[2])); step.Add(P(r[3])); hours.Add(P(r[4])); energy.Add(P(r[5])); min.Add(P(r[6])); mean.Add(P(r[7])); max.Add(P(r[8])); p90.Add(P(r[9]));
                peakH.Add(P(r[10])); peakMean.Add(P(r[11])); midH.Add(P(r[12])); midMean.Add(P(r[13])); inland.Add(P(r[14])); scale.Add(P(r[15]));
            }
            sb.Append("        /// <summary>The load zones: the six countries, then SE1..SE4.</summary>\n");
            sb.Append("        public static readonly string[] Zones = { ").Append(Quote(zoneNames.ToArray())).Append(" };\n");
            sb.Append("        /// <summary>Each zone's country code.</summary>\n");
            sb.Append("        public static readonly string[] ZoneCountry = { ").Append(Quote(zoneCc.ToArray())).Append(" };\n");
            Block(sb, "Periods", "Periods in the 2023 series (35 040 quarter-hours for Germany, hours elsewhere).", periods.ToArray());
            Block(sb, "StepHours", "The period's length in hours.", step.ToArray());
            Block(sb, "Hours", "Hours covered.", hours.ToArray());
            Block(sb, "EnergyGwh", "The series' energy, GWh.", energy.ToArray());
            Block(sb, "MinMw", "The minimum period - the base block's level, every hour.", min.ToArray());
            Block(sb, "MeanMw", "The mean period.", mean.ToArray());
            Block(sb, "MaxMw", "The maximum period of calendar 2023 - a winter peak in Europe (Sweden's 6 December 17:00 CET), a summer one in the USA (27 July, the afternoon).", max.ToArray());
            Block(sb, "P90Mw", "The value exceeded by ten per cent of the periods - the cut between the peak and mid blocks (S3).", p90.ToArray());
            Block(sb, "PeakHours", "Hours in the peak block.", peakH.ToArray());
            Block(sb, "PeakMeanMw", "The peak block's level.", peakMean.ToArray());
            Block(sb, "MidHours", "Hours in the mid block.", midH.ToArray());
            Block(sb, "MidMeanMw", "The mid block's level.", midMean.ToArray());
            Block(sb, "InlandDemandGwh", "Eurostat inland demand 2023, GWh; -1 where the balance has no such figure (the USA and the zones).", inland.ToArray());
            Block(sb, "Scale", "min(1, inland demand / the series' energy) - the factor applied where the load series exceeds the balance (Poland); 1 elsewhere.", scale.ToArray());

            sb.Append("        /// <summary>Sweden's four bidding zones, north to south.</summary>\n");
            sb.Append("        public static readonly string[] SwedishZones = { ").Append(Quote(SwedishZones)).Append(" };\n");
            sb.Append("        /// <summary>eSett's production types, in the column order of ZoneProductionGwh.</summary>\n");
            sb.Append("        public static readonly string[] ZoneProductionTypes = { ").Append(Quote(ZoneProductionTypes)).Append(" };\n");
            var cons = new List<double>(); var prod = new List<double[]>();
            foreach (string[] r in zones) { cons.Add(P(r[2])); var p = new double[ZoneProductionTypes.Length]; for (int t = 0; t < p.Length; t++) { p[t] = P(r[3 + t]); } prod.Add(p); }
            Block(sb, "ZoneConsumptionGwh", "Settlement consumption 2023 per zone, GWh (eSett EXP15).", cons.ToArray());
            Matrix(sb, "ZoneProductionGwh", "Settlement production 2023 by [zone][type], GWh (eSett EXP16).", prod.ToArray());

            var from = new List<string>(); var to = new List<string>(); var ntc = new List<double>(); var mapMax = new List<double>();
            foreach (string[] r in links) { from.Add(r[0]); to.Add(r[1]); ntc.Add(P(r[2])); mapMax.Add(P(r[3])); }
            sb.Append("        /// <summary>The directed links between the zones - from.</summary>\n");
            sb.Append("        public static readonly string[] LinkFrom = { ").Append(Quote(from.ToArray())).Append(" };\n");
            sb.Append("        /// <summary>... and to.</summary>\n");
            sb.Append("        public static readonly string[] LinkTo = { ").Append(Quote(to.ToArray())).Append(" };\n");
            Block(sb, "LinkNtcMw", "Maximal allocated NTC 2021-2023 per direction, MW (Svenska kraftnat, 2024-09-30, Table 1) - the seed.", ntc.ToArray());
            Block(sb, "LinkMapMaxMw", "The network's maximum with no operational-security limit, MW (Svenska kraftnat's capacity-map text) - the ceiling.", mapMax.ToArray());

            sb.Append("        /// <summary>The combustion labels: the family's fossil three.</summary>\n");
            sb.Append("        public static readonly string[] CombustionLabels = { ").Append(Quote(CombustionLabels)).Append(" };\n");
            sb.Append("        /// <summary>The plant classes: main-activity electricity-only, main-activity CHP, main-activity heat-only, then the autoproducers' three.</summary>\n");
            sb.Append("        public static readonly string[] CombustionClasses = { ").Append(Quote(Classes)).Append(" };\n");
            Cube(sb, "FuelTj", "Fossil fuel burned 2023 by [country][label][class], TJ.", fuel);
            Cube(sb, "Co2Kt", "Its CO2 at the IPCC 2006 default factors by [country][label][class], kt.", co2);

            var pop = new List<double>(); var shareMain = new List<double>(); var shareAuto = new List<double>(); var inlandC = new List<double>();
            foreach (string[] r in country) { pop.Add(P(r[1])); shareMain.Add(P(r[2])); shareAuto.Add(P(r[3])); inlandC.Add(P(r[4])); }
            Block(sb, "PopulationM", "World Bank population 2023, millions - the divisor of the environment family's per-head seeds.", pop.ToArray());
            Block(sb, "ChpShareMain", "Main-activity CHP plants' electricity share of their electricity + heat output (1 for the USA, whose split EIA applies itself).", shareMain.ToArray());
            Block(sb, "ChpShareAuto", "The autoproducers' CHP electricity share, likewise.", shareAuto.ToArray());
            Block(sb, "CountryInlandDemandGwh", "Inland demand 2023 per country, GWh (Eurostat nrg_cb_e; the USA's EIA net generation).", inlandC.ToArray());
            sb.Append("    }\n}\n");
            return sb.ToString();
        }

        private static string Quote(string[] items) { var q = new List<string>(); foreach (string s in items) { q.Add("\"" + s + "\""); } return string.Join(", ", q); }
        private static string N(double v) => v.ToString("0.####", CultureInfo.InvariantCulture);

        private static void Block(StringBuilder sb, string name, string doc, double[] values)
        {
            sb.Append("        /// <summary>").Append(doc).Append("</summary>\n");
            sb.Append("        public static readonly double[] ").Append(name).Append(" = { ");
            for (int i = 0; i < values.Length; i++) { sb.Append(N(values[i])).Append(i + 1 < values.Length ? ", " : ""); }
            sb.Append(" };\n\n");
        }

        private static void Matrix(StringBuilder sb, string name, string doc, double[][] values)
        {
            sb.Append("        /// <summary>").Append(doc).Append("</summary>\n");
            sb.Append("        public static readonly double[][] ").Append(name).Append(" =\n        {\n");
            foreach (double[] row in values)
            {
                sb.Append("            new double[] { ");
                for (int i = 0; i < row.Length; i++) { sb.Append(N(row[i])).Append(i + 1 < row.Length ? ", " : ""); }
                sb.Append(" },\n");
            }
            sb.Append("        };\n\n");
        }

        private static void Cube(StringBuilder sb, string name, string doc, double[][][] values)
        {
            sb.Append("        /// <summary>").Append(doc).Append("</summary>\n");
            sb.Append("        public static readonly double[][][] ").Append(name).Append(" =\n        {\n");
            foreach (double[][] plane in values)
            {
                sb.Append("            new double[][]\n            {\n");
                foreach (double[] row in plane)
                {
                    sb.Append("                new double[] { ");
                    for (int i = 0; i < row.Length; i++) { sb.Append(N(row[i])).Append(i + 1 < row.Length ? ", " : ""); }
                    sb.Append(" },\n");
                }
                sb.Append("            },\n");
            }
            sb.Append("        };\n\n");
        }
    }
}
