using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using Debug = UnityEngine.Debug;

namespace PoliSim.EditorTools
{
    /// <summary>
    /// Stage 2 of the energy track (POLISIM_ENERGY_SPECLET.md, ruled §454; the data in ENERGY_LAYER_SPINE.md §455): the physical
    /// layer's six data files under `EnergyData/` - themselves generated by `Tools/energy_prep.pl` from the sources on disk - emitted
    /// into the runtime assembly as `EnergyLayerData`, the `ElectionsDataCatalogGenerator` idiom: each file's SHA-256 is written into
    /// the catalog and `GeneratedCatalogCheck` re-derives it every run, so a CSV cannot move while the C# stays.
    ///
    /// <para>What is asserted on the way in: the six files' headers; 6 countries × 7 labels of fleet rows in the catalog's order; ten
    /// load-block rows (six countries and SE1..SE4); four Swedish zones whose production types sum to their total; six directed links;
    /// 6 × 3 × 6 combustion rows in class order; six country rows. A file that fails any of those is not the file this catalog was
    /// designed for, and no catalog is written.</para>
    /// </summary>
    public static class EnergyCatalogGenerator
    {
        internal const string FleetSource = "EnergyData/fleet_2023.csv";
        internal const string BlocksSource = "EnergyData/load_blocks_2023.csv";
        internal const string ZonesSource = "EnergyData/zones_2023.csv";
        internal const string LinksSource = "EnergyData/links.csv";
        internal const string CombustionSource = "EnergyData/combustion_2023.csv";
        internal const string CountrySource = "EnergyData/country_2023.csv";
        // EN-3 (2026-09-11), the market layer's three - generated by Tools/energy_market_prep.pl
        internal const string DispatchSource = "EnergyData/dispatch_levels_2023.csv";
        internal const string CostsSource = "EnergyData/variable_costs_2023.csv";
        internal const string ExternalLinksSource = "EnergyData/external_links_se.csv";
        // EN-4 (2026-09-11), the fiscal layer's retail seed - generated by Tools/energy_fiscal_prep.pl
        internal const string RetailSource = "EnergyData/retail_2023.csv";
        internal static readonly string[] RetailClasses = { "households", "nonhousehold" };
        /// <summary>EN-5: electricity's weight in each country's consumer price index, per mille (Eurostat prc_hicp_inw CP0451; BLS relative importance for the USA).</summary>
        internal const string PriceIndexWeightSource = "EnergyData/price_index_weights_2023.csv";
        private const string OutputRelative = "Assets/Scripts/Data/Generated/EnergyLayerData.cs";
        internal static readonly string[] DispatchBlocks = { "base", "mid", "peak" };
        internal static readonly string[] DispatchCategories = { "coal", "gas", "oil", "nuclear", "hydro", "wind", "solar", "firm" };
        internal static readonly string[] CostCategories = { "coal", "gas", "oil" };

        internal static readonly string[] Countries = { "DE", "FR", "IT", "PL", "SE", "US" };
        internal static readonly string[] Labels = { "coal", "gas", "nuclear", "hydro", "wind", "solar", "other" };
        internal static readonly string[] CombustionLabels = { "coal", "gas", "other" };
        internal static readonly string[] Classes = { "MAPE", "MAPCHP", "MAPH", "APE", "APCHP", "APH" };
        internal static readonly string[] ZoneProductionTypes = { "hydro", "nuclear", "wind", "solar", "thermal", "other" };
        internal static readonly string[] SwedishZones = { "SE1", "SE2", "SE3", "SE4" };

        [MenuItem("PoliSim/Generate Energy Catalog")]
        public static void Run()
        {
            CheckExit.ArmLogFold();
            string root = Directory.GetCurrentDirectory();
            try
            {
                (List<string[]> fleet, string dFleet) = Read(Path.Combine(root, FleetSource), "country;label;capacity_record_mw;capacity_ember_mw;generation_record_gwh;generation_ember_gwh");
                (List<string[]> blocks, string dBlocks) = Read(Path.Combine(root, BlocksSource), "zone;country;periods;step_h;hours;energy_gwh;min_mw;mean_mw;max_mw;p90_mw;peak_h;peak_mean_mw;mid_h;mid_mean_mw;inland_demand_gwh;scale");
                (List<string[]> zones, string dZones) = Read(Path.Combine(root, ZonesSource), "zone;country;consumption_gwh;hydro_gwh;nuclear_gwh;wind_gwh;solar_gwh;thermal_gwh;other_gwh;total_gwh");
                (List<string[]> links, string dLinks) = Read(Path.Combine(root, LinksSource), "from;to;ntc_mw;map_max_mw");
                (List<string[]> combustion, string dComb) = Read(Path.Combine(root, CombustionSource), "country;label;class;fuel_tj;co2_kt");
                (List<string[]> country, string dCountry) = Read(Path.Combine(root, CountrySource), "country;population_m;chp_share_main;chp_share_auto;inland_demand_gwh");

                // the fleet: 42 rows in the catalog's order
                if (fleet.Count != Countries.Length * Labels.Length) { throw new InvalidDataException($"fleet: {fleet.Count} rows, expected {Countries.Length * Labels.Length}"); }
                var capR = New2(Countries.Length, Labels.Length); var capE = New2(Countries.Length, Labels.Length); var genR = New2(Countries.Length, Labels.Length); var genE = New2(Countries.Length, Labels.Length);
                for (int i = 0; i < fleet.Count; i++)
                {
                    int c = i / Labels.Length, l = i % Labels.Length; string[] r = fleet[i];
                    if (r[0] != Countries[c] || r[1] != Labels[l]) { throw new InvalidDataException($"fleet row {i}: {r[0]}/{r[1]}, expected {Countries[c]}/{Labels[l]}"); }
                    capR[c][l] = P(r[2]); capE[c][l] = P(r[3]); genR[c][l] = P(r[4]); genE[c][l] = P(r[5]);
                    if (capR[c][l] < 0 || genR[c][l] < -1) { throw new InvalidDataException($"fleet row {i}: a negative figure"); }
                }
                // the load blocks: ten rows, the six countries then SE1..SE4
                if (blocks.Count != Countries.Length + SwedishZones.Length) { throw new InvalidDataException($"blocks: {blocks.Count} rows, expected {Countries.Length + SwedishZones.Length}"); }
                for (int i = 0; i < blocks.Count; i++)
                {
                    string expected = i < Countries.Length ? Countries[i] : SwedishZones[i - Countries.Length];
                    if (blocks[i][0] != expected) { throw new InvalidDataException($"blocks row {i}: zone {blocks[i][0]}, expected {expected}"); }
                    if (P(blocks[i][15]) <= 0 || P(blocks[i][15]) > 1.0000001) { throw new InvalidDataException($"blocks row {i}: scale {blocks[i][15]} outside (0, 1]"); }
                }
                // the zones: four, each production type summing to its total within a GWh
                if (zones.Count != SwedishZones.Length) { throw new InvalidDataException($"zones: {zones.Count} rows, expected {SwedishZones.Length}"); }
                for (int i = 0; i < zones.Count; i++)
                {
                    if (zones[i][0] != SwedishZones[i]) { throw new InvalidDataException($"zones row {i}: {zones[i][0]}, expected {SwedishZones[i]}"); }
                    double sum = 0; for (int t = 0; t < ZoneProductionTypes.Length; t++) { sum += P(zones[i][3 + t]); }
                    if (Math.Abs(sum - P(zones[i][9])) > 1.0) { throw new InvalidDataException($"zones row {i}: production types sum to {sum}, total {zones[i][9]}"); }
                }
                if (links.Count != 6) { throw new InvalidDataException($"links: {links.Count} rows, expected 6"); }
                // combustion: 6 × 3 × 6 in order
                if (combustion.Count != Countries.Length * CombustionLabels.Length * Classes.Length) { throw new InvalidDataException($"combustion: {combustion.Count} rows, expected {Countries.Length * CombustionLabels.Length * Classes.Length}"); }
                var fuel = New3(Countries.Length, CombustionLabels.Length, Classes.Length); var co2 = New3(Countries.Length, CombustionLabels.Length, Classes.Length);
                for (int i = 0; i < combustion.Count; i++)
                {
                    int c = i / (CombustionLabels.Length * Classes.Length), l = (i / Classes.Length) % CombustionLabels.Length, k = i % Classes.Length; string[] r = combustion[i];
                    if (r[0] != Countries[c] || r[1] != CombustionLabels[l] || r[2] != Classes[k]) { throw new InvalidDataException($"combustion row {i}: {r[0]}/{r[1]}/{r[2]}, expected {Countries[c]}/{CombustionLabels[l]}/{Classes[k]}"); }
                    fuel[c][l][k] = P(r[3]); co2[c][l][k] = P(r[4]);
                    if (fuel[c][l][k] < 0 || co2[c][l][k] < 0) { throw new InvalidDataException($"combustion row {i}: a negative figure"); }
                }
                if (country.Count != Countries.Length) { throw new InvalidDataException($"country: {country.Count} rows, expected {Countries.Length}"); }
                for (int i = 0; i < country.Count; i++) { if (country[i][0] != Countries[i]) { throw new InvalidDataException($"country row {i}: {country[i][0]}, expected {Countries[i]}"); } }

                // EN-3: the market layer's three files
                (List<string[]> dispatch, string dDispatch) = Read(Path.Combine(root, DispatchSource), "zone;block;hours;demand_mw;coal_mw;gas_mw;oil_mw;nuclear_mw;hydro_mw;wind_mw;solar_mw;firm_mw;consumption_mw;external_export_mw");
                (List<string[]> costs, string dCosts) = Read(Path.Combine(root, CostsSource), "country;category;fuel_per_mwh_th;efficiency;ef_t_per_mwh;vom_per_mwh;availability;main_share;lignite_share;ets_per_t;national_per_market;usd_per_market");
                (List<string[]> external, string dExternal) = Read(Path.Combine(root, ExternalLinksSource), "zone;neighbour;out_mw;in_mw");
                int zoneCount = Countries.Length + SwedishZones.Length;
                if (dispatch.Count != zoneCount * DispatchBlocks.Length) { throw new InvalidDataException($"dispatch: {dispatch.Count} rows, expected {zoneCount * DispatchBlocks.Length}"); }
                for (int i = 0; i < dispatch.Count; i++)
                {
                    int z = i / DispatchBlocks.Length, b = i % DispatchBlocks.Length; string expectedZone = z < Countries.Length ? Countries[z] : SwedishZones[z - Countries.Length];
                    if (dispatch[i][0] != expectedZone || dispatch[i][1] != DispatchBlocks[b]) { throw new InvalidDataException($"dispatch row {i}: {dispatch[i][0]}/{dispatch[i][1]}, expected {expectedZone}/{DispatchBlocks[b]}"); }
                    if (P(dispatch[i][2]) <= 0) { throw new InvalidDataException($"dispatch row {i}: no hours"); }
                    double sum = 0; for (int c = 0; c < DispatchCategories.Length; c++) { sum += P(dispatch[i][4 + c]); }
                    if (Math.Abs(sum - P(dispatch[i][3])) > 1.0) { throw new InvalidDataException($"dispatch row {i}: the categories sum to {sum:0.0} MW against a demand of {dispatch[i][3]}"); }
                }
                if (costs.Count != Countries.Length * CostCategories.Length) { throw new InvalidDataException($"costs: {costs.Count} rows, expected {Countries.Length * CostCategories.Length}"); }
                for (int i = 0; i < costs.Count; i++)
                {
                    int c = i / CostCategories.Length, k = i % CostCategories.Length;
                    if (costs[i][0] != Countries[c] || costs[i][1] != CostCategories[k]) { throw new InvalidDataException($"costs row {i}: {costs[i][0]}/{costs[i][1]}, expected {Countries[c]}/{CostCategories[k]}"); }
                    if (P(costs[i][3]) < 0 || P(costs[i][3]) > 1 || P(costs[i][6]) <= 0 || P(costs[i][6]) > 1) { throw new InvalidDataException($"costs row {i}: efficiency {costs[i][3]} or availability {costs[i][6]} outside (0, 1]"); }
                }
                if (external.Count < 4) { throw new InvalidDataException($"external links: {external.Count} rows"); }
                // EN-4: the retail seed - 6 × 2 rows, the components summing to the total
                (List<string[]> retail, string dRetail) = Read(Path.Combine(root, RetailSource), "country;class;consumption_gwh;energy_supply;network;policy;tax_env;vat;total");
                if (retail.Count != Countries.Length * RetailClasses.Length) { throw new InvalidDataException($"retail: {retail.Count} rows, expected {Countries.Length * RetailClasses.Length}"); }
                for (int i = 0; i < retail.Count; i++)
                {
                    int c = i / RetailClasses.Length, k = i % RetailClasses.Length; string[] r = retail[i];
                    if (r[0] != Countries[c] || r[1] != RetailClasses[k]) { throw new InvalidDataException($"retail row {i}: {r[0]}/{r[1]}, expected {Countries[c]}/{RetailClasses[k]}"); }
                    double sum = P(r[3]) + P(r[4]) + P(r[5]) + P(r[6]) + P(r[7]);
                    if (Math.Abs(sum - P(r[8])) > 0.0003 || P(r[2]) <= 0) { throw new InvalidDataException($"retail row {i}: the components sum to {sum:0.0000} against a total of {r[8]}, or no consumption"); }
                }

                // EN-5: the price-index weights, one row per country in the catalog's order
                (List<string[]> weights, string dWeights) = Read(Path.Combine(root, PriceIndexWeightSource), "country;electricity_per_mille;source");
                if (weights.Count != Countries.Length) { throw new InvalidDataException($"price index weights: {weights.Count} rows, expected {Countries.Length}"); }
                for (int i = 0; i < weights.Count; i++) { if (weights[i][0] != Countries[i]) { throw new InvalidDataException($"price index weight row {i}: {weights[i][0]}, expected {Countries[i]}"); } if (P(weights[i][1]) <= 0) { throw new InvalidDataException($"price index weight for {Countries[i]} is not positive"); } }
                string text = Emit(capR, capE, genR, genE, blocks, zones, links, fuel, co2, country, dFleet, dBlocks, dZones, dLinks, dComb, dCountry, dispatch, costs, external, dDispatch, dCosts, dExternal, retail, dRetail, weights, dWeights);
                File.WriteAllText(Path.Combine(root, OutputRelative), text, new UTF8Encoding(false));
                Debug.Log($"ENERGY: catalog written to {OutputRelative} from six files under EnergyData/ ({dFleet.Substring(0, 12)}…, {dBlocks.Substring(0, 12)}…, {dZones.Substring(0, 12)}…, {dLinks.Substring(0, 12)}…, {dComb.Substring(0, 12)}…, {dCountry.Substring(0, 12)}…).");
                CheckExit.Finish(0);
            }
            catch (Exception e)
            {
                Debug.LogError("ENERGY: catalog NOT written - " + e.Message);
                CheckExit.Finish(1);
            }
        }

        internal static (List<string[]> Rows, string Digest) Read(string path, string header)
        {
            if (!File.Exists(path)) { throw new FileNotFoundException(path); }
            byte[] bytes = File.ReadAllBytes(path);
            string digest = ElectionsDataCatalogGenerator.Sha256Of(bytes);
            var rows = new List<string[]>(); bool seenHeader = false;
            foreach (string raw in File.ReadAllLines(path))
            {
                string line = raw.Trim();
                if (line.Length == 0 || line.StartsWith("#", StringComparison.Ordinal)) { continue; }
                if (!seenHeader) { seenHeader = true; if (line != header) { throw new InvalidDataException($"{Path.GetFileName(path)}: unexpected header: {line}"); } continue; }
                string[] cells = line.Split(';');
                int expected = header.Split(';').Length;
                if (cells.Length != expected) { throw new InvalidDataException($"{Path.GetFileName(path)}: expected {expected} cells: {line}"); }
                rows.Add(cells);
            }
            return (rows, digest);
        }

        /// <summary>The data rows of a file, as GeneratedCatalogCheck counts them - the header and the comments skipped.</summary>
        internal static int DataRows(string path)
        {
            int rows = -1;
            foreach (string raw in File.ReadAllLines(path)) { string line = raw.Trim(); if (line.Length == 0 || line.StartsWith("#", StringComparison.Ordinal)) { continue; } rows++; }
            return Math.Max(0, rows);
        }

        private static double P(string s) => s.Trim().Length == 0 ? -1.0 : double.Parse(s.Trim(), NumberStyles.Float, CultureInfo.InvariantCulture);
        private static double[][] New2(int a, int b) { var m = new double[a][]; for (int i = 0; i < a; i++) { m[i] = new double[b]; } return m; }
        private static double[][][] New3(int a, int b, int c) { var m = new double[a][][]; for (int i = 0; i < a; i++) { m[i] = New2(b, c); } return m; }

        private static string Emit(double[][] capR, double[][] capE, double[][] genR, double[][] genE, List<string[]> blocks, List<string[]> zones, List<string[]> links, double[][][] fuel, double[][][] co2, List<string[]> country,
            string dFleet, string dBlocks, string dZones, string dLinks, string dComb, string dCountry,
            List<string[]> dispatch, List<string[]> costs, List<string[]> external, string dDispatch, string dCosts, string dExternal, List<string[]> retail, string dRetail, List<string[]> weights, string dWeights)
        {
            var sb = new StringBuilder();
            sb.Append("// GENERATED by PoliSim.EditorTools.EnergyCatalogGenerator. DO NOT EDIT BY HAND.\n//\n");
            sb.Append("// Sources (each itself generated by Tools/energy_prep.pl from the files ENERGY_LAYER_SPINE.md lists by digest):\n");
            sb.Append("//   ").Append(FleetSource).Append(" (SHA-256 ").Append(dFleet).Append(")\n");
            sb.Append("//   ").Append(BlocksSource).Append(" (SHA-256 ").Append(dBlocks).Append(")\n");
            sb.Append("//   ").Append(ZonesSource).Append(" (SHA-256 ").Append(dZones).Append(")\n");
            sb.Append("//   ").Append(LinksSource).Append(" (SHA-256 ").Append(dLinks).Append(")\n");
            sb.Append("//   ").Append(CombustionSource).Append(" (SHA-256 ").Append(dComb).Append(")\n");
            sb.Append("//   ").Append(CountrySource).Append(" (SHA-256 ").Append(dCountry).Append(")\n//\n");
            sb.Append("// The digests above are what GeneratedCatalogCheck re-derives from the files every run. The files' own headers carry the\n");
            sb.Append("// provenance: the office of record per country, the fold into the seven labels, the P90 rule of the blocks, the two Svenska\n");
            sb.Append("// kraftnat documents behind the links, the IPCC factors and the operator split behind the combustion figures.\n\n");
            sb.Append("namespace PoliSim.Data.Generated\n{\n");
            sb.Append("    /// <summary>The energy layer's 2023 seed data for six countries and Sweden's four bidding zones - the fleet by the environment\n");
            sb.Append("    /// family's seven labels, the load folded into three blocks, the zones' consumption and production, the links between them, the\n");
            sb.Append("    /// combustion CO2 by plant class, and the per-country keys. Generated, never hand-edited; the units are in the member names.</summary>\n");
            sb.Append("    public static class EnergyLayerData\n    {\n");
            sb.Append("        public const string FleetDigest = \"").Append(dFleet).Append("\";\n");
            sb.Append("        public const string LoadBlocksDigest = \"").Append(dBlocks).Append("\";\n");
            sb.Append("        public const string ZonesDigest = \"").Append(dZones).Append("\";\n");
            sb.Append("        public const string LinksDigest = \"").Append(dLinks).Append("\";\n");
            sb.Append("        public const string CombustionDigest = \"").Append(dComb).Append("\";\n");
            sb.Append("        public const string CountryDigest = \"").Append(dCountry).Append("\";\n\n");
            sb.Append("        /// <summary>The six countries, in the catalog's order: ISO codes, the USA as US.</summary>\n");
            sb.Append("        public static readonly string[] Countries = { ").Append(Quote(Countries)).Append(" };\n");
            sb.Append("        /// <summary>The environment family's seven labels, in its order.</summary>\n");
            sb.Append("        public static readonly string[] Labels = { ").Append(Quote(Labels)).Append(" };\n\n");
            Matrix(sb, "CapacityRecordMw", "Net capacity 2023 by [country][label], MW - the office of record (Eurostat CAP_NET_ELC; the USA EIA net summer). Definitions in the file's header.", capR);
            Matrix(sb, "CapacityEmberMw", "Ember's capacity 2023 by [country][label], MW (nameplate) - the cross-check, never averaged in.", capE);
            Matrix(sb, "GenerationRecordGwh", "Gross generation 2023 by [country][label], GWh - the office of record (Eurostat GEP; the USA EIA net).", genR);
            Matrix(sb, "GenerationEmberGwh", "Ember's generation 2023 by [country][label], GWh.", genE);

            var zoneNames = new List<string>(); var zoneCc = new List<string>();
            var periods = new List<double>(); var step = new List<double>(); var hours = new List<double>(); var energy = new List<double>(); var min = new List<double>(); var mean = new List<double>(); var max = new List<double>(); var p90 = new List<double>();
            var peakH = new List<double>(); var peakMean = new List<double>(); var midH = new List<double>(); var midMean = new List<double>(); var inland = new List<double>(); var scale = new List<double>();
            foreach (string[] r in blocks)
            {
                zoneNames.Add(r[0]); zoneCc.Add(r[1]); periods.Add(P(r[2])); step.Add(P(r[3])); hours.Add(P(r[4])); energy.Add(P(r[5])); min.Add(P(r[6])); mean.Add(P(r[7])); max.Add(P(r[8])); p90.Add(P(r[9]));
                peakH.Add(P(r[10])); peakMean.Add(P(r[11])); midH.Add(P(r[12])); midMean.Add(P(r[13])); inland.Add(P(r[14])); scale.Add(P(r[15]));
            }
            sb.Append("        /// <summary>The load zones: the six countries, then SE1..SE4.</summary>\n");
            sb.Append("        public static readonly string[] Zones = { ").Append(Quote(zoneNames.ToArray())).Append(" };\n");
            sb.Append("        /// <summary>Each zone's country code.</summary>\n");
            sb.Append("        public static readonly string[] ZoneCountry = { ").Append(Quote(zoneCc.ToArray())).Append(" };\n");
            Block(sb, "Periods", "Periods in the 2023 series (35 040 quarter-hours for Germany, hours elsewhere).", periods.ToArray());
            Block(sb, "StepHours", "The period's length in hours.", step.ToArray());
            Block(sb, "Hours", "Hours covered.", hours.ToArray());
            Block(sb, "EnergyGwh", "The series' energy, GWh.", energy.ToArray());
            Block(sb, "MinMw", "The minimum period - the base block's level, every hour.", min.ToArray());
            Block(sb, "MeanMw", "The mean period.", mean.ToArray());
            Block(sb, "MaxMw", "The maximum period of calendar 2023 - a winter peak in Europe (Sweden's 6 December 17:00 CET), a summer one in the USA (27 July, the afternoon).", max.ToArray());
            Block(sb, "P90Mw", "The value exceeded by ten per cent of the periods - the cut between the peak and mid blocks (S3).", p90.ToArray());
            Block(sb, "PeakHours", "Hours in the peak block.", peakH.ToArray());
            Block(sb, "PeakMeanMw", "The peak block's level.", peakMean.ToArray());
            Block(sb, "MidHours", "Hours in the mid block.", midH.ToArray());
            Block(sb, "MidMeanMw", "The mid block's level.", midMean.ToArray());
            Block(sb, "InlandDemandGwh", "Eurostat inland demand 2023, GWh; -1 where the balance has no such figure (the USA and the zones).", inland.ToArray());
            Block(sb, "Scale", "min(1, inland demand / the series' energy) - the factor applied where the load series exceeds the balance (Poland); 1 elsewhere.", scale.ToArray());

            sb.Append("        /// <summary>Sweden's four bidding zones, north to south.</summary>\n");
            sb.Append("        public static readonly string[] SwedishZones = { ").Append(Quote(SwedishZones)).Append(" };\n");
            sb.Append("        /// <summary>eSett's production types, in the column order of ZoneProductionGwh.</summary>\n");
            sb.Append("        public static readonly string[] ZoneProductionTypes = { ").Append(Quote(ZoneProductionTypes)).Append(" };\n");
            var cons = new List<double>(); var prod = new List<double[]>();
            foreach (string[] r in zones) { cons.Add(P(r[2])); var p = new double[ZoneProductionTypes.Length]; for (int t = 0; t < p.Length; t++) { p[t] = P(r[3 + t]); } prod.Add(p); }
            Block(sb, "ZoneConsumptionGwh", "Settlement consumption 2023 per zone, GWh (eSett EXP15).", cons.ToArray());
            Matrix(sb, "ZoneProductionGwh", "Settlement production 2023 by [zone][type], GWh (eSett EXP16).", prod.ToArray());

            var from = new List<string>(); var to = new List<string>(); var ntc = new List<double>(); var mapMax = new List<double>();
            foreach (string[] r in links) { from.Add(r[0]); to.Add(r[1]); ntc.Add(P(r[2])); mapMax.Add(P(r[3])); }
            sb.Append("        /// <summary>The directed links between the zones - from.</summary>\n");
            sb.Append("        public static readonly string[] LinkFrom = { ").Append(Quote(from.ToArray())).Append(" };\n");
            sb.Append("        /// <summary>... and to.</summary>\n");
            sb.Append("        public static readonly string[] LinkTo = { ").Append(Quote(to.ToArray())).Append(" };\n");
            Block(sb, "LinkNtcMw", "Maximal allocated NTC 2021-2023 per direction, MW (Svenska kraftnat, 2024-09-30, Table 1) - the seed.", ntc.ToArray());
            Block(sb, "LinkMapMaxMw", "The network's maximum with no operational-security limit, MW (Svenska kraftnat's capacity-map text) - the ceiling.", mapMax.ToArray());

            sb.Append("        /// <summary>The combustion labels: the family's fossil three.</summary>\n");
            sb.Append("        public static readonly string[] CombustionLabels = { ").Append(Quote(CombustionLabels)).Append(" };\n");
            sb.Append("        /// <summary>The plant classes: main-activity electricity-only, main-activity CHP, main-activity heat-only, then the autoproducers' three.</summary>\n");
            sb.Append("        public static readonly string[] CombustionClasses = { ").Append(Quote(Classes)).Append(" };\n");
            Cube(sb, "FuelTj", "Fossil fuel burned 2023 by [country][label][class], TJ.", fuel);
            Cube(sb, "Co2Kt", "Its CO2 at the IPCC 2006 default factors by [country][label][class], kt.", co2);

            var pop = new List<double>(); var shareMain = new List<double>(); var shareAuto = new List<double>(); var inlandC = new List<double>();
            foreach (string[] r in country) { pop.Add(P(r[1])); shareMain.Add(P(r[2])); shareAuto.Add(P(r[3])); inlandC.Add(P(r[4])); }
            Block(sb, "PopulationM", "World Bank population 2023, millions - the divisor of the environment family's per-head seeds.", pop.ToArray());
            Block(sb, "ChpShareMain", "Main-activity CHP plants' electricity share of their electricity + heat output (1 for the USA, whose split EIA applies itself).", shareMain.ToArray());
            Block(sb, "ChpShareAuto", "The autoproducers' CHP electricity share, likewise.", shareAuto.ToArray());
            Block(sb, "CountryInlandDemandGwh", "Inland demand 2023 per country, GWh (Eurostat nrg_cb_e; the USA's EIA net generation).", inlandC.ToArray());

            // ---- EN-3, the market layer -----------------------------------------------------------------------
            sb.Append("        // ---- EN-3 (2026-09-11): the market layer - the clearing's blocks as hours, the 2023 levels per category, the merit order's inputs\n");
            sb.Append("        public const string DispatchDigest = \"").Append(dDispatch).Append("\";\n");
            sb.Append("        public const string CostsDigest = \"").Append(dCosts).Append("\";\n");
            sb.Append("        public const string ExternalLinksDigest = \"").Append(dExternal).Append("\";\n");
            sb.Append("        /// <summary>The clearing's three blocks as hours - the trough decile, the middle eight, the top decile of the load (S3's P90 cut and its mirror).</summary>\n");
            sb.Append("        public static readonly string[] DispatchBlocks = { ").Append(Quote(DispatchBlocks)).Append(" };\n");
            sb.Append("        /// <summary>The dispatch's categories: the three fossil ones in merit order, then the resource-driven and the firm (must-run) output.</summary>\n");
            sb.Append("        public static readonly string[] DispatchCategories = { ").Append(Quote(DispatchCategories)).Append(" };\n");
            int zoneCount = Countries.Length + SwedishZones.Length;
            var dHours = New2(zoneCount, DispatchBlocks.Length); var dDemand = New2(zoneCount, DispatchBlocks.Length); var dCons = New2(zoneCount, DispatchBlocks.Length); var dExt = New2(zoneCount, DispatchBlocks.Length);
            var dLevel = New3(zoneCount, DispatchBlocks.Length, DispatchCategories.Length);
            for (int i = 0; i < dispatch.Count; i++)
            {
                int z = i / DispatchBlocks.Length, b = i % DispatchBlocks.Length; string[] r = dispatch[i];
                dHours[z][b] = P(r[2]); dDemand[z][b] = P(r[3]); for (int c = 0; c < DispatchCategories.Length; c++) { dLevel[z][b][c] = P(r[4 + c]); }
                dCons[z][b] = r[12].Trim().Length == 0 ? -1 : P(r[12]); dExt[z][b] = r[13].Trim().Length == 0 ? 0 : P(r[13]);
            }
            Matrix(sb, "DispatchHours", "Hours in each block by [zone][block] (the zones in Zones' order).", dHours);
            Matrix(sb, "DispatchDemandMw", "The block's demand by [zone][block], MW - the total generation level in the block's hours (consumption + net export + losses + pumping).", dDemand);
            Cube(sb, "DispatchLevelMw", "The 2023 output level by [zone][block][category], MW, in the block's hours.", dLevel);
            Matrix(sb, "ZoneConsumptionBlockMw", "Sweden's zones: settlement consumption by [zone][block], MW, on the national block hours; -1 for the countries (their demand row is the balance).", dCons);
            Matrix(sb, "ZoneExternalExportMw", "Sweden's zones: the exogenous external export by [zone][block], MW, positive out of Sweden (energy-charts cbpf apportioned by the interconnectors); 0 for the countries.", dExt);
            sb.Append("        /// <summary>The merit order's categories.</summary>\n");
            sb.Append("        public static readonly string[] CostCategories = { ").Append(Quote(CostCategories)).Append(" };\n");
            var fuelP = New2(Countries.Length, CostCategories.Length); var eff = New2(Countries.Length, CostCategories.Length); var ef = New2(Countries.Length, CostCategories.Length); var vom = New2(Countries.Length, CostCategories.Length);
            var avail = New2(Countries.Length, CostCategories.Length); var main = New2(Countries.Length, CostCategories.Length); var lig = New2(Countries.Length, CostCategories.Length); var ets = new double[Countries.Length]; var nat = new double[Countries.Length]; var usd = new double[Countries.Length];
            for (int i = 0; i < costs.Count; i++)
            {
                int c = i / CostCategories.Length, k = i % CostCategories.Length; string[] r = costs[i];
                fuelP[c][k] = P(r[2]); eff[c][k] = P(r[3]); ef[c][k] = P(r[4]); vom[c][k] = P(r[5]); avail[c][k] = P(r[6]); main[c][k] = P(r[7]); lig[c][k] = P(r[8]); ets[c] = P(r[9]); nat[c] = P(r[10]); usd[c] = P(r[11]);
            }
            Matrix(sb, "FuelPerMwhTh", "Fuel price 2023 by [country][cost category], the country's currency per MWh of fuel (NCV) - the file's header names each series.", fuelP);
            Matrix(sb, "Efficiency", "Implied electrical efficiency by [country][cost category], DERIVED from the balance (0 where the country has no such plant).", eff);
            Matrix(sb, "EmissionFactorTPerMwh", "Emission factor by [country][cost category], t CO2 per MWh of electricity, DERIVED (IPCC 2006 defaults over the balance).", ef);
            Matrix(sb, "VomPerMwh", "Variable O&M by [country][cost category], currency per MWh (EIA AEO2023 Table 1).", vom);
            Matrix(sb, "Availability", "Dependable share of installed capacity by [country][cost category] - [AUTHORED-DRAFT] 0.85, the ERAA row billed.", avail);
            Matrix(sb, "MainShare", "The main-activity producers' share of the category's generation by [country][cost category] - EDGAR's 1A1 basis.", main);
            Matrix(sb, "LigniteShare", "Lignite's share of the coal input by [country][cost category] (the coal row; 0 elsewhere).", lig);
            Block(sb, "EtsPerT", "The carbon price the fleet already pays, per country, currency per tonne - the EU ETS 2023 secondary mean for the five (ICAP), 0 for the USA.", ets);
            Block(sb, "NationalPerMarketCurrency", "The country's currency per unit of the market's (EUR for the five, USD for the USA): 1 for the euro members and the USA, the ECB 2023 reference rates for the krona and the zloty - the bridge for a tax line's points, which are the country's currency.", nat);
            Block(sb, "UsdPerMarketCurrency", "The BOOK's dollars per unit of the market's currency - the game keeps every country's book in US dollars - the ECB 2023 reference rate USD/EUR for the five, 1 for the USA; the fiscal layer's stack and ledgers are in the book's dollars through it.", usd);
            var extZone = new List<string>(); var extNb = new List<string>(); var extOut = new List<double>(); var extIn = new List<double>();
            foreach (string[] r in external) { extZone.Add(r[0]); extNb.Add(r[1]); extOut.Add(P(r[2])); extIn.Add(P(r[3])); }
            sb.Append("        /// <summary>Sweden's interconnectors - the zone.</summary>\n");
            sb.Append("        public static readonly string[] ExternalLinkZone = { ").Append(Quote(extZone.ToArray())).Append(" };\n");
            sb.Append("        /// <summary>... the neighbour.</summary>\n");
            sb.Append("        public static readonly string[] ExternalLinkNeighbour = { ").Append(Quote(extNb.ToArray())).Append(" };\n");
            Block(sb, "ExternalLinkOutMw", "Capacity out of Sweden, MW (Svenska kraftnat's capacity-map text).", extOut.ToArray());
            Block(sb, "ExternalLinkInMw", "Capacity into Sweden, MW.", extIn.ToArray());

            // ---- EN-4, the fiscal layer's retail seed ----------------------------------------------------------
            sb.Append("        // ---- EN-4 (2026-09-11): the retail stack's seed - 2023 consumption and price components per customer class\n");
            sb.Append("        public const string RetailDigest = \"").Append(dRetail).Append("\";\n");
            sb.Append("        /// <summary>The customer classes: households (Eurostat band DC; EIA residential) and non-households (band IC; the other EIA sectors).</summary>\n");
            sb.Append("        public static readonly string[] RetailClasses = { ").Append(Quote(RetailClasses)).Append(" };\n");
            var rCons = New2(Countries.Length, RetailClasses.Length); var rSup = New2(Countries.Length, RetailClasses.Length); var rNet = New2(Countries.Length, RetailClasses.Length); var rPol = New2(Countries.Length, RetailClasses.Length);
            var rEnv = New2(Countries.Length, RetailClasses.Length); var rVat = New2(Countries.Length, RetailClasses.Length); var rTot = New2(Countries.Length, RetailClasses.Length);
            for (int i = 0; i < retail.Count; i++)
            {
                int c = i / RetailClasses.Length, k = i % RetailClasses.Length; string[] r = retail[i];
                rCons[c][k] = P(r[2]); rSup[c][k] = P(r[3]); rNet[c][k] = P(r[4]); rPol[c][k] = P(r[5]); rEnv[c][k] = P(r[6]); rVat[c][k] = P(r[7]); rTot[c][k] = P(r[8]);
            }
            Matrix(sb, "RetailConsumptionGwh", "2023 consumption by [country][class], GWh (Eurostat nrg_cb_e; EIA EPA 2.2).", rCons);
            Matrix(sb, "RetailEnergySupply", "The energy-and-supply component per kWh by [country][class] (Eurostat NRG_SUP; the USA's all-in price) - the dispatch's wholesale plus a FITTED supply margin at the seed.", rSup);
            Matrix(sb, "RetailNetwork", "The network component per kWh (Eurostat NETC; 0 for the USA, BILLED).", rNet);
            Matrix(sb, "RetailPolicy", "The policy levies per kWh - renewable + capacity + other charges (Eurostat TAX_RNW + TAX_CAP + OTH).", rPol);
            Matrix(sb, "RetailTaxEnv", "Environmental and nuclear taxes per kWh (Eurostat TAX_ENV + TAX_NUC).", rEnv);
            Matrix(sb, "RetailVat", "VAT per kWh at the seed (Eurostat VAT); the runtime carries the rate it implies on the pre-VAT stack.", rVat);
            Matrix(sb, "RetailTotal", "The all-in price per kWh (the components' sum).", rTot);
            // EN-5 (2026-09-11): the pass-through's one sourced factor
            sb.Append("        public const string PriceIndexWeightDigest = \"").Append(dWeights).Append("\";\n");
            var wPm = new double[Countries.Length]; for (int i = 0; i < weights.Count; i++) { wPm[i] = P(weights[i][1]); }
            Block(sb, "RetailPriceIndexWeightPerMille", "Electricity's weight in the consumer price index per country, per mille of the all-items basket, 2023 - Eurostat prc_hicp_inw COICOP CP0451 for the five, the BLS CPI-U relative importance (December 2023) for the USA; the household retail price's change relative to the general price level times this weight is the year's pass-through to Inflation (EnergyPassThrough).", wPm);
            sb.Append("    }\n}\n");
            return sb.ToString();
        }

        private static string Quote(string[] items) { var q = new List<string>(); foreach (string s in items) { q.Add("\"" + s + "\""); } return string.Join(", ", q); }
        private static string N(double v) => v.ToString("0.####", CultureInfo.InvariantCulture);

        private static void Block(StringBuilder sb, string name, string doc, double[] values)
        {
            sb.Append("        /// <summary>").Append(doc).Append("</summary>\n");
            sb.Append("        public static readonly double[] ").Append(name).Append(" = { ");
            for (int i = 0; i < values.Length; i++) { sb.Append(N(values[i])).Append(i + 1 < values.Length ? ", " : ""); }
            sb.Append(" };\n\n");
        }

        private static void Matrix(StringBuilder sb, string name, string doc, double[][] values)
        {
            sb.Append("        /// <summary>").Append(doc).Append("</summary>\n");
            sb.Append("        public static readonly double[][] ").Append(name).Append(" =\n        {\n");
            foreach (double[] row in values)
            {
                sb.Append("            new double[] { ");
                for (int i = 0; i < row.Length; i++) { sb.Append(N(row[i])).Append(i + 1 < row.Length ? ", " : ""); }
                sb.Append(" },\n");
            }
            sb.Append("        };\n\n");
        }

        private static void Cube(StringBuilder sb, string name, string doc, double[][][] values)
        {
            sb.Append("        /// <summary>").Append(doc).Append("</summary>\n");
            sb.Append("        public static readonly double[][][] ").Append(name).Append(" =\n        {\n");
            foreach (double[][] plane in values)
            {
                sb.Append("            new double[][]\n            {\n");
                foreach (double[] row in plane)
                {
                    sb.Append("                new double[] { ");
                    for (int i = 0; i < row.Length; i++) { sb.Append(N(row[i])).Append(i + 1 < row.Length ? ", " : ""); }
                    sb.Append(" },\n");
                }
                sb.Append("            },\n");
            }
            sb.Append("        };\n\n");
        }
    }
}
