using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using PoliSim.Data;
using PoliSim.Elections;
using PoliSim.Simulation;
using UnityEngine;
using Debug = UnityEngine.Debug;

namespace PoliSim.EditorTools
{
    /// <summary>
    /// §681: **THE ENTRANT LAYER, MEASURED AND GATED.** Every share printed is a PERCENTAGE OF VALID VOTES and every vector printed sums to 100
    /// (asserted). (1) THE PROPERTY: the share mechanism as it stood - `PreferenceModel` over the vote model's compatibility, before the layer -
    /// draws a new option from all parties by size: each party's loss over its share, printed, with their spread. (2) THE FAMILIES: every value
    /// in `PartyFamilies` read back from the fetched CHES CSV. (3) INERT: with no entrant the layer returns the very array it was given, on
    /// every country's live prediction. (4) THE GATES: a twin at M's position (a created Grassroots party placed on M) draws most of its vote from
    /// M and M's family; a Grassroots newcomer at (5, 5) that does not campaign lands inside the range real first-time parties achieved in their
    /// first Riksdag election - Valmyndigheten's own results, generated by `Tools/first_time_parties.pl` into
    /// `ElectionsData/sweden/first_time_parties.tsv`, read here, never typed.
    /// </summary>
    public static class EntrantLayerDiagnostic
    {
        private static string F(string f, params object[] a) => string.Format(CultureInfo.InvariantCulture, f, a);

        /// <summary>A vector of fractions printed as percentages of valid votes, with its sum - asserted to be 100.</summary>
        private static string Pct(IReadOnlyList<string> keys, double[] shares, ref bool sumsTo100)
        {
            double sum = shares.Sum() * 100.0;
            if (Math.Abs(sum - 100.0) > 1e-6) { sumsTo100 = false; }
            return string.Join(" ", keys.Select((k, i) => F("{0} {1:0.00}", k, shares[i] * 100.0))) + F(" (% of valid votes; sum {0:0.000})", sum);
        }

        public static void Run()
        {
            CheckExit.ArmLogFold();
            var sb = new StringBuilder("=== EntrantLayerDiagnostic (§681): awareness and family-grouped substitution ===\n");
            int failures = 0;
            bool sums = true;
            void Check(bool ok, string what) { if (!ok) { failures++; } sb.Append(ok ? "    ok        " : "    FAIL      ").Append(what).Append('\n'); }
            using IDisposable epoch = SimulationManager.EpochScope();
            using IDisposable created = CreatedParties.Scope();
            try
            {
                const CountryId se = CountryId.Sweden;
                WorldClock.ApplyStart(se);
                CreatedParties.Clear();
                PoliticalParty[] real = PartySystems.RealRoster(se);

                // (2) the families against the file
                string csv = Path.Combine("ElectionsData", "positions", "raw", "CHES_2024_final_v2.csv");
                var fileFamily = new Dictionary<string, int>();
                foreach (string line in File.ReadAllLines(csv).Skip(1))
                {
                    string[] f = line.Split(',');
                    if (f.Length > 3 && int.TryParse(f[0], out int c) && int.TryParse(f[3], out int fam)) { fileFamily[c + "/" + f[2].Trim('"')] = fam; }
                }
                var wrong = PartyFamilies.Table.Where(t => !fileFamily.TryGetValue(t.ChesCountry + "/" + t.ChesParty, out int fam) || fam != t.Family).Select(t => t.Key).ToList();
                Check(wrong.Count == 0 && PartyFamilies.Table.Count > 0, F("every family in the table is the CHES 2024 file's ({0} keys read back; {1})", PartyFamilies.Table.Count, wrong.Count == 0 ? "none differs" : "differs: " + string.Join(", ", wrong)));

                // (3) inert: no entrant, the very array
                bool inert = true;
                foreach (CountryId c in new[] { CountryId.Sweden, CountryId.Germany, CountryId.Poland, CountryId.Italy })
                {
                    if (!NationalElection.TryCompatibility(c, out string[] keys, out double[] compat, out double[] prior, out double[] loyalty)) { continue; }
                    double[] pref = PreferenceModel.Preference(compat, prior, loyalty);
                    bool hasEntrant = prior.Any(EntrantLayer.IsEntrant);
                    double[] after = EntrantLayer.Apply(pref, prior, PartyFamilies.For(c, keys), null, null);
                    sb.Append(F("    measured  {0}: {1} parties, entrant(s): {2}\n", c, keys.Length, hasEntrant ? string.Join(" ", keys.Where((k, i) => EntrantLayer.IsEntrant(prior[i]))) : "none"));
                    if (!hasEntrant && !ReferenceEquals(after, pref)) { inert = false; }
                }
                Check(inert, "inert: a live prediction with no entrant is returned as the very array it was (every country the model predicts)");

                // (1) the property, on the mechanism as it stood (grouping 0): the twin's draw from each party over that party's share
                CreatedParty Make(string key) { var p = new CreatedParty { Country = se, Key = key, Name = "Testpartiet " + key, LeaderName = "T" }; p.ApplyOrigin(PartyOrigin.Grassroots); return p; }
                NationalElection.TryCompatibility(se, out string[] k0, out double[] c0, out double[] p0, out double[] l0);
                double[] base0 = PreferenceModel.Preference(c0, p0, l0);
                sb.Append("    measured  the chamber as predicted, no newcomer: ").Append(Pct(k0, base0, ref sums)).Append('\n');
                int m = Array.IndexOf(k0, "M");
                var twin = Make("NM"); twin.PlaceOn(real[Array.FindIndex(real, p => p.Abbrev == "M")]);
                CreatedParties.TryRegister(twin, real, out _);
                NationalElection.TryCompatibility(se, out string[] k1, out double[] c1, out double[] p1, out double[] l1);
                double[] plain = PreferenceModel.Preference(c1, p1, l1);
                var ratios = new List<string>();
                double lo = double.MaxValue, hi = double.MinValue;
                for (int i = 0; i < k0.Length; i++)
                {
                    double loss = base0[i] - plain[i], r = loss / base0[i];
                    lo = Math.Min(lo, r); hi = Math.Max(hi, r);
                    ratios.Add(F("{0} {1:0.00}/{2:0.00} = {3:0.0}%", k0[i], loss * 100.0, base0[i] * 100.0, r * 100.0));
                }
                sb.Append("    measured  the mechanism as it stood (no layer), M's twin at its full share: ").Append(Pct(k1, plain, ref sums)).Append('\n');
                sb.Append("    measured  each party's loss over its share (pp over %): ").Append(string.Join(", ", ratios)).Append(F(" - spread {0:0.0} to {1:0.0}%\n", lo * 100.0, hi * 100.0));
                Check(hi - lo < 0.5 * hi, F("the proportional-substitution property holds on the mechanism as it stood: every party loses {0:0.0}-{1:0.0}% of its own share - by size, not by nearness (M, the twin's neighbour, loses {2:0.0}%)", lo * 100.0, hi * 100.0, (base0[m] - plain[m]) / base0[m] * 100.0));

                // (4a) the twin at M with the layer: most of its vote from M and M's family
                int[] fam1 = PartyFamilies.For(se, k1);
                int twinIndex = Array.IndexOf(k1, "NM");
                // the twin at FULL awareness (null = every party at 1): the gate is where it draws from, not how much
                double[] layered = EntrantLayer.Apply(plain, p1, fam1, null, EntrantLayer.GroupingOf(se, k1));   // the twin is a created party: it carries the grouping
                sb.Append(F("    measured  the layer, the twin at full awareness, grouping {0:0.00} (family {1}, M's {2}): ", EntrantLayer.GroupingStrength, fam1[twinIndex], fam1[m])).Append(Pct(k1, layered, ref sums)).Append('\n');
                double twinShare = layered[twinIndex];
                double fromFamily = 0.0;
                var draws = new List<string>();
                double drawn = 0.0;
                for (int i = 0; i < k0.Length; i++)
                {
                    double d = base0[i] - layered[i];   // what the party lost to the twin, against the chamber without it
                    drawn += d;
                    if (fam1[i] == fam1[twinIndex] && fam1[i] >= 0) { fromFamily += d; }
                    draws.Add(F("{0} {1:+0.00;-0.00}", k0[i], -d * 100.0));
                }
                sb.Append("    measured  where the twin's vote comes from (pp): ").Append(string.Join(", ", draws)).Append(F(" - {0:0.0}% of it from M's family\n", drawn > 0 ? fromFamily / drawn * 100.0 : 0.0));
                Check(drawn > 0 && fromFamily / drawn > 0.5, F("a twin at M's position draws most of its vote from M and M's family: {0:0.0}% of its {1:0.00}% (grouping {2:0.00})", fromFamily / drawn * 100.0, twinShare * 100.0, EntrantLayer.GroupingStrength));

                // (4b) a Grassroots newcomer at (5, 5) that does not campaign, in the idle prediction the game makes
                CreatedParties.Clear();
                var grass = Make("GRS"); grass.LrEcon = 5f; grass.Galtan = 5f;
                CreatedParties.TryRegister(grass, real, out _);
                NationalElection.TryPredictShares(se, out Dictionary<string, double> idle);
                string[] kIdle = idle.Keys.ToArray();
                double[] vIdle = kIdle.Select(k => idle[k]).ToArray();
                sb.Append(F("    measured  a Grassroots newcomer at (5, 5), no campaign, awareness {0:0.00} (Recognition {1}): ", PartyOrigins.Pip(PartyOrigins.Awareness, grass.Recognition), grass.Recognition)).Append(Pct(kIdle, vIdle, ref sums)).Append('\n');
                string tsv = Path.Combine("ElectionsData", "sweden", "first_time_parties.tsv");
                var first = File.ReadAllLines(tsv).Skip(1).Select(l => l.Split('\t')).Where(f => f.Length > 4 && double.TryParse(f[4], NumberStyles.Float, CultureInfo.InvariantCulture, out _))
                    .Select(f => (Year: f[0], Party: f[2], Pct: double.Parse(f[4], CultureInfo.InvariantCulture))).ToList();
                double min = first.Min(x => x.Pct), max = first.Max(x => x.Pct);
                var top = first.OrderByDescending(x => x.Pct).First();
                double grs = idle["GRS"] * 100.0;
                Check(first.Count > 0 && grs >= min && grs <= max,
                    F("a Grassroots newcomer that does not campaign lands at {0:0.00}% of valid votes, inside the range {1} real first-time parties achieved in their first Riksdag election 2006-2026, {2:0.00}-{3:0.00}% (Valmyndigheten; the highest {4} {5})", grs, first.Count, min, max, top.Party, top.Year));
            }
            catch (Exception ex) { failures++; sb.Append("    THREW: " + ex.GetType().Name + ": " + ex.Message + "\n" + ex.StackTrace + "\n"); }
            finally { CreatedParties.Clear(); NationalElection.TryPredictShares(CountryId.Sweden, out _); }

            if (!sums) { failures++; sb.Append("    FAIL      a printed vector did not sum to 100\n"); }
            else { sb.Append("    ok        every vector printed sums to 100 (% of valid votes)\n"); }
            if (failures > 0) { Debug.LogError($"ENTRANT LAYER: {failures} failure(s).\n{sb}"); CheckExit.Finish(1); return; }
            Debug.Log(sb.ToString());
            CheckExit.Finish(0);
        }
    }
}
