using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using PoliSim.Data;
using UnityEditor;
using UnityEngine;
using Debug = UnityEngine.Debug;

namespace PoliSim.EditorTools
{
    /// <summary>
    /// **T-3, form A (Elias, 2026-09-15): the identity's G is the sourced final-consumption share of GDP at the seed, grown with the lines.**
    /// Turns `MacroData/government_consumption_2023.csv` - derived by `Tools/govcons_prep.pl` from Eurostat nama_10_gdp (P3_S13 over B1GQ,
    /// national currency) for the five and BEA's NIPA flat file (A955RC over A191RC) for the USA, every file under
    /// `PoliSim-captures/sources/govcons/` listed by digest in `MacroData/README.md` - into a generated table of one share per country.
    /// DERIVED: no figure is typed here or there.
    ///
    /// <para><b>Refuses to emit</b> if a country is missing, a share is not a number between 0 and 100, or the header is not the one this
    /// generator reads. The source's SHA-256 is emitted as data so `GeneratedCatalogCheck` holds the table to the file; the USA's row carries
    /// its perimeter note (general government against the model's federal lines) as data too.</para>
    /// </summary>
    public static class GovernmentConsumptionCatalogGenerator
    {
        public const string SourceRelative = "MacroData/government_consumption_2023.csv";
        private const string OutputRelative = "Assets/Scripts/Data/Generated/GovernmentConsumptionData.cs";
        private const string Header = "geo,country,source,consumption_series,gdp_series,year,consumption,gdp,unit,share_pct,published_pct,published_source,federal_share_pct,flag";

        private static readonly (CountryId Id, string Geo)[] Countries =
        {
            (CountryId.USA, "US"), (CountryId.Sweden, "SE"), (CountryId.Germany, "DE"), (CountryId.France, "FR"), (CountryId.Italy, "IT"), (CountryId.Poland, "PL"),
        };

        [MenuItem("PoliSim/Generate Government Consumption Catalog")]
        public static void Generate() => GenerateInternal();

        /// <summary>Batch entry: generates and exits 0, or exits 1 having refused.</summary>
        public static void GenerateBatch() => EditorApplication.Exit(GenerateInternal() ? 0 : 1);

        private static bool GenerateInternal()
        {
            string root = Directory.GetCurrentDirectory();
            string path = Path.Combine(root, SourceRelative.Replace('/', Path.DirectorySeparatorChar));
            if (!File.Exists(path)) { Debug.LogError($"GOVCONSCATALOG: {SourceRelative} is not on disk - run Tools/govcons_prep.pl first."); return false; }
            string[] lines = File.ReadAllText(path).Replace("\r", "").Split('\n');
            var failures = new List<string>();
            if (lines.Length == 0 || lines[0] != Header) { failures.Add($"the header is not '{Header}'"); }
            var share = new Dictionary<CountryId, double>(); var source = new Dictionary<CountryId, string>(); var flag = new Dictionary<CountryId, string>();
            var federal = new Dictionary<CountryId, double>();
            var byGeo = new Dictionary<string, string[]>(StringComparer.Ordinal);
            for (int i = 1; i < lines.Length; i++)
            {
                if (lines[i].Trim().Length == 0) { continue; }
                string[] p = lines[i].Split(',');
                if (p.Length != 14) { failures.Add($"line {i + 1}: {p.Length} columns, 14 expected"); continue; }
                byGeo[p[0]] = p;
            }
            foreach ((CountryId id, string geo) in Countries)
            {
                if (!byGeo.TryGetValue(geo, out string[] p)) { failures.Add($"{id}: no row for {geo}"); continue; }
                if (!double.TryParse(p[9], NumberStyles.Float, CultureInfo.InvariantCulture, out double s) || !(s > 0.0) || !(s < 100.0)) { failures.Add($"{id}: share '{p[9]}' is not a number between 0 and 100"); continue; }
                share[id] = s; source[id] = $"{p[2]} {p[3]} / {p[4]}, {p[5]}"; flag[id] = p[13];
                if (p[12].Length > 0 && double.TryParse(p[12], NumberStyles.Float, CultureInfo.InvariantCulture, out double f)) { federal[id] = f; }
            }
            if (failures.Count > 0)
            {
                Debug.LogError("GOVCONSCATALOG: REFUSING TO EMIT - a partial table would leave a country's G on no source.\n  " + string.Join("\n  ", failures));
                return false;
            }
            string digest = ElectionsDataCatalogGenerator.Sha256Of(File.ReadAllBytes(path));
            var sb = new StringBuilder();
            sb.Append("// GENERATED by PoliSim.EditorTools.GovernmentConsumptionCatalogGenerator. DO NOT EDIT BY HAND.\n//\n");
            sb.Append("// T-3, form A: general government final consumption expenditure over GDP, 2023, current prices - the identity's G at the seed.\n");
            sb.Append("// The five: Eurostat nama_10_gdp P3_S13 / B1GQ (CP_MNAC). The USA: BEA NIPA A955RC / A191RC - general government, against the\n");
            sb.Append("// model's federal lines; the World Bank's NE.CON.GOVT.ZS is BEA's own ratio, so the USA's reading is one source in two copies.\n//\n");
            sb.Append("// SHA-256 (").Append(SourceRelative).Append("): ").Append(digest).Append('\n');
            sb.Append("\nusing System.Collections.Generic;\n\nnamespace PoliSim.Data.Generated\n{\n    public static class GovernmentConsumptionData\n    {\n");
            sb.Append("        public const string SourcePath = \"").Append(SourceRelative).Append("\";\n");
            sb.Append("        public const string SourceDigest = \"").Append(digest).Append("\";\n");
            sb.Append("        public const int Year = 2023;\n\n");
            sb.Append("        /// <summary>General government final consumption expenditure, per cent of GDP, 2023 - the file's share_pct, unrounded.</summary>\n");
            sb.Append("        public static readonly Dictionary<CountryId, float> SharePct = new Dictionary<CountryId, float>\n        {\n");
            foreach ((CountryId id, _) in Countries) { sb.Append("            { CountryId.").Append(id).Append(", ").Append(share[id].ToString("0.######", CultureInfo.InvariantCulture)).Append("f },\n"); }
            sb.Append("        };\n\n");
            sb.Append("        /// <summary>Each share's source, series and year, from the file.</summary>\n");
            sb.Append("        public static readonly Dictionary<CountryId, string> Source = new Dictionary<CountryId, string>\n        {\n");
            foreach ((CountryId id, _) in Countries) { sb.Append("            { CountryId.").Append(id).Append(", \"").Append(source[id].Replace("\"", "'")).Append("\" },\n"); }
            sb.Append("        };\n\n");
            sb.Append("        /// <summary>The publisher's provisional flag on the figures ('p'), empty where none.</summary>\n");
            sb.Append("        public static readonly Dictionary<CountryId, string> Flag = new Dictionary<CountryId, string>\n        {\n");
            foreach ((CountryId id, _) in Countries) { sb.Append("            { CountryId.").Append(id).Append(", \"").Append(flag[id]).Append("\" },\n"); }
            sb.Append("        };\n\n");
            sb.Append("        /// <summary>The USA's federal-only consumption share (BEA A957RC over A191RC), the perimeter its lines sit on; no other row carries one.</summary>\n");
            sb.Append("        public static readonly Dictionary<CountryId, float> FederalSharePct = new Dictionary<CountryId, float>\n        {\n");
            foreach (KeyValuePair<CountryId, double> e in federal) { sb.Append("            { CountryId.").Append(e.Key).Append(", ").Append(e.Value.ToString("0.######", CultureInfo.InvariantCulture)).Append("f },\n"); }
            sb.Append("        };\n    }\n}\n");
            File.WriteAllText(Path.Combine(root, OutputRelative), sb.ToString(), new UTF8Encoding(false));
            AssetDatabase.Refresh();
            Debug.Log($"GOVCONSCATALOG: {share.Count} shares generated into {OutputRelative} from {SourceRelative} ({digest}).");
            return true;
        }
    }
}
