using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using PoliSim.Data;
using PoliSim.Simulation;
using UnityEngine;

namespace PoliSim.EditorTools
{
    /// <summary>
    /// P4-C1 (2026-09-04) - THE LEVER MAP, MEASURED. Enumerates every macro quantity the model holds and,
    /// for each, which dials and which laws reach it - generated by probing, never transcribed from a
    /// reading of the code. The record it writes (`LEVER_MAP.md` at the repo root) is the coverage plan
    /// for P4-C3: the unreached set is the list of quantities no law and no dial moves today.
    ///
    /// <para><b>How a reach is measured.</b> One baseline run and one probe run per lever, both from the
    /// same seed on a fresh world, both driven the way SimulationTestRunner and TrajectoryBaselineDump
    /// drive (AdvanceDay x DaysPerTurn, then AdvanceTurn) for <see cref="Horizon"/> turns. A dial probe
    /// hands the player's country ONE PolicyDecision override on the first turn - the real per-turn
    /// path, the one every bill's effects go through - and None afterwards; a law probe enacts one law
    /// through SimulationManager's own private ApplyLawBillEffects (LawCompositionDiagnostic's
    /// reflection idiom) before the first turn. A quantity is REACHED by a lever when its value after
    /// the horizon differs from the baseline's by more than float noise (relative 1e-6). Every quantity
    /// is read from the same object the game reads it from: EconomyState's public floats by
    /// reflection, the Country's parameter floats by reflection (its own levers, their baselines and
    /// trackers excluded by name pattern, since a lever reaching itself is not a reach), each sector's
    /// three figures, the fund's assets, the zone's rate, and the Taylor rule's suggestion.</para>
    ///
    /// <para><b>What the map cannot say.</b> A reach is a non-zero difference over the horizon, not a
    /// magnitude judgement - a quantity moved by 1e-5 is reached; whether it is reached USEFULLY is
    /// P4-C3's question. And the central bank's parameters (the inflation target, the neutral real
    /// rate, the two gap weights) are constants and a per-country constant function: they cannot be
    /// reached by anything, which the map states rather than probes.</para>
    ///
    /// Run: `Unity.exe -batchmode -nographics -projectPath &lt;path&gt; -executeMethod
    /// PoliSim.EditorTools.LeverMapDump.Run -logFile &lt;path&gt; [-levermapout=&lt;file&gt;]`
    /// </summary>
    public static class LeverMapDump
    {
        private const int Seed = 777;                 // the harness's seed, TrajectoryBaselineDump's first
        private const int Horizon = 8;                // eight turns - two years, so the slow couplings register
        private const CountryId Probed = CountryId.Sweden;   // the player's country in every playtest
        private const float NoiseRelative = 1e-6f;
        private const float DialProbeLevel = 80f;     // 0-100 dials are pushed from their standing to 80
        private const float SpendingLineProbePercent = 10f;
        private const float TaxProbePoints = 5f;
        private const float TariffProbePoints = 5f;
        private const float RateProbePoints = 1f;
        private const float MinimumWageProbePoints = 10f;   // Kaitz points
        private const float PaidLeaveProbeWeeks = 20f;
        private const float DrawdownProbePercentOfGdp = 2f;

        private sealed class Quantity
        {
            public string Group;
            public string Name;
            public Func<Country, float> Read;
        }

        private sealed class Lever
        {
            public string Family;
            public string Name;
            public Action<SimulationManager, Country, PolicyDecision> Arm;   // fills the first turn's decision or mutates the country before it
            public string[] ViaDials;   // laws: the dials the law moves (from DialDeltas); dials: null
        }

        public static void Run()
        {
            CheckExit.ArmLogFold();
            string outPath = Arg("-levermapout=", Path.Combine(Application.dataPath, "..", "LEVER_MAP.md"));
            List<Quantity> quantities = BuildQuantities();
            List<Lever> levers = BuildLevers();
            Debug.Log($"LEVERMAP: {quantities.Count} quantities, {levers.Count} levers, horizon {Horizon} turns, seed {Seed}, {Probed}.");

            float[] baseline = RunOne(null, quantities, out _);
            var reach = new Dictionary<string, List<string>>();   // quantity -> lever names
            var leverReach = new Dictionary<string, List<string>>();
            foreach (Quantity q in quantities) { reach[q.Name] = new List<string>(); }
            foreach (Lever lever in levers)
            {
                float[] probed = RunOne(lever, quantities, out bool armed);
                var hit = new List<string>();
                if (armed)
                {
                    for (int i = 0; i < quantities.Count; i++)
                    {
                        float tolerance = NoiseRelative * Mathf.Max(1f, Mathf.Abs(baseline[i]));
                        if (Mathf.Abs(probed[i] - baseline[i]) > tolerance)
                        {
                            hit.Add(quantities[i].Name);
                            reach[quantities[i].Name].Add(lever.Name);
                        }
                    }
                }
                leverReach[lever.Name] = armed ? hit : null;
            }

            string map = Render(quantities, levers, reach, leverReach);
            File.WriteAllText(outPath, map);
            int unreached = quantities.Count(q => reach[q.Name].Count == 0);
            Debug.Log($"LEVERMAP: wrote {Path.GetFullPath(outPath)} - {quantities.Count - unreached} of {quantities.Count} quantities reached by at least one lever, {unreached} UNREACHED (the coverage plan).");
            CheckExit.Finish(0);
        }

        private static float[] RunOne(Lever lever, List<Quantity> quantities, out bool armed)
        {
            armed = true;
            SimulationRandom.Seed(Seed);
            World world = WorldFactory.CreateDefault();
            var go = new GameObject("LEVERMAP");
            try
            {
                SimulationManager sim = go.AddComponent<SimulationManager>();
                sim.SetWorld(world);
                Country country = world.GetCountry(Probed);
                var decisions = new Dictionary<CountryId, PolicyDecision>();
                foreach (Country c in world.Countries) { decisions[c.Id] = PolicyDecision.None(); }
                if (lever != null)
                {
                    PolicyDecision first = PolicyDecision.None();
                    try { lever.Arm(sim, country, first); }
                    catch (NotSupportedException) { armed = false; }
                    decisions[Probed] = first;
                }
                for (int turn = 1; turn <= Horizon; turn++)
                {
                    for (int day = 0; day < SimulationManager.DaysPerTurn; day++) { sim.AdvanceDay(); }
                    sim.AdvanceTurn(decisions);
                    decisions[Probed] = PolicyDecision.None();
                }
                var values = new float[quantities.Count];
                for (int i = 0; i < quantities.Count; i++) { values[i] = quantities[i].Read(country); }
                return values;
            }
            finally
            {
                UnityEngine.Object.DestroyImmediate(go);
            }
        }

        // ---- the quantities -------------------------------------------------------------------------

        private static readonly string[] CountryLeverPatterns =
        {
            "Base", "Baseline", "Level", "Override", "Applied", "MinimumWagePercentOfMedian", "PaidFamilyLeaveWeeks",
            "SentencingSeverity", "BaseTariffRate", "PartyApprovalRating"
        };

        private static List<Quantity> BuildQuantities()
        {
            var list = new List<Quantity>();
            FieldInfo[] stateFields = typeof(EconomyState).GetFields(BindingFlags.Public | BindingFlags.Instance)
                .Where(f => f.FieldType == typeof(float)).OrderBy(f => f.Name, StringComparer.Ordinal).ToArray();
            foreach (FieldInfo f in stateFields)
            {
                FieldInfo captured = f;
                list.Add(new Quantity { Group = "EconomyState", Name = "EconomyState." + f.Name, Read = c => (float)captured.GetValue(c.State) });
            }
            FieldInfo[] countryFields = typeof(Country).GetFields(BindingFlags.Public | BindingFlags.Instance)
                .Where(f => f.FieldType == typeof(float) && !CountryLeverPatterns.Any(p => f.Name.Contains(p)))
                .OrderBy(f => f.Name, StringComparer.Ordinal).ToArray();
            foreach (FieldInfo f in countryFields)
            {
                FieldInfo captured = f;
                list.Add(new Quantity { Group = "Country parameter", Name = "Country." + f.Name, Read = c => (float)captured.GetValue(c) });
            }
            foreach (SectorType type in Enum.GetValues(typeof(SectorType)))
            {
                SectorType t = type;
                list.Add(new Quantity { Group = "Sector", Name = $"Sector.OutputShareOfGdp ({t})", Read = c => SectorOf(c, t)?.OutputShareOfGdp ?? 0f });
                list.Add(new Quantity { Group = "Sector", Name = $"Sector.EmploymentShare ({t})", Read = c => SectorOf(c, t)?.EmploymentShare ?? 0f });
                list.Add(new Quantity { Group = "Sector", Name = $"Sector.SectorMetric ({t})", Read = c => SectorOf(c, t)?.SectorMetric ?? 0f });
            }
            list.Add(new Quantity { Group = "Fund", Name = "SovereignWealthFund.TotalAssets", Read = c => c.SovereignWealthFund?.TotalAssets ?? 0f });
            list.Add(new Quantity { Group = "Central bank", Name = "CurrencyZone.InterestRate", Read = c => c.CurrencyZone?.InterestRate ?? 0f });
            list.Add(new Quantity { Group = "Central bank", Name = "TaylorRule.GetSuggestedInterestRate", Read = c => TaylorRule.GetSuggestedInterestRate(c) });
            list.Add(new Quantity { Group = "Central bank", Name = "TaylorRule.GetOutputGapPercent", Read = c => TaylorRule.GetOutputGapPercent(c) });
            list.Add(new Quantity { Group = "Central bank", Name = "TaylorRule.GetUnemploymentGapPercent", Read = c => TaylorRule.GetUnemploymentGapPercent(c) });
            return list;
        }

        private static Sector SectorOf(Country c, SectorType t) => c.Sectors.Find(s => s.Type == t);

        // ---- the levers -----------------------------------------------------------------------------

        private static List<Lever> BuildLevers()
        {
            var list = new List<Lever>();
            // Budget lines: the per-line percentage change the Budget bill carries.
            foreach (SpendingCategory cat in Enum.GetValues(typeof(SpendingCategory)))
            {
                SpendingCategory c0 = cat;
                list.Add(new Lever { Family = "Budget line", Name = $"Budget line {c0} ({SpendingLineProbePercent:+0} %)", Arm = (sim, c, d) =>
                {
                    if (!c.SpendingLines.Exists(l => l.Category == c0)) { throw new NotSupportedException(); }
                    d.SpendingLineChanges[c0] = SpendingLineProbePercent;
                } });
            }
            foreach (TaxType tax in Enum.GetValues(typeof(TaxType)))
            {
                TaxType t0 = tax;
                list.Add(new Lever { Family = "Tax rate", Name = $"Tax {t0} ({TaxProbePoints:+0} pts)", Arm = (sim, c, d) =>
                {
                    TaxLine line = c.TaxLines.Find(l => l.Type == t0);
                    if (line == null) { throw new NotSupportedException(); }
                    d.TaxRateOverrides[t0] = line.Rate + TaxProbePoints;
                } });
            }
            foreach (WelfareProgramType w in Enum.GetValues(typeof(WelfareProgramType)))
            {
                WelfareProgramType w0 = w;
                list.Add(new Lever { Family = "Welfare generosity", Name = $"Welfare {w0} (to {DialProbeLevel:0})", Arm = (sim, c, d) =>
                {
                    if (!c.WelfarePrograms.Exists(p => p.Type == w0 && p.IsImplemented)) { throw new NotSupportedException(); }
                    d.WelfareGenerosityOverrides[w0] = DialProbeLevel;
                } });
            }
            list.Add(new Lever { Family = "Central bank", Name = $"Policy rate ({RateProbePoints:+0} pt)", Arm = (sim, c, d) => d.InterestRateChange = RateProbePoints });
            list.Add(new Lever { Family = "Trade", Name = $"Base tariff ({TariffProbePoints:+0} pts)", Arm = (sim, c, d) => d.TariffRateChange = TariffProbePoints });
            list.Add(new Lever { Family = "Trade", Name = $"Partner tariff override, first partner (+{TariffProbePoints * 2:0} pts)", Arm = (sim, c, d) =>
            {
                if (c.TradePartners.Count == 0) { throw new NotSupportedException(); }
                d.PartnerTariffOverrides[c.TradePartners[0].PartnerId] = c.BaseTariffRate + TariffProbePoints * 2f;
            } });
            // Labour six - the standing dial plus a step, so a dial already at 50 and one at 30 both move.
            list.Add(new Lever { Family = "Labour dial", Name = $"Minimum Wage ({MinimumWageProbePoints:+0} Kaitz)", Arm = (sim, c, d) =>
            {
                if (!c.MinimumWageImplemented) { throw new NotSupportedException(); }
                d.MinimumWageOverride = c.MinimumWagePercentOfMedian + MinimumWageProbePoints;
            } });
            list.Add(new Lever { Family = "Labour dial", Name = $"Paid Family Leave ({PaidLeaveProbeWeeks:+0} weeks)", Arm = (sim, c, d) => d.PaidFamilyLeaveWeeksOverride = c.PaidFamilyLeaveWeeks + PaidLeaveProbeWeeks });
            list.Add(new Lever { Family = "Labour dial", Name = "Overtime Regulation (to 80)", Arm = (sim, c, d) => d.OvertimeRegulationOverride = DialProbeLevel });
            list.Add(new Lever { Family = "Labour dial", Name = "Retraining Programs (to 80)", Arm = (sim, c, d) => d.RetrainingProgramOverride = DialProbeLevel });
            list.Add(new Lever { Family = "Labour dial", Name = "Family Policy (to 80)", Arm = (sim, c, d) => d.FamilyPolicyOverride = DialProbeLevel });
            list.Add(new Lever { Family = "Labour dial", Name = "Immigration Policy (to 80)", Arm = (sim, c, d) => d.ImmigrationPolicyOverride = DialProbeLevel });
            // Crime six.
            list.Add(new Lever { Family = "Crime dial", Name = "Police Funding (to 80)", Arm = (sim, c, d) => d.PoliceFundingOverride = DialProbeLevel });
            list.Add(new Lever { Family = "Crime dial", Name = "Sentencing Severity (to 80)", Arm = (sim, c, d) => d.SentencingSeverityOverride = DialProbeLevel });
            list.Add(new Lever { Family = "Crime dial", Name = "Bail Reform (to 80)", Arm = (sim, c, d) => d.BailReformOverride = DialProbeLevel });
            list.Add(new Lever { Family = "Crime dial", Name = "Drug Policy (to 80)", Arm = (sim, c, d) => d.DrugPolicyOverride = DialProbeLevel });
            list.Add(new Lever { Family = "Crime dial", Name = "Judicial Funding (to 80)", Arm = (sim, c, d) => d.JudicialFundingOverride = DialProbeLevel });
            list.Add(new Lever { Family = "Crime dial", Name = "Border Enforcement (to 80)", Arm = (sim, c, d) => d.BorderEnforcementOverride = DialProbeLevel });
            // Sector five, per sector.
            foreach (SectorType type in Enum.GetValues(typeof(SectorType)))
            {
                SectorType t = type;
                list.Add(new Lever { Family = "Sector dial", Name = $"{t} Subsidy (to 80)", Arm = (sim, c, d) => d.SectorSubsidyOverrides[t] = DialProbeLevel });
                list.Add(new Lever { Family = "Sector dial", Name = $"{t} Regulation (to 80)", Arm = (sim, c, d) => d.SectorRegulationOverrides[t] = DialProbeLevel });
                list.Add(new Lever { Family = "Sector dial", Name = $"{t} Tax Credits (to 80)", Arm = (sim, c, d) => d.SectorTaxCreditOverrides[t] = DialProbeLevel });
                list.Add(new Lever { Family = "Sector dial", Name = $"{t} Research Grants (to 80)", Arm = (sim, c, d) => d.SectorResearchGrantsOverrides[t] = DialProbeLevel });
                list.Add(new Lever { Family = "Sector dial", Name = $"{t} Nationalization / Deregulation (to 80)", Arm = (sim, c, d) => d.SectorDeregulationNationalizationOverrides[t] = DialProbeLevel });
            }
            // The fund's six and the drawdown.
            list.Add(new Lever { Family = "Fund", Name = "Fund contribution rate (+1 pt)", Arm = (sim, c, d) => { RequireFund(c); d.SwfContributionRateOverride = c.SovereignWealthFund.ContributionRatePercent + 1f; } });
            list.Add(new Lever { Family = "Fund", Name = "Fund domestic allocation (to 80)", Arm = (sim, c, d) => { RequireFund(c); d.SwfDomesticAllocationOverride = DialProbeLevel; } });
            list.Add(new Lever { Family = "Fund", Name = "Fund equities weight (+20)", Arm = (sim, c, d) => { RequireFund(c); d.SwfEquitiesWeightOverride = c.SovereignWealthFund.EquitiesWeight + 20f; } });
            list.Add(new Lever { Family = "Fund", Name = "Fund bonds weight (+20)", Arm = (sim, c, d) => { RequireFund(c); d.SwfBondsWeightOverride = c.SovereignWealthFund.BondsWeight + 20f; } });
            list.Add(new Lever { Family = "Fund", Name = "Fund infrastructure weight (+20)", Arm = (sim, c, d) => { RequireFund(c); d.SwfInfrastructureWeightOverride = c.SovereignWealthFund.InfrastructureWeight + 20f; } });
            list.Add(new Lever { Family = "Fund", Name = "Fund real-estate weight (+20)", Arm = (sim, c, d) => { RequireFund(c); d.SwfRealEstateWeightOverride = c.SovereignWealthFund.RealEstateWeight + 20f; } });
            list.Add(new Lever { Family = "Fund", Name = $"Fund drawdown ({DrawdownProbePercentOfGdp:0} % of GDP)", Arm = (sim, c, d) =>
            {
                RequireFund(c);
                Invoke(sim, "ApplySwfDrawdownBillEffects", c, new SwfDrawdownBill { WithdrawalPercentOfGdp = DrawdownProbePercentOfGdp });
            } });
            // Every law in the catalog, enacted through the real path.
            foreach (LawDefinition law in LawCatalog.All)
            {
                LawDefinition l = law;
                list.Add(new Lever { Family = "Law: " + l.Category, Name = $"Law {l.Id} - {l.Name}", ViaDials = DialsMoved(l),
                    Arm = (sim, c, d) => Invoke(sim, "ApplyLawBillEffects", c, new LawBill { LawId = l.Id, IsRepeal = false }) });
            }
            return list;
        }

        private static void RequireFund(Country c) { if (c.SovereignWealthFund == null) { throw new NotSupportedException(); } }

        private static readonly string[] LawDialNames =
        {
            "Police Funding", "Sentencing Severity", "Bail Reform", "Drug Policy", "Judicial Funding", "Border Enforcement",
            "Minimum Wage", "Paid Family Leave", "Overtime Regulation", "Retraining Programs", "Family Policy", "Immigration Policy"
        };

        private static string[] DialsMoved(LawDefinition law)
        {
            float[] deltas = law.DialDeltas;
            var moved = new List<string>();
            for (int i = 0; i < deltas.Length && i < LawDialNames.Length; i++)
            {
                if (Mathf.Abs(deltas[i]) > 0f) { moved.Add(LawDialNames[i] + " " + deltas[i].ToString("+0.#;-0.#", CultureInfo.InvariantCulture)); }
            }
            return moved.ToArray();
        }

        private static void Invoke(SimulationManager sim, string method, params object[] args)
        {
            MethodInfo m = typeof(SimulationManager).GetMethod(method, BindingFlags.NonPublic | BindingFlags.Instance);
            if (m == null) { throw new InvalidOperationException($"SimulationManager.{method} not found - the real path moved."); }
            m.Invoke(sim, args);
        }

        // ---- the record -----------------------------------------------------------------------------

        private static string Render(List<Quantity> quantities, List<Lever> levers, Dictionary<string, List<string>> reach, Dictionary<string, List<string>> leverReach)
        {
            var sb = new StringBuilder(1 << 18);
            sb.Append("# LEVER MAP - every macro quantity the model holds, and what reaches it\n\n");
            sb.Append($"GENERATED by `LeverMapDump` ({DateTime.Now:yyyy-MM-dd}), not transcribed. Do not edit by hand; re-run the dump.\n\n");
            sb.Append($"Probed country {Probed}, seed {Seed}, horizon {Horizon} turns ({Horizon * SimulationManager.DaysPerTurn} days). ");
            sb.Append("A lever REACHES a quantity when the quantity's value after the horizon differs from the untouched baseline's by more than float noise (relative 1e-6). ");
            sb.Append("Dials are armed as one PolicyDecision override on the first turn (the path every bill's effects take); laws are enacted through SimulationManager's own ApplyLawBillEffects before the first turn. ");
            sb.Append("A reach is a non-zero difference, not a magnitude judgement.\n\n");

            int dialCount = levers.Count(l => l.ViaDials == null);
            int lawCount = levers.Count - dialCount;
            int notArmed = leverReach.Count(kv => kv.Value == null);
            sb.Append($"**{quantities.Count} quantities · {dialCount} dial probes · {lawCount} laws** ({notArmed} probes not armable for {Probed}: the lever does not exist there, listed in §3 as NOT ARMED).\n\n");

            // §1 quantities
            sb.Append("## 1. The quantities, and what reaches each\n\n");
            sb.Append("| Quantity | Group | Dials reaching it | Laws reaching it | Status |\n|---|---|---|---|---|\n");
            var unreached = new List<Quantity>();
            foreach (Quantity q in quantities)
            {
                List<string> hits = reach[q.Name];
                var dials = hits.Where(h => !h.StartsWith("Law ", StringComparison.Ordinal)).ToList();
                var laws = hits.Where(h => h.StartsWith("Law ", StringComparison.Ordinal)).ToList();
                string status = hits.Count == 0 ? "**UNREACHED**" : dials.Count == 0 ? "laws only" : laws.Count == 0 ? "dials only" : "reached";
                if (hits.Count == 0) { unreached.Add(q); }
                string dialText = dials.Count == 0 ? "-" : dials.Count > 12 ? $"{dials.Count} dials ({string.Join(", ", dials.Take(6))}, …)" : string.Join(", ", dials);
                string lawText = laws.Count == 0 ? "-" : $"{laws.Count} of {lawCount}";
                sb.Append($"| `{q.Name}` | {q.Group} | {dialText} | {lawText} | {status} |\n");
            }

            // §2 unreached
            sb.Append("\n## 2. The unreached set - the coverage plan for P4-C3\n\n");
            if (unreached.Count == 0) { sb.Append("Every quantity is reached by at least one lever.\n"); }
            foreach (Quantity q in unreached) { sb.Append($"- `{q.Name}` ({q.Group})\n"); }
            sb.Append("\nHeld as constants, reachable by nothing and probed by nothing (stated, not measured): ");
            sb.Append($"`TaylorRule.InflationTarget` (a per-country constant function: {Inv(TaylorRule.InflationTarget(Probed))} % for {Probed}), ");
            sb.Append($"`TaylorRule.NeutralRealRate` ({Inv(TaylorRule.NeutralRealRate)} %), `TaylorRule.InflationGapWeight` ({Inv(TaylorRule.InflationGapWeight)}), `TaylorRule.UnemploymentGapWeight` ({Inv(TaylorRule.UnemploymentGapWeight)}). ");
            sb.Append("A monetary-regime law that moves the target or the mandate needs these to become per-country state first.\n");

            // §3 per lever
            sb.Append("\n## 3. Each lever, and the quantities it reaches\n");
            string family = null;
            foreach (Lever lever in levers)
            {
                if (lever.Family != family) { family = lever.Family; sb.Append($"\n### {family}\n\n"); }
                List<string> hits = leverReach[lever.Name];
                if (hits == null) { sb.Append($"- {lever.Name}: NOT ARMED for {Probed}\n"); continue; }
                string via = lever.ViaDials == null ? "" : lever.ViaDials.Length == 0 ? " [moves no dial]" : $" [via {string.Join("; ", lever.ViaDials)}]";
                sb.Append($"- {lever.Name}{via}: {hits.Count} reached");
                if (hits.Count > 0 && hits.Count <= 40) { sb.Append(" - ").Append(string.Join(", ", hits.Select(h => $"`{h}`"))); }
                sb.Append('\n');
            }

            // §4 the coupling tables' targets
            sb.Append("\n## 4. The coupling tables' targets (structural, from the tables themselves)\n\n");
            sb.Append("Labour couplings (`LaborCouplings.All`):\n\n");
            foreach (var g in LaborCouplings.All.GroupBy(c => c.Stat))
            {
                sb.Append($"- {g.Key}: {string.Join(", ", g.Select(c => $"{c.Dial} ({c.SignedSensitivity.ToString("+0.####;-0.####", CultureInfo.InvariantCulture)})"))}\n");
            }
            sb.Append("\nCrime & Justice couplings (`CrimeJusticeCouplings.All`):\n\n");
            foreach (var g in CrimeJusticeCouplings.All.GroupBy(c => c.Stat))
            {
                sb.Append($"- {g.Key}: {string.Join(", ", g.Select(c => $"{c.Dial} ({c.SignedSensitivity.ToString("+0.####;-0.####", CultureInfo.InvariantCulture)})"))}\n");
            }
            return sb.ToString();
        }

        private static string Inv(float v) => v.ToString("0.0##", CultureInfo.InvariantCulture);

        private static string Arg(string prefix, string fallback)
        {
            foreach (string a in Environment.GetCommandLineArgs())
            {
                if (a.StartsWith(prefix, StringComparison.Ordinal)) { return a.Substring(prefix.Length); }
            }
            return fallback;
        }
    }
}
