using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using PoliSim.Data;
using PoliSim.Simulation;
using UnityEngine;

namespace PoliSim.EditorTools
{
    /// <summary>
    /// P4-C1 (2026-09-04) - THE LEVER MAP, MEASURED. Enumerates every macro quantity the model holds and,
    /// for each, which dials and which laws reach it - generated by probing, never transcribed from a
    /// reading of the code. The record it writes (`LEVER_MAP.md` at the repo root) is the coverage plan
    /// for P4-C3: the unreached set is the list of quantities no law and no dial moves today.
    ///
    /// <para>The probing machinery lives in <see cref="LeverProbes"/> since P5-B1 (the budget premise dump shares
    /// it). A quantity is REACHED by a lever when its value after the horizon differs from the baseline's by more
    /// than float noise (relative 1e-6). The central bank's parameters (the inflation target, the neutral real
    /// rate, the two gap weights) are constants and a per-country constant function: they cannot be reached by
    /// anything, which the map states rather than probes.</para>
    ///
    /// Run: `Unity.exe -batchmode -nographics -projectPath &lt;path&gt; -executeMethod
    /// PoliSim.EditorTools.LeverMapDump.Run -logFile &lt;path&gt; [-levermapout=&lt;file&gt;]`
    /// </summary>
    public static class LeverMapDump
    {
        private const int Horizon = 8;                // eight turns - two years, so the slow couplings register
        private const float NoiseRelative = 1e-6f;

        public static void Run()
        {
            CheckExit.ArmLogFold();
            string outPath = LeverProbes.Arg("-levermapout=", Path.Combine(Application.dataPath, "..", "LEVER_MAP.md"));
            List<LeverProbes.Quantity> quantities = LeverProbes.BuildQuantities();
            List<LeverProbes.Lever> levers = LeverProbes.BuildLevers(includeLaws: true, budgetLinePercent: 10f);
            Debug.Log($"LEVERMAP: {quantities.Count} quantities, {levers.Count} levers, horizon {Horizon} turns, seed {LeverProbes.Seed}, {LeverProbes.Probed}.");

            float[] baseline = LeverProbes.RunOne(null, quantities, Horizon, out _);
            var reach = new Dictionary<string, List<string>>();   // quantity -> lever names
            var leverReach = new Dictionary<string, List<string>>();
            foreach (LeverProbes.Quantity q in quantities) { reach[q.Name] = new List<string>(); }
            foreach (LeverProbes.Lever lever in levers)
            {
                float[] probed = LeverProbes.RunOne(lever, quantities, Horizon, out bool armed);
                var hit = new List<string>();
                if (armed)
                {
                    for (int i = 0; i < quantities.Count; i++)
                    {
                        float tolerance = NoiseRelative * Mathf.Max(1f, Mathf.Abs(baseline[i]));
                        if (Mathf.Abs(probed[i] - baseline[i]) > tolerance)
                        {
                            hit.Add(quantities[i].Name);
                            reach[quantities[i].Name].Add(lever.Name);
                        }
                    }
                }
                leverReach[lever.Name] = armed ? hit : null;
            }

            string map = Render(quantities, levers, reach, leverReach);
            File.WriteAllText(outPath, map);
            int unreached = quantities.Count(q => reach[q.Name].Count == 0);
            Debug.Log($"LEVERMAP: wrote {Path.GetFullPath(outPath)} - {quantities.Count - unreached} of {quantities.Count} quantities reached by at least one lever, {unreached} UNREACHED (the coverage plan).");
            CheckExit.Finish(0);
        }

        private static string Render(List<LeverProbes.Quantity> quantities, List<LeverProbes.Lever> levers, Dictionary<string, List<string>> reach, Dictionary<string, List<string>> leverReach)
        {
            var sb = new StringBuilder(1 << 18);
            sb.Append("# LEVER MAP - every macro quantity the model holds, and what reaches it\n\n");
            sb.Append($"GENERATED by `LeverMapDump` ({DateTime.Now:yyyy-MM-dd}), not transcribed. Do not edit by hand; re-run the dump.\n\n");
            sb.Append($"Probed country {LeverProbes.Probed}, seed {LeverProbes.Seed}, horizon {Horizon} turns ({Horizon * SimulationManager.DaysPerTurn} days). ");
            sb.Append("A lever REACHES a quantity when the quantity's value after the horizon differs from the untouched baseline's by more than float noise (relative 1e-6). ");
            sb.Append("Dials are armed as one PolicyDecision override on the first turn (the path every bill's effects take); laws are enacted through SimulationManager's own ApplyLawBillEffects before the first turn. ");
            sb.Append("A reach is a non-zero difference, not a magnitude judgement. Every law reaches `EconomyState.ApprovalRating` through its enactment cost alone; a law reaches anything else only through the twelve dials its deltas move or the structural parameters it carries (§3 names them per law).\n\n");

            int dialCount = levers.Count(l => l.ViaDials == null);
            int lawCount = levers.Count - dialCount;
            int notArmed = leverReach.Count(kv => kv.Value == null);
            sb.Append($"**{quantities.Count} quantities · {dialCount} dial probes · {lawCount} laws** ({notArmed} probes not armable for {LeverProbes.Probed}: the lever does not exist there, listed in §3 as NOT ARMED).\n\n");

            sb.Append("## 1. The quantities, and what reaches each\n\n");
            sb.Append("| Quantity | Group | Dials reaching it | Laws reaching it | Status |\n|---|---|---|---|---|\n");
            var unreached = new List<LeverProbes.Quantity>();
            foreach (LeverProbes.Quantity q in quantities)
            {
                List<string> hits = reach[q.Name];
                var dials = hits.Where(h => !h.StartsWith("Law ", StringComparison.Ordinal)).ToList();
                var laws = hits.Where(h => h.StartsWith("Law ", StringComparison.Ordinal)).ToList();
                string status = hits.Count == 0 ? "**UNREACHED**" : dials.Count == 0 ? "laws only" : laws.Count == 0 ? "dials only" : "reached";
                if (hits.Count == 0) { unreached.Add(q); }
                string dialText = dials.Count == 0 ? "-" : dials.Count > 12 ? $"{dials.Count} dials ({string.Join(", ", dials.Take(6))}, …)" : string.Join(", ", dials);
                string lawText = laws.Count == 0 ? "-" : $"{laws.Count} of {lawCount}";
                sb.Append($"| `{q.Name}` | {q.Group} | {dialText} | {lawText} | {status} |\n");
            }

            sb.Append("\n## 2. The unreached set - the coverage plan for P4-C3\n\n");
            if (unreached.Count == 0) { sb.Append("Every quantity is reached by at least one lever.\n"); }
            foreach (LeverProbes.Quantity q in unreached) { sb.Append($"- `{q.Name}` ({q.Group})\n"); }
            sb.Append("\nThe four Taylor-rule constants (`CurrencyZone.InflationTarget`, `NeutralRealRate`, `InflationGapWeight`, `UnemploymentGapWeight`) are per-currency-zone STATE since P4-C3's third category (2026-09-05), probed above as `Zone.*`: reached by the MonetaryRegime laws where the parliament owns its bank (Sweden, Poland, the USA), unreachable by national law for the euro members - treaty competence, ruling (a).\n");

            sb.Append("\n## 3. Each lever, and the quantities it reaches\n");
            string family = null;
            foreach (LeverProbes.Lever lever in levers)
            {
                if (lever.Family != family) { family = lever.Family; sb.Append($"\n### {family}\n\n"); }
                List<string> hits = leverReach[lever.Name];
                if (hits == null) { sb.Append($"- {lever.Name}: NOT ARMED for {LeverProbes.Probed}\n"); continue; }
                string via = lever.ViaDials == null ? "" : lever.ViaDials.Length == 0 ? " [moves no dial]" : $" [via {string.Join("; ", lever.ViaDials)}]";
                sb.Append($"- {lever.Name}{via}: {hits.Count} reached");
                if (hits.Count > 0 && hits.Count <= 40) { sb.Append(" - ").Append(string.Join(", ", hits.Select(h => $"`{h}`"))); }
                sb.Append('\n');
            }

            sb.Append("\n## 4. The coupling tables' targets (structural, from the tables themselves)\n\n");
            sb.Append("Labour couplings (`LaborCouplings.All`):\n\n");
            foreach (var g in LaborCouplings.All.GroupBy(c => c.Stat))
            {
                sb.Append($"- {g.Key}: {string.Join(", ", g.Select(c => $"{c.Dial} ({c.SignedSensitivity.ToString("+0.####;-0.####", CultureInfo.InvariantCulture)})"))}\n");
            }
            sb.Append("\nCrime & Justice couplings (`CrimeJusticeCouplings.All`):\n\n");
            foreach (var g in CrimeJusticeCouplings.All.GroupBy(c => c.Stat))
            {
                sb.Append($"- {g.Key}: {string.Join(", ", g.Select(c => $"{c.Dial} ({c.SignedSensitivity.ToString("+0.####;-0.####", CultureInfo.InvariantCulture)})"))}\n");
            }
            return sb.ToString();
        }

        private static string Inv(float v) => v.ToString("0.0##", CultureInfo.InvariantCulture);
    }
}
