#!/usr/bin/perl
# BOARDS_BUILT - one row per Design board id, from the record (2026-09-29; COMPLETED.md s648). GENERATED, never hand-edited.
#
#   perl Tools/boards_built.pl <board-file.dc.html> > BOARDS_BUILT.md
#
# The board ids are Design's own: every id="..." in the board file whose screen label starts with the id (19a, 1m-r2, 15c-r3 ...),
# joined with every "board <id>" COMPLETED.md and POLISIM_FEATURE_LIST.md name (boards moved to Design's archive file are known to
# the record only). For each id the record's sections that name it are read:
#   BUILT        a section naming the board also says BUILT / "built" / "installed" of it, and names no REVERT or STOPPED for it
#   UNSURE       the record names the board, but no section says it was built, or one says built and another reverted/stopped it
#   NOT IN THE RECORD   Design drew it and no section or row names it
# The ids of notes (dmm-note, sitting-c-note ...) and symbols (v-*) are not boards and are left out.
use strict; use warnings;
my ($boardFile) = @ARGV;
die "usage: boards_built.pl <board-file.dc.html>\n" unless $boardFile;
my $root = 'G:/UNITY/Projects/PoliSim';
sub slurp { my ($p) = @_; open my $f, '<:encoding(UTF-8)', $p or die "$p: $!\n"; local $/; my $s = <$f>; close $f; $s }
binmode STDOUT, ':encoding(UTF-8)';

my $html = slurp($boardFile);
my %label;
while ($html =~ /\bid="([^"]+)"[^>]*?data-screen-label="([^"]*)"/g) {
    my ($id, $lab) = ($1, $2);
    next if $id =~ /note$|^v-|index$/;
    next unless $lab =~ /^\Q$id\E\b/;
    $label{$id} = $lab;
}
my $record = slurp("$root/COMPLETED.md");
my $features = slurp("$root/POLISIM_FEATURE_LIST.md");
my %fromRecord;
for my $text ($record, $features) {
    while ($text =~ /\b[Bb]oards? ((?:\d{1,2}[a-z](?:-r\d)?)(?:(?:, | and | ?\/ ?|-)\d{0,2}[a-z](?:-r\d)?)*)/g) {
        for my $id (split /, | and | ?\/ ?/, $1) { $fromRecord{$id} = 1 if $id =~ /^\d{1,2}[a-z](?:-r\d)?$/; }
    }
}
my %ids = (%label, map { $_ => ($label{$_} // '') } keys %fromRecord);

# The record's sections, each with its number.
my @sections;
while ($record =~ /^## (\d+)\. (.*?)(?=^## \d+\. |\z)/msg) { push @sections, [$1, $2]; }

sub sortkey { my ($id) = @_; my ($n, $l, $r) = $id =~ /^(\d+)([a-z]*)(?:-r(\d))?/; return sprintf('%03d%-3s%d', $n // 999, $l // '', $r // 0); }

print "# BOARDS_BUILT - one row per Design board, from the record\n\n";
print "GENERATED by `Tools/boards_built.pl` from `COMPLETED.md`, `POLISIM_FEATURE_LIST.md` and Design's board file; never hand-edited.\n";
print "BUILT: a record section naming the board says it was built. UNSURE: the record names it but does not say built, or says built and\n";
print "also reverted or stopped it - read the sections listed. NOT IN THE RECORD: drawn by Design, named by no section or row.\n\n";
print "| board | Design's label | status | sections naming it |\n|---|---|---|---|\n";
for my $id (sort { sortkey($a) cmp sortkey($b) } keys %ids) {
    my (@naming, $built, $undone);
    for my $s (@sections) {
        my ($n, $body) = @$s;
        next unless $body =~ /\b(?:[Bb]oards? |\()(?:[^.\n]{0,40}?)\b\Q$id\E\b(?!-r)/;
        push @naming, $n;
        my @near = $body =~ /(.{0,160}\b\Q$id\E\b(?!-r).{0,160})/sg;
        for my $w (@near) {
            $built = 1 if $w =~ /\bBUILT\b|\bbuilt\b|\binstalled\b|\bINSTALLED\b/;
            $undone = 1 if $w =~ /\bREVERTED\b|\breverted\b|\bSTOPPED\b|\bnot built\b|\bNOT BUILT\b/;
        }
    }
    my $status = !@naming ? 'NOT IN THE RECORD' : ($built && !$undone) ? 'BUILT' : 'UNSURE';
    my $refs = @naming ? join(', ', map { "\x{00A7}$_" } @naming) : '-';
    (my $lab = $ids{$id} // '') =~ s/\|/\\|/g;
    print "| $id | $lab | $status | $refs |\n";
}
