#!/usr/bin/env bash
# ------------------------------------------------------------------------------------------------
# D18's inventory, regenerated end to end. ONE COMMAND, which is the point (§419, 2026-09-09).
#
# The asset request used to carry counts somebody read off a check and typed into the document. Two
# of them were false by the time D18 was written - "52 undrawn marks" (43) and "two StatNodeId icons
# owed" (delivered in the original pack). This script is the replacement for that habit:
#
#   1. Unity, in batch, runs D18Inventory.Emit, which RUNS the coverage checks and writes their own
#      lines to Logs/d18_inventory.md (gitignored - the body's home is the request document).
#   2. That body is spliced into CLAUDE_DESIGN_ASSET_REQUEST.md between the generated-block markers,
#      stamped with its sha256.
#
# D18InventoryCheck, in the cheap bar, rebuilds the body on every run and fails when the document and
# the repo disagree. So the ask cannot go stale quietly: it goes red.
#
# Usage:  Tools/d18_inventory.sh          (from anywhere; paths are derived from this file)
#         UNITY=/path/to/Unity.exe Tools/d18_inventory.sh
#
# ⚠ Unity will refuse to open the project while the Editor has it open. Close it first; the script
#   reports the launcher's own exit code rather than guessing why.
# ------------------------------------------------------------------------------------------------
set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
UNITY="${UNITY:-G:/UNITY/Unity Hub/6000.5.6f1/Editor/Unity.exe}"
DOC="$ROOT/CLAUDE_DESIGN_ASSET_REQUEST.md"
BODY="$ROOT/Logs/d18_inventory.md"
LOG="${D18LOG:-$ROOT/Logs/d18_inventory.log}"
ANCHOR='<!-- D18-INVENTORY -->'

if [ ! -x "$UNITY" ] && [ ! -f "$UNITY" ]; then
  echo "d18: no Unity at '$UNITY' - set UNITY=<path to Unity.exe>" >&2
  exit 2
fi

echo "d18: emitting from $ROOT"
rm -f "$BODY"
"$UNITY" -batchmode -nographics -projectPath "$ROOT" -executeMethod PoliSim.EditorTools.D18Inventory.Emit -logFile "$LOG"
code=$?
echo "d18: Unity exit $code (log: $LOG)"

if [ ! -s "$BODY" ]; then
  echo "d18: no body at $BODY - nothing was emitted, so nothing is spliced." >&2
  exit 3
fi

if [ "$code" -ne 0 ]; then
  # ⚠ A non-zero emit means the inventory itself is untrustworthy (an enumeration found nothing, two
  #   counts of one fact disagreed, or the naming rule failed against a delivered file). Splicing it
  #   anyway would put a figure nobody stands behind in front of another party.
  echo "d18: the emit reported a fault; the document is NOT updated. Read the log." >&2
  exit "$code"
fi

perl -e '
use strict; use warnings; use utf8;
use Digest::SHA qw(sha256_hex);
my ($doc, $body, $anchor) = @ARGV;

open(my $b, "<:raw", $body) or die "d18: cannot read $body: $!\n";
local $/; my $bytes = <$b>; close $b;
$bytes =~ s/\r\n/\n/g;
my $digest = sha256_hex($bytes);

open(my $d, "<:raw", $doc) or die "d18: cannot read $doc: $!\n";
my $text = <$d>; close $d;
$text =~ s/\r\n/\n/g;

my $begin = "<!-- GENERATED by D18Inventory.Emit (Tools/d18_inventory.sh). DO NOT EDIT BY HAND. source-digest: $digest -->";
my $end   = "<!-- END GENERATED -->";
my $block = "$begin\n$bytes$end";

my $where;
if ($text =~ s/<!-- GENERATED by D18Inventory\.Emit.*?<!-- END GENERATED -->/$block/s) {
  $where = "replaced the existing block";
} elsif (index($text, $anchor) >= 0) {
  my $q = quotemeta($anchor);
  $text =~ s/$q/$block/;
  $where = "expanded the anchor";
} else {
  die "d18: the document carries neither a generated block nor the anchor $anchor - refusing to guess where the inventory goes\n";
}

open(my $o, ">:raw", $doc) or die "d18: cannot write $doc: $!\n";
print $o $text; close $o;
printf("d18: %s - %d bytes of inventory, digest %s\n", $where, length($bytes), $digest);
' "$DOC" "$BODY" "$ANCHOR"
