#!/usr/bin/perl
# energy_hydro_prep.pl - EN-3b (2026-09-11): the reservoir dispatch's data - Sweden's four zones' 2023 day-ahead price by the model's load blocks,
# each zone's coupling to the continental price the market clears (the water value's outside option), and the reservoirs' energy capacity.
# Usage: perl Tools/energy_hydro_prep.pl <sources dir> <EnergyData dir>
#   Prices: energy-charts.info /price (day-ahead, EUR/MWh, hourly, 2023) for SE1-SE4, DE-LU and PL - the exchange's data as energy-charts republishes it
#           (its licence note: private and internal use; the seed carries three block means per zone, not the series). The blocks are the model's:
#           P10 / P90 of the hourly national load (energy-charts public_power, Load), as EnergyLayer folds them.
#   Coupling: the OLS slope of a zone's hourly price on the continental proxy's hourly price - Germany's and Poland's weighted 615 / 600 as
#           EnergyMarket weights them - DERIVED from the same year's 8 760 hours; the share of a continental move a Swedish zone carried in 2023.
#   Reservoirs: Energiföretagen, "Aktuellt magasinsläge Sverige" (weekly report, fetched 2026-09-11): 100 % = 33.7 TWh nationally; per zone the
#           report's fill per cent and GWh pair gives the capacity (GWh / fill).
use strict; use warnings; use utf8; use JSON::PP;
my ($src, $out) = @ARGV; die "usage\n" unless $src && $out;
sub slurp { my ($p) = @_; open my $in, '<:raw', $p or die "$p: $!"; local $/; my $t = <$in>; close $in; return $t; }

sub hourly_load { my ($cc) = @_; my $pp = decode_json(slurp("$src/energycharts_public_power_${cc}_2023.json"));
  my ($load) = grep { $_->{name} =~ /^Load$/i } @{$pp->{production_types}}; die "no load for $cc" unless $load;
  my (%lh, %ln); my @t = @{$pp->{unix_seconds}}; my @L = @{$load->{data}};
  for my $i (0..$#t) { next unless defined $L[$i]; my $h = int($t[$i]/3600)*3600; $lh{$h} += $L[$i]; $ln{$h}++; }
  my %hl; $hl{$_} = $lh{$_}/$ln{$_} for keys %lh; return \%hl; }
sub hourly_price { my ($bzn) = @_; my $pr = decode_json(slurp("$src/energycharts_price_${bzn}_2023.json"));
  my %p; my @t = @{$pr->{unix_seconds}}; my @P = @{$pr->{price}}; for my $i (0..$#t) { $p{$t[$i]} = $P[$i] if defined $P[$i]; } return \%p; }
sub blocks { my ($load, $price) = @_;   # block means on the load's P10 / P90
  my @hours = sort { $a <=> $b } grep { exists $price->{$_} } keys %$load; my @loads = map { $load->{$_} } @hours;
  my @s = sort { $a <=> $b } @loads; my $p10 = $s[int(0.10*$#s)]; my $p90 = $s[int(0.90*$#s)];
  my (%sum, %n, $lw, $ls); for my $i (0..$#hours) { my $b = $loads[$i] <= $p10 ? 'base' : ($loads[$i] >= $p90 ? 'peak' : 'mid'); $sum{$b} += $price->{$hours[$i]}; $n{$b}++; $lw += $price->{$hours[$i]} * $loads[$i]; $ls += $loads[$i]; }
  return ($sum{base}/$n{base}, $sum{mid}/$n{mid}, $sum{peak}/$n{peak}, $lw/$ls, scalar @hours); }
sub slope { my ($x, $y) = @_;   # OLS slope of y on x over the common hours
  my (@xs, @ys); for my $h (keys %$x) { next unless exists $y->{$h}; push @xs, $x->{$h}; push @ys, $y->{$h}; }
  my $n = @xs; my ($mx, $my) = (0, 0); $mx += $_ for @xs; $my += $_ for @ys; $mx /= $n; $my /= $n;
  my ($sxy, $sxx) = (0, 0); for my $i (0..$n-1) { $sxy += ($xs[$i]-$mx)*($ys[$i]-$my); $sxx += ($xs[$i]-$mx)**2; } return ($sxy/$sxx, $n); }

my $seLoad = hourly_load('se'); my $deLoad = hourly_load('de'); my $plLoad = hourly_load('pl');
my $de = hourly_price('DE-LU'); my $pl = hourly_price('PL');
my %proxy; for my $h (keys %$de) { next unless exists $pl->{$h}; $proxy{$h} = ($de->{$h} * 615 + $pl->{$h} * 600) / 1215; }   # EnergyMarket.WaterValueOf's weights

# the reservoirs: the weekly report's per-zone fill and GWh
my $txt = slurp("$src/energiforetagen_magasin.txt"); $txt =~ s/\s+/ /g;
my ($nat) = $txt =~ /100 ?%= ?([0-9]+,[0-9]) TWh/ or die "national capacity";
$nat =~ s/,/./; my $nationalGwh = $nat * 1000;
my %cap;
if ($txt =~ /SE1 ?([0-9]+,[0-9]) ?([0-9][0-9 ]*?) ?SE2 ?([0-9]+,[0-9]) ?([0-9][0-9 ]*?) ?SE3 ?([0-9]+,[0-9]) ?([0-9][0-9 ]*?) ?SE4 ?([0-9]+,[0-9]) ?([0-9][0-9 ]*?) ?0102030/) {
  my @v = ($1, $2, $3, $4, $5, $6, $7, $8); my @z = qw(SE1 SE2 SE3 SE4);
  for my $i (0..3) { my $pct = $v[2*$i]; $pct =~ s/,/./; my $gwh = $v[2*$i+1]; $gwh =~ s/ //g; $cap{$z[$i]} = $pct > 0 ? $gwh / ($pct/100) : 0; }
} else { die "per-zone reservoir figures not found in the report's text"; }
my $sum = 0; $sum += $cap{$_} for keys %cap;

open my $o, '>:encoding(UTF-8)', "$out/hydro_2023.csv" or die $!;
print $o "# hydro_2023.csv - GENERATED by Tools/energy_hydro_prep.pl (EN-3b). Sweden's zones: the 2023 day-ahead price by the model's load blocks (energy-charts.info, the exchange's data; block = P10/P90 of the hourly national load), the zone's coupling to the continental proxy (OLS slope of the zone's hourly price on the 615/600-weighted DE-LU/PL hourly price, 2023 - DERIVED), and the reservoir's energy capacity (Energiföretagen weekly report: GWh / fill per cent; national 100 % = $nat TWh).\n";
printf $o "# The continental proxy's own 2023 block means on Germany's and Poland's loads are appended for the record (rows DE, PL): what the market's seed prices are measured against.\n";
print $o "zone;price_base;price_mid;price_peak;price_load_weighted;hours;beta_to_proxy;reservoir_capacity_gwh\n";
for my $z (qw(SE1 SE2 SE3 SE4)) {
  my $p = hourly_price($z); my ($b, $m, $k, $lw, $n) = blocks($seLoad, $p); my ($beta, $nb) = slope(\%proxy, $p);
  printf $o "%s;%.2f;%.2f;%.2f;%.2f;%d;%.4f;%.0f\n", $z, $b, $m, $k, $lw, $n, $beta, $cap{$z};
}
{ my ($b, $m, $k, $lw, $n) = blocks($deLoad, $de); printf $o "DE;%.2f;%.2f;%.2f;%.2f;%d;1.0000;0\n", $b, $m, $k, $lw, $n; }
{ my ($b, $m, $k, $lw, $n) = blocks($plLoad, $pl); printf $o "PL;%.2f;%.2f;%.2f;%.2f;%d;1.0000;0\n", $b, $m, $k, $lw, $n; }
close $o;

# the hydro fleets' storage character: Eurostat nrg_inf_epcrw 2023 - RA100 hydro, RA110ROR run-of-river, RA130 pumped storage (a store, not an inflow);
# the SHIFTABLE share of the year's hydro energy is what is neither run-of-river nor pumped: (RA100 - RA110ROR - RA130) / (RA100 - RA130).
my $tsv = slurp("$src/eurostat_nrg_inf_epcrw_2023.tsv"); my %fleet;
for my $line (split /\n/, $tsv) { my @c = split /\t/, $line; next unless @c >= 7; my ($siec) = $c[1] =~ /^(RA\w+)=/; my ($cc) = $c[4] =~ /^([A-Z]{2})=/; next unless $siec && $cc; $fleet{$cc}{$siec} = $c[6] + 0; }
open my $h, '>:encoding(UTF-8)', "$out/hydro_fleet_2023.csv" or die $!;
print $h "# hydro_fleet_2023.csv - GENERATED by Tools/energy_hydro_prep.pl (EN-3b). The hydro fleets' storage character, 2023, MW: Eurostat nrg_inf_epcrw CAP_NET_ELC - RA100 hydro, RA110ROR run-of-river, RA130 pumped storage. shiftable_share = (hydro - run-of-river - pumped) / (hydro - pumped): the part of the year's hydro energy a reservoir operator can move between the load blocks. ⚠ France and Poland report run-of-river as 0 (a reporting hole for France, whose fleet is largely run-of-river and pondage) - their share is BILLED and reads 0 here, so no shift is modelled for them; the USA has no Eurostat row and is BILLED likewise.\n";
print $h "country;hydro_mw;run_of_river_mw;pumped_mw;shiftable_share;status\n";
for my $cc (qw(DE FR IT PL SE US)) {
  my $f = $fleet{$cc} || {}; my ($all, $ror, $pump) = ($f->{RA100} // 0, $f->{RA110ROR} // 0, $f->{RA130} // 0);
  my $status = $cc eq 'US' ? 'BILLED (no Eurostat row)' : ($ror <= 0 && $cc ne 'SE' ? 'BILLED (run-of-river reported 0)' : 'SOURCED');
  my $share = ($all - $pump) > 0 && $status eq 'SOURCED' ? ($all - $ror - $pump) / ($all - $pump) : 0;
  $share = 1 if $cc eq 'SE';   # Sweden's hydro is regulated river systems: run-of-river reported 0, and the water value is its price
  printf $h "%s;%.0f;%.0f;%.0f;%.4f;%s\n", $cc, $all, $ror, $pump, $share, $status;
}
close $h;
printf "energy_hydro_prep: national capacity %.1f TWh (zones sum %.1f); wrote hydro_2023.csv and hydro_fleet_2023.csv\n", $nat, $sum/1000;
