#!/usr/bin/perl
# energy_index_prep.pl - EN-5 (2026-09-11): electricity's weight in each country's consumer price index, the pass-through's one sourced factor.
# Usage: perl Tools/energy_index_prep.pl <sources dir> <EnergyData dir>
#   DE FR IT PL SE: Eurostat prc_hicp_inw (HICP item weights), COICOP CP0451 "Electricity", 2023, per mille of the all-items basket (JSON-stat, fetched 2026-09-10).
#   US: BLS "Relative importance of components in the Consumer Price Indexes: U.S. city average, December 2023", CPI-U column, "Electricity", per cent
#       (the page as served through web.archive.org - bls.gov answers 403 to this client - fetched 2026-09-11); written per mille.
use strict; use warnings; use utf8;
my ($src, $out) = @ARGV; die "usage: energy_index_prep.pl <sources> <EnergyData>\n" unless $src && $out;
sub slurp { my ($p) = @_; open my $in, '<:raw', $p or die "$p: $!"; local $/; my $t = <$in>; close $in; return $t; }

# Eurostat JSON-stat: value index over the dimension order freq,coicop,geo,time (sizes 1,3,5,1) - index = coicop*5 + geo
my $json = slurp("$src/eurostat_prc_hicp_inw_2023.json");
my %geoIndex; { my ($geoBlock) = $json =~ /"geo":\{"label":"[^"]*","category":\{"index":\{([^}]*)\}/ or die "geo index"; while ($geoBlock =~ /"([A-Z]{2})":(\d+)/g) { $geoIndex{$1} = $2; } }
my %coicopIndex; { my ($cb) = $json =~ /"coicop":\{"label":"[^"]*","category":\{"index":\{([^}]*)\}/ or die "coicop index"; while ($cb =~ /"(CP\w+)":(\d+)/g) { $coicopIndex{$1} = $2; } }
my %value; { my ($vb) = $json =~ /"value":\{([^}]*)\}/ or die "values"; while ($vb =~ /"(\d+)":([0-9.]+)/g) { $value{$1} = $2; } }
my $geoCount = scalar keys %geoIndex;
my %w;
for my $cc (qw(DE FR IT PL SE)) { my $i = $coicopIndex{CP0451} * $geoCount + $geoIndex{$cc}; die "no value for $cc" unless defined $value{$i}; $w{$cc} = $value{$i}; }

# BLS: the CPI-U column of the December 2023 relative-importance table
my $bls = slurp("$src/bls_ri_2023_archive.html"); $bls =~ s/<script.*?<\/script>//gs; $bls =~ s/<[^>]+>/ /g; $bls =~ s/&nbsp;/ /g; $bls =~ s/\s+/ /g;
my ($cpiu) = $bls =~ /Electricity ([0-9]+\.[0-9]+) [0-9]+\.[0-9]+ Utility/ or die "BLS electricity row";
$w{US} = $cpiu * 10;   # per cent -> per mille

open my $o, '>:encoding(UTF-8)', "$out/price_index_weights_2023.csv" or die $!;
print $o "# price_index_weights_2023.csv - GENERATED by Tools/energy_index_prep.pl (EN-5). Electricity's weight in the consumer price index, per mille of the all-items basket, 2023.\n";
print $o "# DE FR IT PL SE: Eurostat prc_hicp_inw, COICOP CP0451 Electricity, 2023 (HICP item weights; the 2023 weights rest on 2022's expenditure, the spike year - Sweden's 70.50 is two and a half times Germany's, and part of that is the year).\n";
printf $o "# US: BLS relative importance December 2023, CPI-U, Electricity %.3f %% (per mille below); reached through web.archive.org, bls.gov refusing this client.\n", $cpiu;
print $o "country;electricity_per_mille;source\n";
for my $cc (qw(DE FR IT PL SE US)) { printf $o "%s;%.2f;%s\n", $cc, $w{$cc}, $cc eq 'US' ? 'BLS CPI-U relative importance Dec 2023' : 'Eurostat prc_hicp_inw CP0451 2023'; }
close $o;
printf "energy_index_prep: %s\n", join(', ', map { "$_ $w{$_}" } qw(DE FR IT PL SE US));
