#!/usr/bin/perl
# POLAND'S 41 OKREGI AS A TABLE FOR A DESIGN ASK (D-PL, COMPLETED.md s771). Reads the district table of ElectionsData/poland/returns_2023.md
# ("| 1 Legnica (12) | ..." - the KBW's okregi_sejm_utf8.csv, the seat city and the magnitude) and writes, to the directory given:
#   districts_2023.csv   okreg;seat_city;seats - generated, never retyped
# and, with -ask <ASK.md>, replaces a line reading exactly TABLE in that file with the same rows as a markdown table.
# Dies unless it reads 41 districts whose seats sum to 460 (Kodeks wyborczy art. 201; the same check as Tools/sejm_districts_prep.pl).
# Usage (from the project root): perl Tools/pl_districts_table.pl <outdir> [-ask <ASK.md>]
use strict;
use warnings;
use utf8;

my ($outdir, $flag, $ask) = @ARGV;
die "usage: perl Tools/pl_districts_table.pl <outdir> [-ask <ASK.md>]\n" unless $outdir && -d $outdir;
open my $in, '<:encoding(UTF-8)', 'ElectionsData/poland/returns_2023.md' or die "returns_2023.md: $!";
my @rows;
while (my $line = <$in>) { push @rows, [$1, $2, $3] if $line =~ /^\| (\d+) (.+?) \((\d+)\) \|/; }
close $in;
my $seats = 0;
$seats += $_->[2] for @rows;
die "read " . scalar(@rows) . " districts summing to $seats seats - not 41 and 460\n" unless @rows == 41 && $seats == 460;

open my $csv, '>:encoding(UTF-8)', "$outdir/districts_2023.csv" or die $!;
print $csv "# Poland Sejm 2023 - the 41 okregi: number, seat of the district commission (siedziba OKW), magnitude [SOURCED]\n";
print $csv "# from ElectionsData/poland/returns_2023.md (the KBW okregi_sejm_utf8.csv); generated by Tools/pl_districts_table.pl, never retyped\n";
print $csv "okreg;seat_city;seats\n";
print $csv join(';', @$_) . "\n" for @rows;
close $csv;
print "WROTE $outdir/districts_2023.csv - 41 districts, 460 seats\n";

if (defined $flag && $flag eq '-ask')
{
    open my $a, '<:encoding(UTF-8)', $ask or die "$ask: $!";
    local $/;
    my $text = <$a>;
    close $a;
    my $table = "| okręg | seat (siedziba OKW) | seats |\n|---:|---|---:|\n" . join('', map { "| $_->[0] | $_->[1] | $_->[2] |\n" } @rows);
    chomp $table;
    my $n = ($text =~ s/^TABLE$/$table/m);
    die "$ask has no line reading TABLE\n" unless $n;
    open my $o, '>:encoding(UTF-8)', $ask or die $!;
    print $o $text;
    close $o;
    print "FILLED the table in $ask\n";
}
