#!/usr/bin/perl
# THE PRE-START RECORD (ruled 2026-10-01, item 0 of the round after the overnight round; COMPLETED.md s709). Reads the five raw files saved
# whole under ElectionsData/macro/raw/ and writes, per country and month, the two published series the perceived-economy reading takes:
#   ElectionsData/macro/prestart_record.csv                     country,month,unemployment,inflation (blank = not published)
#   Assets/Scripts/Elections/Generated/PreStartRecord.cs        the same figures as C# literals, the CSV's SHA-256 in its header
# Sources: Eurostat une_rt_m (s_adj=SA, age=TOTAL, sex=T, unit=PC_ACT) for unemployment, the EU five; Eurostat prc_hicp_manr (coicop=CP00,
# unit=RCH_A) through 2025-12 and prc_hicp_minr (ECOICOP ver.2, coicop18=TOTAL, unit=RCH_A) from 2026-01 for inflation - the two agree within
# 0.1 on every overlapping month checked; BLS LNS14000000 (U-3, SA) and CUUR0000SA0 (CPI-U, NSA; the 12-month change computed from the index,
# rounded to one decimal as BLS prints it) for the USA. BLS prints "-" for a month it never published (October 2025, "Data unavailable due to
# the 2025 lapse in appropriations") - that month is left out, never read as zero; the CPI 12-month change of October 2026 has no base for it either.
# Usage: perl Tools/prestart_record_prep.pl   (from the project root)
# ASCII only.
use strict; use warnings;
use JSON::PP;
use Digest::SHA qw(sha256_hex);

my $raw = 'ElectionsData/macro/raw';
sub load { my ($f) = @_; open my $h, '<:raw', "$raw/$f" or die "$raw/$f: $!\n"; local $/; my $s = <$h>; close $h; return decode_json($s); }

# A Eurostat JSON-stat 2.0 value by its (geo, time), every other dimension a single member.
sub eurostat {
    my ($j) = @_;
    my @ids = @{$j->{id}}; my @size = @{$j->{size}};
    my %out;
    for my $geo (keys %{$j->{dimension}{geo}{category}{index}}) {
        for my $time (keys %{$j->{dimension}{time}{category}{index}}) {
            my $i = 0;
            for my $k (0 .. $#ids) {
                my $d = $ids[$k];
                my $p = $d eq 'geo' ? $j->{dimension}{geo}{category}{index}{$geo} : $d eq 'time' ? $j->{dimension}{time}{category}{index}{$time} : 0;
                die "dimension $d has more than one member\n" if $d ne 'geo' && $d ne 'time' && $size[$k] != 1;
                $i = $i * $size[$k] + $p;
            }
            $out{$geo}{$time} = $j->{value}{$i} if defined $j->{value}{$i};
        }
    }
    return \%out;
}

my %country = (DE => 'Germany', SE => 'Sweden', IT => 'Italy', PL => 'Poland', FR => 'France');
my %une; my %inf;
my $u = eurostat(load('eurostat_une_rt_m_2026-10-01.json'));
my $h1 = eurostat(load('eurostat_prc_hicp_manr_2026-10-01.json'));
my $h2 = eurostat(load('eurostat_prc_hicp_minr_2026-10-01.json'));
for my $geo (keys %country) {
    my $c = $country{$geo};
    for my $t (keys %{$u->{$geo}}) { $une{$c}{$t} = $u->{$geo}{$t}; }
    for my $t (keys %{$h1->{$geo}}) { $inf{$c}{$t} = $h1->{$geo}{$t} if $t le '2025-12'; }
    for my $t (keys %{$h2->{$geo}}) { $inf{$c}{$t} = $h2->{$geo}{$t} if $t ge '2026-01'; }
}
my $bls = sub { my $j = load(shift); my %m; for my $d (@{$j->{Results}{series}[0]{data}}) { my ($mm) = $d->{period} =~ /^M(\d\d)$/; next unless defined $mm && $mm ne '13' && $d->{value} =~ /^-?[0-9.]+$/; $m{sprintf('%s-%s', $d->{year}, $mm)} = $d->{value}; } \%m; };
my $usU = $bls->('bls_LNS14000000_2026-10-01.json');
my $usI = $bls->('bls_CUUR0000SA0_2026-10-01.json');
for my $t (keys %$usU) { $une{USA}{$t} = $usU->{$t} + 0; }
for my $t (keys %$usI) {
    my ($y, $m) = split /-/, $t; my $prev = sprintf('%04d-%s', $y - 1, $m);
    next unless defined $usI->{$prev};
    my $r = 100.0 * ($usI->{$t} / $usI->{$prev} - 1.0);
    $inf{USA}{$t} = sprintf('%.1f', $r + ($r >= 0 ? 1e-9 : -1e-9)) + 0;
}

my @countries = qw(USA Sweden Germany France Italy Poland);
my %months; for my $c (@countries) { $months{$_} = 1 for (keys %{$une{$c} || {}}), (keys %{$inf{$c} || {}}); }
my @all = sort keys %months;

my $csv = "country,month,unemployment,inflation\n";
for my $c (@countries) {
    for my $t (@all) {
        my ($a, $b) = ($une{$c}{$t}, $inf{$c}{$t});
        next unless defined $a || defined $b;
        $csv .= join(',', $c, $t, defined $a ? $a : '', defined $b ? $b : '') . "\n";
    }
}
my $csvPath = 'ElectionsData/macro/prestart_record.csv';
open my $o, '>:raw', $csvPath or die; print $o $csv; close $o;
my $digest = sha256_hex($csv);

my $cs = "// GENERATED by Tools/prestart_record_prep.pl. DO NOT EDIT BY HAND.\n//\n// Source : $csvPath\n// SHA-256: $digest\n//\n"
    . "// PreStartRecordDiagnostic re-reads the CSV and compares every figure.\n\n"
    . "namespace PoliSim.Elections.Generated\n{\n"
    . "    /// <summary>s709 (ruled 2026-10-01): the two published series the perceived-economy reading takes, per country and month - SOURCED\n"
    . "    /// (Eurostat une_rt_m SA and the HICP annual rate for the EU five; BLS U-3 SA and the CPI-U 12-month change for the USA; the record\n"
    . "    /// `ElectionsData/macro/prestart_record.md`). NaN = not published. Generated, never hand-edited.</summary>\n"
    . "    public static class PreStartRecord\n    {\n        public const string SourceDigest = \"$digest\";\n\n";
for my $c (@countries) {
    $cs .= "        /// <summary>$c: year, month, unemployment (%), inflation (% over twelve months).</summary>\n";
    $cs .= "        public static readonly (int Year, int Month, float Unemployment, float Inflation)[] $c =\n        {\n";
    for my $t (@all) {
        my ($a, $b) = ($une{$c}{$t}, $inf{$c}{$t});
        next unless defined $a || defined $b;
        my ($y, $m) = split /-/, $t;
        my $f = sub { my $v = shift; defined $v ? sprintf('%sf', $v + 0) : 'float.NaN' };
        $cs .= sprintf("            (%d, %d, %s, %s),\n", $y, $m + 0, $f->($a), $f->($b));
    }
    $cs .= "        };\n\n";
}
$cs .= "        /// <summary>The country's months, oldest first.</summary>\n"
    . "        public static (int Year, int Month, float Unemployment, float Inflation)[] For(PoliSim.Data.CountryId id)\n        {\n"
    . "            switch (id)\n            {\n";
$cs .= "                case PoliSim.Data.CountryId.$_: return $_;\n" for @countries;
$cs .= "                default: return new (int, int, float, float)[0];\n            }\n        }\n    }\n}\n";
my $csPath = 'Assets/Scripts/Elections/Generated/PreStartRecord.cs';
open my $p, '>:raw', $csPath or die; print $p $cs; close $p;
my $rows = () = $csv =~ /\n/g;
print "WROTE $csvPath (" . ($rows - 1) . " rows, SHA-256 $digest) and $csPath\n";
