#!/usr/bin/perl
# POLAND'S PRESIDENTIAL RETURNS FOR THE RUNTIME (PS-5 with S7, part one; COMPLETED.md s720). Reads the PKW's four rounds as the sourcing pass
# saved them - ElectionsData/poland/presidential_votes.csv (election,round,date,candidate,committee,votes; __VALID__ / __INVALID__ / __BALLOTS__ /
# __ELIGIBLE__ rows per round; the notices in ElectionsData/poland/presidential_returns.md) - and writes
#   Assets/Scripts/Elections/Generated/PolishPresidentialReturns.cs   the candidates' votes and the round totals as C# literals, the CSV's SHA-256
# in its header. The names pass through byte for byte (UTF-8, the PKW's spelling). PresidentialElectionDiagnostic re-reads the CSV and compares.
# Usage: perl Tools/presidential_returns_prep.pl   (from the project root)
# ASCII only.
use strict; use warnings;
use Digest::SHA qw(sha256_hex);

my $csv = 'ElectionsData/poland/presidential_votes.csv';
my $out = 'Assets/Scripts/Elections/Generated/PolishPresidentialReturns.cs';
open my $h, '<:raw', $csv or die "$csv: $!\n";
local $/; my $bytes = <$h>; close $h;
my $digest = sha256_hex($bytes);

my (@rows, %totals, @order);
my $header = 1;
for my $line (split /\r?\n/, $bytes) {
    next if $line eq '' || $line =~ /^#/;
    if ($header) { $header = 0; next; }
    my @f; my $cur = ''; my $quoted = 0;
    for my $c (split //, $line) {
        if ($c eq '"') { $quoted = !$quoted; next; }
        if ($c eq ',' && !$quoted) { push @f, $cur; $cur = ''; next; }
        $cur .= $c;
    }
    push @f, $cur;
    die "a row of $csv has " . scalar(@f) . " fields, not 6: $line\n" unless @f == 6;
    my ($year, $round, $date, $candidate, undef, $votes) = @f;
    die "not a date: $date\n" unless $date =~ /^(\d{4})-(\d{2})-(\d{2})$/;
    my ($y, $m, $d) = ($1, $2 + 0, $3 + 0);
    die "not a count: $votes\n" unless $votes =~ /^\d+$/;
    my $key = "$year/$round";
    push @order, $key unless exists $totals{$key};
    $totals{$key} ||= { year => $year, round => $round, m => $m, d => $d };
    if ($candidate =~ /^__(VALID|INVALID|BALLOTS|ELIGIBLE)__$/) { $totals{$key}{lc $1} = $votes; next; }
    die "a quote or a backslash in a name: $candidate\n" if $candidate =~ /["\\]/;
    push @rows, "            ($year, $round, \"$candidate\", ${votes}L),";
}
my @tot;
for my $key (@order) {
    my $t = $totals{$key};
    for my $f (qw(valid invalid ballots eligible)) { die "$key has no __\U$f\E__ row\n" unless defined $t->{$f}; }
    push @tot, "            ($t->{year}, $t->{round}, $t->{m}, $t->{d}, $t->{valid}L, $t->{invalid}L, $t->{ballots}L, $t->{eligible}L),";
}

open my $o, '>:raw', $out or die "$out: $!\n";
print $o "// GENERATED by Tools/presidential_returns_prep.pl. DO NOT EDIT BY HAND.\r\n//\r\n// Source : $csv\r\n// SHA-256: $digest\r\n//\r\n";
print $o "// PresidentialElectionDiagnostic re-reads the CSV and compares every figure.\r\n\r\n";
print $o "namespace PoliSim.Elections.Generated\r\n{\r\n";
print $o "    /// <summary>s720 (PS-5 with S7): Poland's presidential elections of record, both rounds of 2020 and 2025 - SOURCED (the PKW's notices in the\r\n";
print $o "    /// Dziennik Ustaw, `ElectionsData/poland/presidential_returns.md`). Generated, never hand-edited.</summary>\r\n";
print $o "    public static class PolishPresidentialReturns\r\n    {\r\n";
print $o "        public const string SourceDigest = \"$digest\";\r\n\r\n";
print $o "        /// <summary>Each candidate's votes: election year, round (1 the first vote, 2 the run-off), the candidate as the PKW writes the name, the votes.</summary>\r\n";
print $o "        public static readonly (int Year, int Round, string Candidate, long Votes)[] Votes =\r\n        {\r\n";
print $o join("\r\n", @rows), "\r\n        };\r\n\r\n";
print $o "        /// <summary>Each round: year, round, the day it was held (month, day), the valid votes, the invalid, the ballots, the electorate.</summary>\r\n";
print $o "        public static readonly (int Year, int Round, int Month, int Day, long Valid, long Invalid, long Ballots, long Eligible)[] Rounds =\r\n        {\r\n";
print $o join("\r\n", @tot), "\r\n        };\r\n    }\r\n}\r\n";
close $o;
print "WROTE $out - " . scalar(@rows) . " candidate rows over " . scalar(@tot) . " rounds; source SHA-256 $digest\n";
