#!/usr/bin/perl
# POLAND'S SEJM DISTRICTS FOR THE RUNTIME (PS-5, the live wiring part two; COMPLETED.md s762). Reads the 2023 Sejm's votes per committee per okreg as
# the sourcing pass saved them - ElectionsData/poland/district_votes_2023.csv (okreg;PiS;KO;TD;NL;Konf;MN, the PKW's own file, every national sum
# cross-checked) - and the 41 districts' magnitudes from ElectionsData/poland/returns_2023.md's district table ("| 1 Legnica (12) | ..."), and writes
#   Assets/Scripts/Elections/Generated/PolishSejmDistricts2023.cs   the committees, the votes and the magnitudes as C# literals, both sources' SHA-256
# in its header. PolishSejmAllocationDiagnostic re-reads both files and compares every figure.
# Usage: perl Tools/sejm_districts_prep.pl [out]   (from the project root; out defaults to the Generated path)
# ASCII only.
use strict; use warnings;
use Digest::SHA qw(sha256_hex);

my $csv = 'ElectionsData/poland/district_votes_2023.csv';
my $md = 'ElectionsData/poland/returns_2023.md';
my $out = shift // 'Assets/Scripts/Elections/Generated/PolishSejmDistricts2023.cs';

open my $h, '<:raw', $csv or die "$csv: $!\n"; local $/; my $bytes = <$h>; close $h;
my $csvDigest = sha256_hex($bytes);
my (@committees, @rows);
for my $line (split /\r?\n/, $bytes) {
    next if $line eq '' || $line =~ /^#/;
    my @f = split /;/, $line;
    if (!@committees) { die "the header must start with okreg\n" unless $f[0] eq 'okreg'; @committees = @f[1..$#f]; next; }
    die "a row has " . scalar(@f) . " fields: $line\n" unless @f == @committees + 1;
    for my $v (@f) { die "not a whole number: $v\n" unless $v =~ /^\d+$/; }
    push @rows, [@f];
}
die "41 districts expected, " . scalar(@rows) . " read\n" unless @rows == 41;
for my $i (0..$#rows) { die "okreg " . ($i + 1) . " out of order\n" unless $rows[$i][0] == $i + 1; }

open $h, '<:raw', $md or die "$md: $!\n"; my $mdBytes = <$h>; close $h;
my $mdDigest = sha256_hex($mdBytes);
my %mag;
for my $line (split /\r?\n/, $mdBytes) { if ($line =~ /^\|\s*(\d+)\s+[^|(]+\((\d+)\)\s*\|/) { $mag{$1} = $2; } }
die "41 magnitudes expected, " . scalar(keys %mag) . " read\n" unless keys(%mag) == 41;
my $seats = 0; $seats += $mag{$_} for 1..41;
die "the magnitudes sum to $seats, not 460\n" unless $seats == 460;

my $c = join(', ', map { "\"$_\"" } @committees);
my @votes = map { my $r = $_; '            new long[] { ' . join(', ', @{$r}[1..$#$r]) . ' },   // okreg ' . $r->[0] } @rows;
my $m = join(', ', map { $mag{$_} } 1..41);
open my $o, '>:raw', $out or die "$out: $!\n";
print $o <<"EOT";
// GENERATED by Tools/sejm_districts_prep.pl. DO NOT EDIT BY HAND.
//
// Source : ElectionsData/poland/district_votes_2023.csv
// SHA-256: $csvDigest
// Source : ElectionsData/poland/returns_2023.md (the district table's magnitudes)
// SHA-256: $mdDigest
//
// PolishSejmAllocationDiagnostic re-reads both files and compares every figure.

namespace PoliSim.Elections.Generated
{
    /// <summary>s762 (PS-5, the live wiring part two): the 10th Sejm's election of 2023 by district - every committee's valid votes in each of the 41
    /// okregi and each okreg's magnitude - SOURCED (the PKW's own per-district file; the notice Dz.U. 2023 poz. 2234, `ElectionsData/poland/returns_2023.md`).
    /// Generated, never hand-edited. The live count's base: the game's national vote is spread over the districts by a uniform swing from these.</summary>
    public static class PolishSejmDistricts2023
    {
        public const string SourceDigest = "$csvDigest";
        public const string MagnitudesDigest = "$mdDigest";

        /// <summary>The committees, the columns of <see cref="Votes"/> - the 2023 lists' own keys.</summary>
        public static readonly string[] Committees = { $c };

        /// <summary>Valid votes per committee (columns as <see cref="Committees"/>) per okreg (rows, okreg 1 to 41).</summary>
        public static readonly long[][] Votes =
        {
@{[join("\n", @votes)]}
        };

        /// <summary>Each okreg's seats, okreg 1 to 41 (Kodeks wyborczy art. 201 - 460 in all).</summary>
        public static readonly int[] Magnitudes = { $m };
    }
}
EOT
close $o;
print "wrote $out: " . scalar(@rows) . " districts, " . scalar(@committees) . " committees, 460 seats\n";
