#!/usr/bin/perl
# THE AT-REST TEXT-DRAW BASELINE (D24 item 5, 2026-09-29; COMPLETED.md s648). Reads a dry film's label table (the
# DryGuiPass record: one row per text draw per capture; PoliSim-captures/labels/<label>_<country>_<w>_labels.tsv) and
# prints what a screen AT REST asks the reader to read: the text draws inside the clip of each rail screen's own
# unscrolled frame. The screens are composed for UI v3.3 in this order - most text first - so the ranking is emitted,
# never typed.
#
#   perl Tools/text_baseline.pl rank   <labels.tsv>           the rail screens by visible text draws at rest, most first
#   perl Tools/text_baseline.pl screen <labels.tsv> <stem>     one frame's visible draws: font size, mode, width, text
#   perl Tools/text_baseline.pl tsv    <labels.tsv> <a,b,..>   the named frames' visible draws as a TSV, geometry kept (s662, Design's
#                                                              ask); each frame's count goes to stderr
#   perl Tools/text_baseline.pl reach  <labels.tsv> 04h_people_dense   People's moved words, each on the dense frame (s662)
#
# A rail screen's at-rest frame is the capture the sweep takes on arriving at it (the stems below, the sweep's own);
# a draw flagged OUTSIDE its clip is not on the screen and is not counted. The Desk is 01c_desk (the running desk).
use strict; use warnings;
binmode STDOUT, ':encoding(UTF-8)';
#   perl Tools/text_baseline.pl removed <before.tsv> <after.tsv> <stem> <first> <stop>   s666: the draws a retrofit took off a frame's block at
#        rest - the visible draws of <stem> from the one reading <first> up to (not including) the one beginning <stop>, in <before>, less those still
#        there in <after>; one per line, a multiset difference. Its output is docs/generated/PEOPLE_AT_REST_REMOVED.tsv, read by
#        PeopleSlipReachabilityCheck (every removed word on a slip within two levels).
if (@ARGV && $ARGV[0] eq 'removed') {
    my (undef, $before, $after, $rstem, $first, $stop) = @ARGV;
    die "usage: text_baseline.pl removed <before.tsv> <after.tsv> <stem> <first> <stop>\n" unless $stop;
    my $block = sub {
        my ($file) = @_;
        open my $h, '<:encoding(UTF-8)', $file or die "$file: $!\n";
        my $hd = <$h>; chomp $hd; $hd =~ s/\r$//; my @c = split /\t/, $hd; my %a; @a{@c} = 0 .. $#c;
        my (@out, $on);
        while (my $l = <$h>) { chomp $l; $l =~ s/\r$//; my @f = split /\t/, $l, -1;
            next unless $f[$a{capture}] eq $rstem; next if ($f[$a{flags}] // '') =~ /OUTSIDE/;
            my $x = $f[$a{text}]; $on = 1 if $x eq $first; $on = 0 if $on && index($x, $stop) == 0; push @out, $x if $on; }
        close $h; return @out;
    };
    my @b = $block->($before); my %keep; $keep{$_}++ for $block->($after);
    die "no block in $before\n" unless @b;
    print "# GENERATED by Tools/text_baseline.pl removed - never hand-edited. The draws ${rstem}'s block ('$first' to '$stop') carried at rest before\n";
    print "# its retrofit and no longer does: before = $before, after = $after. One draw per line.\n";
    print "text\n";
    for my $x (@b) { if ($keep{$x}) { $keep{$x}--; next } print "$x\n" }
    exit 0;
}
my ($mode, $tsv, $stem) = @ARGV;
die "usage: text_baseline.pl rank <labels.tsv> | screen <labels.tsv> <stem> | tsv <labels.tsv> <a,b,...>\n" unless $mode && $tsv && ($mode eq 'rank' || (($mode eq 'screen' || $mode eq 'tsv' || $mode eq 'reach') && $stem));
my %want = map { $_ => 1 } split /,/, ($stem // '');
my %rail = (
    '01c_desk' => 'DESK', '02_statistics' => 'STATS', '03_decisions' => 'DOCKET', '04_demographics' => 'PEOPLE',
    '05_budget' => 'BUDGET', '06_policylaws' => 'LAWS', '07_politics' => 'POLITICS', '08_energy' => 'ENERGY',
);
open my $in, '<:encoding(UTF-8)', $tsv or die "$tsv: $!\n";
my $head = <$in>; chomp $head; $head =~ s/\r$//;
my @cols = split /\t/, $head; my %at; @at{@cols} = 0 .. $#cols;
for my $c (qw(capture x y width height font mode flags text)) { die "the table has no '$c' column\n" unless exists $at{$c}; }
my (%count, @rows);
while (my $line = <$in>) {
    chomp $line; $line =~ s/\r$//;
    my @f = split /\t/, $line, -1;
    next if ($f[$at{flags}] // '') =~ /OUTSIDE/;
    my $cap = $f[$at{capture}];
    $count{$cap}++;
    push @rows, [ $f[$at{font}], $f[$at{mode}], $f[$at{width}], $f[$at{text}] ] if ($mode eq 'screen' || $mode eq 'reach') && $cap eq $stem;
    push @rows, [ map { $f[$at{$_}] } qw(capture x y width height font mode text) ] if $mode eq 'tsv' && $want{$cap};
}
close $in;
if ($mode eq 'rank') {
    my @present = grep { exists $count{$_} } keys %rail;
    my @missing = grep { !exists $count{$_} } sort keys %rail;
    print "rank\tscreen\tvisible text draws at rest\tframe\n";
    my $i = 0;
    for my $s (sort { $count{$b} <=> $count{$a} || $a cmp $b } @present) { $i++; print "$i\t$rail{$s}\t$count{$s}\t$s\n"; }
    print "MISSING\t$rail{$_}\t-\t$_ (not in this table)\n" for @missing;
    exit(@missing ? 1 : 0);
}
if ($mode eq 'reach') {
    # s662 (UI v3.3 s1: a removed word no slip and no dense line reaches fails): People's words that left the page at rest (board 20a, table E),
    # each asserted on the dense frame's draws. The band values are the band slip's (a pointer's, not filmed) and are not listed here.
    my @need = ('21 FIVE-YEAR BANDS', 'BANDS SUM TO', 'WORKING AGE 15', 'VOTING AGE', 'OLD-AGE = 65+', 'SCHOOL-AGE SHARE', 'ELDERLY SHARE',
                'GROUPS, ONE INK', 'CONSTITUTION', 'NOT A FORECAST', 'THE MODEL\'S OWN ARITHMETIC', 'PopulationCohorts', 'CohortVoterGroups');
    my $all = join("\n", map { $_->[3] } @rows);
    my $miss = 0;
    for my $n (@need) { if (index($all, $n) >= 0) { print "reach\tok\t$n\n" } else { print "reach\tMISSING\t$n\n"; $miss++ } }
    printf "%s: %d of %d moved words reachable on the dense frame\n", $stem, @need - $miss, scalar @need;
    exit($miss ? 1 : 0);
}
die "no visible draws for '$stem' in $tsv\n" unless @rows;
if ($mode eq 'tsv') {
    print "capture\tx\ty\twidth\theight\tfont\tmode\ttext\n";
    print join("\t", @$_), "\n" for @rows;
    printf STDERR "%s\t%d visible text draws at rest\n", $_, $count{$_} // 0 for sort keys %want;
    exit((grep { !$count{$_} } keys %want) ? 1 : 0);
}
print "font\tmode\twidth\ttext\n";
print join("\t", @$_), "\n" for @rows;
printf STDERR "%s: %d visible text draws at rest\n", $stem, scalar @rows;
