#!/usr/bin/perl
# THE B1 VETO RULE BACKTESTED ON THE 10TH SEJM'S RECORD - written whole, every miss listed (Elias's ruling E4, COMPLETED.md s775).
# Reads ElectionsData/poland/third_readings_term10.csv (every whole-bill third reading of the term, the PiS club's votes, the outcome) and
# ElectionsData/poland/veto_record.csv (the 53 vetoes and their full titles), and writes docs/generated/VETO_B1_BACKTEST.md:
#   the confusion matrix (B1 fires / does not, against vetoed / signed / sent to the Tribunal), per president and for the term;
#   the hit rate (recall), the precision; Nawrocki's window; every veto B1 misses; every act B1 names that was not vetoed.
# B1 (ruled 2026-10-02, s757): the President vetoes an ordinary statute when MORE THAN HALF of his backing party's club MEMBERS at the vote
# (absent included) voted NO; the budget act (veto_exempt) is never vetoed. The president is the one on the day of the DECISION (outcome_date):
# Andrzej Duda to 2025-08-05, Karol Nawrocki from 2025-08-06; PiS backs both. An undecided act (pending, at the Senate) is outside every count.
# Usage (from the project root): perl Tools/veto_b1_backtest.pl [out]   (out defaults to docs/generated/VETO_B1_BACKTEST.md)
# The CSV reader is RFC 4180 (quoted fields, doubled quotes) - the term's titles carry commas and quotes. Dies on any parse anomaly.
use strict;
use warnings;
use utf8;

my $out = $ARGV[0] // 'docs/generated/VETO_B1_BACKTEST.md';
my $D = 'ElectionsData/poland/';

sub read_csv {
    my ($path) = @_;
    open my $fh, '<:encoding(UTF-8)', $path or die "$path: $!";
    local $/;
    my $s = <$fh>;
    close $fh;
    my (@rows, @row);
    my ($field, $inq, $i, $n) = ('', 0, 0, length $s);
    while ($i < $n) {
        my $c = substr($s, $i, 1);
        if ($inq) {
            if ($c eq '"') {
                if ($i + 1 < $n && substr($s, $i + 1, 1) eq '"') { $field .= '"'; $i += 2; next; }
                $inq = 0; $i++; next;
            }
            die "$path: a field runs over a line\n" if $c eq "\n";
            $field .= $c; $i++; next;
        }
        if ($c eq '"') { die "$path: a quote inside an unquoted field\n" if length $field; $inq = 1; $i++; next; }
        if ($c eq ',') { push @row, $field; $field = ''; $i++; next; }
        if ($c eq "\r") { $i++; next; }
        if ($c eq "\n") { push @row, $field; push @rows, [@row]; @row = (); $field = ''; $i++; next; }
        $field .= $c; $i++;
    }
    push @row, $field if length($field) || @row;
    push @rows, [@row] if @row;
    die "$path: an unterminated quote\n" if $inq;
    my $head = shift @rows;
    my @recs;
    for my $r (@rows) {
        next if @$r == 1 && $r->[0] eq '';
        next if $r->[0] =~ /^#/;
        die "$path: a row of " . scalar(@$r) . " fields against a header of " . scalar(@$head) . "\n" unless @$r == @$head;
        my %x;
        @x{@$head} = @$r;
        push @recs, \%x;
    }
    return \@recs;
}

my $readings = read_csv($D . 'third_readings_term10.csv');
my $vetoes = read_csv($D . 'veto_record.csv');

sub outcome { my $o = shift; return 'vetoed' if $o eq 'vetoed'; return 'signed' if $o =~ /^signed/; return 'Tribunal' if $o =~ /^referred to Tribunal/; return undef; }
sub president { $_[0] lt '2025-08-06' ? 'Duda' : 'Nawrocki' }
sub fires { my $x = shift; 2 * $x->{pis_no} > $x->{pis_members} }

my @decided = grep { defined outcome($_->{outcome}) && $_->{veto_exempt} eq '' } @$readings;
die "no decided act read\n" unless @decided;
for my $x (@decided) { die "PiS's counts do not sum to its members at $x->{sitting}/$x->{vote_no}\n" unless $x->{pis_yes} + $x->{pis_no} + $x->{pis_abstain} + $x->{pis_absent} == $x->{pis_members}; }

my %cell;
for my $x (@decided) { $cell{president($x->{outcome_date})}{fires($x) ? 'yes' : 'no'}{outcome($x->{outcome})}++; }
sub c { my ($p, $f, $o) = @_; my $n = 0; for my $pp ($p eq 'term' ? qw(Duda Nawrocki) : ($p)) { $n += $cell{$pp}{$f}{$o} // 0; } return $n; }
sub pct { my ($a, $b) = @_; return $b ? sprintf('%.1f %%', 100 * $a / $b) : '-'; }

my %vetoTitle;
for my $v (@$vetoes) { $vetoTitle{"$v->{third_reading_sitting}/$v->{third_reading_vote_no}"} = $v->{act_title}; }

open my $o, '>:encoding(UTF-8)', $out or die "$out: $!";
print $o "<!-- GENERATED by Tools/veto_b1_backtest.pl. DO NOT EDIT BY HAND. Re-derive: perl Tools/veto_b1_backtest.pl -->\n";
print $o "# B1 backtested on the 10th Sejm's record - every miss\n\n";
print $o "The rule (Elias's ruling B1, COMPLETED.md s757): the President vetoes an ordinary statute when more than half of his backing party's club\n";
print $o "members at the vote (absent included) voted NO. Read on `ElectionsData/poland/third_readings_term10.csv` and `veto_record.csv` (the Sejm API's\n";
print $o "own record); the president is the one on the decision's day; budget acts and undecided acts are outside every count.\n\n";
print $o "## The confusion matrix\n\n| President | B1 fires | vetoed | signed | to the Tribunal | total |\n|---|---|---:|---:|---:|---:|\n";
for my $p (qw(Duda Nawrocki term)) {
    for my $f (qw(yes no)) {
        my ($v, $s, $t) = (c($p, $f, 'vetoed'), c($p, $f, 'signed'), c($p, $f, 'Tribunal'));
        print $o "| " . ($p eq 'term' ? 'the whole term' : $p) . " | $f | $v | $s | $t | " . ($v + $s + $t) . " |\n";
    }
}
print $o "\n## The rates\n\n";
for my $p (qw(Duda Nawrocki term)) {
    my $vet = c($p, 'yes', 'vetoed') + c($p, 'no', 'vetoed');
    my $named = c($p, 'yes', 'vetoed') + c($p, 'yes', 'signed') + c($p, 'yes', 'Tribunal');
    my $all = $named + c($p, 'no', 'vetoed') + c($p, 'no', 'signed') + c($p, 'no', 'Tribunal');
    printf $o "- **%s**: hit rate %d of %d vetoes (%s); precision %d of the %d acts B1 names (%s); %d of %d decided acts vetoed (%s).\n",
        ($p eq 'term' ? 'The whole term' : $p), c($p, 'yes', 'vetoed'), $vet, pct(c($p, 'yes', 'vetoed'), $vet), c($p, 'yes', 'vetoed'), $named, pct(c($p, 'yes', 'vetoed'), $named),
        $vet, $all, pct($vet, $all);
}
print $o "\n## Every veto B1 misses\n\n";
my $k = 0;
for my $x (sort { $a->{outcome_date} cmp $b->{outcome_date} } grep { outcome($_->{outcome}) eq 'vetoed' && !fires($_) } @decided) {
    $k++;
    my $key = "$x->{sitting}/$x->{vote_no}";
    printf $o "%d. **%s, vetoed %s** - PiS yes/no/abstain/absent %s/%s/%s/%s of %s%s - %s\n", $k, president($x->{outcome_date}), $x->{outcome_date},
        $x->{pis_yes}, $x->{pis_no}, $x->{pis_abstain}, $x->{pis_absent}, $x->{pis_members},
        ($x->{rozwojplus_yes} ne '' ? " (RozwojPlus $x->{rozwojplus_yes}/$x->{rozwojplus_no}/$x->{rozwojplus_abstain}/$x->{rozwojplus_absent})" : ''),
        $vetoTitle{$key} // $x->{title};
}
print $o "\n## Every act B1 names that was not vetoed\n\n";
for my $p (qw(Duda Nawrocki)) {
    my @l = sort { $a->{outcome_date} cmp $b->{outcome_date} || $a->{sitting} <=> $b->{sitting} || $a->{vote_no} <=> $b->{vote_no} }
        grep { president($_->{outcome_date}) eq $p && fires($_) && outcome($_->{outcome}) ne 'vetoed' } @decided;
    print $o "### $p - " . scalar(@l) . " acts\n\n| decided | outcome | Sejm vote | PiS yes/no/abstain/absent of members | the Sejm's agenda title |\n|---|---|---|---|---|\n";
    for my $x (@l) {
        (my $t = $x->{title}) =~ s/\|/\//g;
        printf $o "| %s | %s | %s/%s (%s) | %s/%s/%s/%s of %s | %s |\n", $x->{outcome_date}, outcome($x->{outcome}), $x->{sitting}, $x->{vote_no}, $x->{date},
            $x->{pis_yes}, $x->{pis_no}, $x->{pis_abstain}, $x->{pis_absent}, $x->{pis_members}, $t;
    }
    print $o "\n";
}
close $o;
print "WROTE $out - " . scalar(@decided) . " decided ordinary statutes; B1 names " . (c('term', 'yes', 'vetoed') + c('term', 'yes', 'signed') + c('term', 'yes', 'Tribunal'))
    . ", catches " . c('term', 'yes', 'vetoed') . " of " . (c('term', 'yes', 'vetoed') + c('term', 'no', 'vetoed')) . " vetoes\n";
